### ISSUE TITLE
don't strip conditional comments!

### ISSUE THREAD

**Issue by simonwiles** [htacg/tidy-html5#104]
it would be great if an option were available to strip regular HTML comments, but leave IE conditional comments intact.  i don't know if there would be any interest in implementing this option here, but it would be worth considering, imo.  thanks!

**Comment by geoffmcl** [comment]
Yeek, being the coder, who long ago now, spent quite some time on improving 
Tidy's ability to clean out lots of that conditional stuff, especially 
that produced by Word 2000, hence the word-2000 option, I would very unlikely 
be the person to now, what exactly?, partially avoid some things ;=))

As to re-writing Tidy in other languages, I can only say "have a go!"... but 
I was not aware C/C++ devs were a dying breed ;=))

**Comment by geoffmcl** [comment]
@simonwiles @marcoscaceres @sideshowbarker on reviewing this issue seems there is nothing for me to do as a C code at this time ;=)).

So I'll close this, but feel free to re-open, or open new issues. Thanks for reporting...

Also note the latest and greatest is in the master branch, as we head towards a 5.0.0 release.
