### ISSUE TITLE
Have an option to disable munging entirely

### ISSUE THREAD

**Issue by jay** [htacg/tidy-html5#117]
This is a feature request for an option disable munging entirely. I have HTML documents that I am converting to XML and I need to preserve the whitespace in between the tags. For example:
<code>&lt;span&gt;&nbsp;&nbsp;A&nbsp;&nbsp;B&nbsp;&nbsp;&lt;/span&gt;</code>

I walked through the code and wrote some options that worked for me to allow the broken stuff I want to passthrough.  jay@c12dbb2 (original) ; jay@8a7b55d (now) . As long as I've set `tidyOptSetInt(tidyDoc, TidyWrapLen, 0)` it works ok.

**Comment by balthisar** [comment]
@jay, Sorry for the very long lack of a response. As you can see now, there's a lot of activity.

I wonder if you'd willing to turn this into a PR against the develop-500 branch? It's a bit incomplete now as this would be a new tidy option, and requires documentation, integration with the rest of the library, but if there's a valid use case an we're not breaking any standards, it's something we can consider.

I'll keep this open in the meantime without a commitment date.

**Comment by geoffmcl** [comment]
@jay first just a reminder that the main development branch is now `master`, and may shortly delete the develop-500 branch, although for the moment am trying to remember to keep them equal...

And would again apologize for a very tardy response... I hope we can be slicker next time ;=))

I have had a chance to review your simple changes to add a **new** option `OptBoolUnofficial_KeepMySpaces`, and if this is all that is required seems interesting...

Of course you would need to give it a name conforming to the tidy standard, like perhaps `TidyKeepMySpace` invoked by say `--keep-my-space yes`, default being `no`. 

And I can not see where you used the second option so perhaps this could be dropped...

And you would need to git rebase your clone back to `master`, or just delete it and start again since it is not that many changes... and you would need to add the xml information output in localize.c, which documents the meaning and use of the feature...

Then your feature would appear as a Pull Request that I could easily merge and test...

Anyway, as there has been no further comment on this issue in many months, and given that your original issue was raised over a year ago, am closing this for now...

Please feel free to re-open, or raise a new issue and/or a PR... thanks...

**Comment by vgandhe-102524** [comment]
I would like to re-open this issue. I have a customer who is using tidy, requesting for preserving the spaces. 
Could anyone comment on this if it is fixed in any dev branch ? I see the problem still exists in the latest version (tidy 5.8.0) of the tidy.  Can anyone suggest the workaround or fix  ?
