### ISSUE TITLE
Installation fails: "No such file or directory" (Mac OS X 9.4)

### ISSUE THREAD

**Issue by janaspage** [htacg/tidy-html5#123]
The [installation instructions](https://github.com/w3c/tidy-html5#building-the-tidy-command-line-tool) advise first entering `make -C build/gmake/` into the command line. However this outputs: 

    make: *** build/gmake/: No such file or directory.  Stop.

Am I supposed to change into a particular directory first? Thank you.

**Comment by geoffmcl** [comment]
The latest development branch, develop-500 now only uses a cmake build... can you check this branch
$ git pull and git checkout develop-500
We really need some tester in MAC OS X, since this is one I can not test in...
Report any problems in this cmake system, and will try to fix and assist if a problem in this branch...
