### ISSUE TITLE
a typo error: Enfo

### ISSUE THREAD

**Issue by kissferenc** [htacg/tidy-html5#129]
I got the following error: 
```
Enfo: <body> previously mentioned"
```

**Comment by geoffmcl** [comment]
Sorry for the delay in a reply...
Checked the latest development branch, develop-500
$ git checkout develop-500
And can not find 'Enfo' anywhere in the source?
Maybe it has been fixed in this development branch. If you get a chance please check again and report perhaps with a small html sample where this happen...

**Comment by geoffmcl** [comment]
Have searched again for this, but found nothing so will close this...

If you find it again, and supply a sample, feel free to re-open this...
