### ISSUE TITLE
Omitting optional BODY start tag yields undue warning

### ISSUE THREAD

**Issue by ezequiel-garzon** [htacg/tidy-html5#132]
The W3C standard [indicates](http://www.w3.org/TR/html5/syntax.html#optional-tags) that "Omitting an element's start tag in the situations described below does not mean the element is not present; it is implied, but it is still there. For example, an HTML document always has a root html element, even if the string <html> doesn't appear anywhere in the markup."

It is therefore hard to understand why `tidy` yields the warning `inserting implicit <body>` when evaluating the following input:

    <!doctype html>
    <meta charset=utf-8>
    <title>Sample</title>
    <h1>Sample</h1>

If anything, *all* omitted tags are eventually inserted by the parser, so why bring up this particular warning? (Removing whitespace doesn't remove the warning.) The above code is validated by the W3C validator.

**Comment by geoffmcl** [comment]
Sorry for the delay on a reply...
Agree the validator does not flag this as a warning...
So have disabled emitting a warning for inserting BODY in the development branch, develop-500
Please pull, git checkout develop-500 and retest... if satisfied please close... 
Thanks for your report...

**Comment by ezequiel-garzon** [comment]
Thanks for the reply, Geoff! I can't verify this, as I'm getting errors when I try to build it. I'm not an advanced user, so please handle this issue however you see fit. Thanks for your work!

**Comment by balthisar** [comment]
@ezequiel-garzon, what types of build errors and what's your build environment? We can help you in this thread if it's your error ;-)  Or if it's a reproducible build problem then we'd like to address that with another bug report.

**Comment by ezequiel-garzon** [comment]
@balthisar Thanks for your interest, Jim. Let me first say that I don't (yet!) know how to use git... so I just downloaded the new zip at github. Here is what I get as root:

    # make -C build/gmake
    make: Entering directory `/home/eze/sb/tidy-html5-master/build/gmake'
    make: Nothing to be done for `all'.
    make: Leaving directory `/home/eze/sb/tidy-html5-master/build/gmake'
    # ls build/gmake/
    Makefile  obj  readme.txt

Any thoughts will be appreciated. Thanks!

**Comment by geoffmcl** [comment]
Hi ezequiel-garzon,

Glad you got a chance to try... let me see if I can help...

1: Did you switch the branch to develop-500 BEFORE you downloaded the zip?
Upper left should show branch: master v
Click on the down arrow, and choose 'develop-500'
Then it should show branch: develop-500 v

Then clicking Download ZIP, and you should get a tidy-html5-develop-500.zip after 
that... That will unzip into a directory tidy-html5-develop-500.

2: This branch does NOT have any Makefile, nor a build/gmake directory... It uses 
cmake... I also have Ubuntu 14.04 LTS... so if cmake is not already installed, run 
$ sudo apt-get install cmake

Now as the readme states, to build should be as simple as, get into the build/cmake directory,
and run cmake ../.., like -
$ cd tidy-html5-develop-500/build/cmake
$ cmake ../..
$ make
and if desired
$ sudo make install

Advise if any problems with any part of this...

3: git is also very easy. To install it -
$ sudo apt-get install git

Now you can clone the repo into a tidy-html5 directory with -
$ git clone https://github.com/htacg/tidy-html5.git
OR
$ git clone git@github.com:htacg/tidy-html5.git

Then to switch to the develop-500 branch -
$ cd tidy-html5
$ git checkout develop-500

Then to build, as above - get into the build/cmake directory, and run cmake ../..
$ cd build/cmake
$ cmake ../..
$ make
and if desired
$ sudo make install

Once you have git cloned like this you can keep up with the 
latest at any time with - no more zip needed...
$ cd tidy-html5
$ git pull
and it will be updated...

Hope this helps... but advise if any problems... I am sure they can be solved ;=))

Regards,
Geoff.

**Comment by ezequiel-garzon** [comment]
Thanks for your help and patience, Geoff: that was a very detailed post. I'm now able to run the latest version of tidy5! I will try git as you mentioned. I assume I must follow the three steps you provided above each time I run git pull, right?

While the example I gave now runs successfully, a minor modification gives warnings (and "info"):

    $ cat sample.html 
    <!doctype html>
    <meta charset=utf-8>
    <title>Sample</title>
    Sample
    $ tidy5 -qe sample.html 
    line 4 column 1 - Warning: plain text isn't allowed in <head> elements
    line 2 column 1 - Info: <head> previously mentioned

Here again the W3 validator is OK with the file. Should I open new issues? Should I close this one? I know best practices indicate to explicitly include all tags, be they optional or not, but I guess that's the main distinction from XHTML, which makes validation much more predictable. As an aside I wonder (if you are willing to digress) why this project doesn't use "the same technology" used by the W3 validator. Aren't the two teams duplicating efforts? (I clearly like having a CLI tool!) Thanks once more!

**Comment by geoffmcl** [comment]
Hi ezequiel-garzon,

Ah, yes, I did overlook the warning if you omit the optional
tags... Maybe leave this open to remind me to look at that,
rather than creating a new issue...

Glad you got a tidy5 working ;=)) And hope you get the chance
to use the git clone so you can stay at the latest code easily
with just git pull...

After a git pull, yes it is safer to always run the 3 steps,
but if there has been no change in the CMakeLists.txt, which
may indicate a new or different source, version, etc, then the
Makefile would still be valid, so you can just run make...

But sometimes after a very substantial source change, it in fact
may be necessary to delete the CMakeCache.txt and the CMakeFiles
directory, because cmake tries to avoid doing everything again on
a second and subsequent runs, and sometimes previous values in
these can cause problems... not often...

Concerning the validators, I do not really know, but I think in
the early days the validator tried to use Tidy, and does in fact
still use the now OLD version if you add the option to 'Clean up
Markup with HTML-Tidy'. We hope they update that when we eventually
release Tidy 5.0.0...

And I guess another reason is that tidy development sort of
'died' for a while after the 2009 release... I have looked at
the source of both the validator and validator/nu, and see
they use a big mixture - perl, python, java, cgi - too much for
me to understand ;=()

I too was hoping we could share some tables or something,
but for the present it is a bit of a duplicated effort...

But this also reminded me to have a quick look at the
tidyperl wrapper - HTML::Tidy, which uses a C++ wrapper,
and SWIG to generate the code, and add that to the things to
do as we march towards the next release...

And then there is a TidyUI (GUI), and other language bindings...
Python, Java, COM/ATL, always a zillion things to play with ;=))

Regards,
Geoff.

**Comment by geoffmcl** [comment]
Difficult decision to avoid this warning when no optional tags are present, in this case ```<body>```.

Decided only if --omit-optional-tags yes is configured, thus indicating that they may also have been omitted in the source, avoid this warning.

Otherwise issue the warning since at that time tidy is parsing the ```<head>```.

Have bumped version point to 5 for this change.

Hope you are now using git since you can just do git pull, and re-build to get this update.

If satisfactory after testing please close this issue.

**Comment by ezequiel-garzon** [comment]
Thanks once more for your feedback, Geoff! I'll close this issue as I knew nothing about the option `--omit-optional-tags`, which is clearly what I was looking for.

As a last issue for now, how do you feel about [ambiguous ampersands](http://www.w3.org/TR/html5/syntax.html#syntax-ambiguous-ampersand) and such? E.g., `<p>A&E & this && even this` does not contain ambiguous ampersands, but it does yield a warning. In this case [so does the W3 validator](https://bugzilla.validator.nu/show_bug.cgi?id=841). Should I open a different issue or just let it be? I'm sorry to bring up so many edge cases! Once more, thanks wholeheartedly for your help. Cheers!

**Comment by geoffmcl** [comment]
No appolgy needed for 'edge' cases... subtlety is part of Tidy ;=))

Given that I recently argued in #88, that it was ok for Tidy to 'silently' fix-up ```<``` and ```>```, that is no warning issued, perhaps the 3 warnings issued for ```<p>A&E & this && even this</p>``` is excessive!

I note that the validators only flags the first! And of course the tidied output passes the validators with flying colors...

Have always been of two minds about 'silent' fix-ups, but given that there are probably a number of other 'silent' fix-ups, so I suppose I'd opt for suppressing these warnings... or not...

Just do not like the sense that Tidy does things to my file without telling me, and thus in a way helping in my html education and understanding. 

Maybe all these 'silent' actions need to be at a different level that gives notice of change, if say --show-silent-fixes on, but does not raise the error exit level.

Sorry to be so ambiguous ;=))

**Comment by ezequiel-garzon** [comment]
Ambiguity when referring to ambiguous ampersands is a nice touch! I agree with the fact that a finer distinction would be a great addition. For instance, writing `a&b,c`, which is valid markup, should not issue the same level of warning as `a&b;c`, which is not. Also, I must admit I like running `tidy5 -qe` more than using it to *tidy* my documents...
