### ISSUE TITLE
Code within JSP tags is not preserved

### ISSUE THREAD

**Issue by nkmathew** [htacg/tidy-html5#133]
Its indentation keeps increasing everytime I format the file. My config:

    indent:yes
    indent-spaces:2
    wrap:0
    tab-size:4
    newline:LF
    quiet:yes
    show-warnings:no
    add-xml-space:yes
    tidy-mark:no

Check out the gify.
![recording](https://cloud.githubusercontent.com/assets/5522822/4994029/cb3952e8-69c5-11e4-838b-ba6dae35ad0f.gif)

**Comment by geoffmcl** [comment]
Sorry for the delay in a reply...
Have tested this and confirm this still exists in the latest development branch, develop-500
It is a conflict between preserving JSP code spacing, and adding an indent...
Will see what can be done...

**Comment by geoffmcl** [comment]
[develop-500 0f80c08] Issue #133 - ever increasing indent!

Have made a simple but profound change in pprint.c to fix this 'bug'. A bug that has been around forever...

Since leading space is preserved on script code, after tidy indents the code once, a second run on that tidied file would add more indent to already indented code.

The fix is to skip any leading spaces in the text to be output by the amount of the indent.

This fix should be carefully checked, and removed if there are other bad consequences.

Bump the version point to 4 for this change.

**Comment by balthisar** [comment]
@nkmathew, can you confirm that this fix meets your requirements?

**Comment by nkmathew** [comment]
Works ok

-- 
nkmathew

**Comment by geoffmcl** [comment]
@nkmathew, as predicted the previous fix had adverse consequences on other tags, like script, which lost its indent, so reverted that commit!

But now found what I hope is a better fix, which for the moment only deals with an AspTag, but could apply to other text like tags...

Appreciate it if you get a chance to pull the latest develop-500 branch, compile and test again. Thanks...

The version should be 4.9.15 plus for this fix...

**Comment by balthisar** [comment]
@nkmathew, does this latest fix meet your expectation? Would like to get a chance to hear from you before closing this issue.

**Comment by nkmathew** [comment]
Sorry about that. I'm okay with this

On 2/23/15, Jim Derry <notifications@github.com> wrote:
> @nkmathew, does this latest fix meet your expectation? Would like to get a
> chance to hear from you before closing this issue.
>
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/htacg/tidy-html5/issues/133#issuecomment-75490739


-- 
nkmathew
