### ISSUE TITLE
Attempted to read or write protected memory & buggy translation

### ISSUE THREAD

**Issue by techresources** [htacg/tidy-html5#147]
I've two bugs to be reported.

(1)
I required a tool to repair HTML files having improper structure. So I tried implemented TidyManaged.dll with libtidy.dll. I developed c#.net window application using .net framework 4. Upon calling doc.save() function, I'm getting below mentioned exception msg.

Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

This is the piece of code I'm using.

    private void btnOk_Click(object sender, EventArgs e)
    {
        try
        {
            using (Document doc = Document.FromString(txtOriginal.Text))
            {
                doc.ShowWarnings = false;
                doc.Quiet = true;
                doc.OutputXhtml = true;
                doc.CleanAndRepair();
                string parsed = doc.Save();
                txtNew.Text = parsed;
            }
        }
        catch (Exception ex)
        {
            MessageBox.Show(ex.Message);
        }
    }

I'm getting exception msg upon calling Save method of document. "string parsed = doc.Save();"

(2)
Another issue is : I'm trying to repair HTML file using online utlity.
URL : http://infohound.net/tidy/

it converts the 
````<p class="MsoNormal"><span style="font-family:"Palatino","serif""><o:p> </o:p></span></p>````
to 
````<p class="MsoNormal"><span style="font-family:">&nbsp;</span></p>````

![1](https://cloud.githubusercontent.com/assets/10723816/5917373/f096b766-a641-11e4-94aa-2e17d2ef82e1.png)
![2](https://cloud.githubusercontent.com/assets/10723816/5917372/f0907216-a641-11e4-8d15-83204d0f07fc.png)
![3](https://cloud.githubusercontent.com/assets/10723816/5917405/382968bc-a642-11e4-8b32-42ada4e3db3a.png)

.
removes fonts name.

**Comment by geoffmcl** [comment]
Hi techresources,

Thank you for moving the bug report to here, but
please do not put two issues in one... that is
very confusing...

But concerning your No 1. exception msg, you have really
added nothing more than was in your original report!
Well except for the images...

So I can ONLY repeat the comments and questions from
my reply -

Please be aware that the continued development of
HTML Tidy has moved to -
https://github.com/htacg/tidy-html5/tree/develop-500

Note that is the develop-500 branch, not master...
Thus obviously only bugs against the branch will be
worked on...

If you have the capability of cloning the above repo,
switching to the develop-500 branch, and compiling a
new libtidy.dll, then maybe you could test against
that ...

If you do not have that capability, then we are working
hard to do a new release of Tidy 5.0.0 in the shortest
possible time, hopefully weeks...

But in any case it would be appreciated if you could
narrow down in exactly what circumstances the exception
occurs, or does it happen every time...

If it can be narrowed to a minimal html case, maybe
I could test such a case against the current development
code...

Oh, and also where is the source of TidyManaged.dll? Is
this what you have written in c#.net? I have/use MSVC10...
can I run your source?

So please answer the questions and address the comments
in there...

And since from the images I can see you are using MSVC IDE,
so you should be able to Debug trace into doc.Save(),
and point out exactly what happens... You will need to
be using a Debug version of tiydlib.dll for this...

Or maybe even link WindowsFormsApplication1 to the Debug
static library...

Further I note this is a very messy MS Word generated
html file... always very difficult... it adds so much
proprietary stuff... but Tidy tries... if configured
to clean a word document...

Concerning your no 2, that is NOT really a bug. For sure
when we reach a release of Tidy 5.0.0, we would need to
keep that site, and several others like it, like the W3C
validator, in mind, and encourage them to update to the
latest Tidy... but we are NOT at that point yet...

I will add a note to my 'things to do on release', so
thanks for pointing it out... so no need to create another
issue now...

But to be able to try to help on No 1, need MORE
information...

And finally to post html code to here you need to escape
it like I added to your post, like this -
````<htm><p>escaped html</p></html>````

Regards,
Geoff.

**Comment by techresources** [comment]
Hi Geoff,

Thanks a lot for prompt response.

Kindly provide downloadable link of Tidy v4.0.0.0  Dll and source code if possible.
So, we can try it on latest dll version.

regards,
techresources

**Comment by geoffmcl** [comment]
Hi techresources,

Source:
=======

All the source is in the git repo -
https://github.com/htacg/tidy-html5

Clone source:
$ git clone git@github.com:htacg/tidy-html5.git
or using https -
$ git clone https://github.com/htacg/tidy-html5.git

Switch to develop-500 branch - IMPORTANT -
$ cd tidy-html5
$ git checkout develop-500

Building:
=========

Need CMake installed - http://www.cmake.org/download
There is a simple to use Windows installer which
will set things up... and you obviously have MSVC
installed...

For 32-bit static version
$ cd build\cmake, and run build-me.bat

For 64-bit static version
$ cd build\win64, maybe adjust and run build-me.bat

For the DLL builds in the respective build-me.bat
files add a line, obviously after the
CMAKE_INSTALL_PREFIX lines -
@set TMPOPTS=%TMPOPTS% -DBUILD_SHARED_LIB:BOOL=ON
and run the build-me.bats...

Runtime Binaries:
=================

We do not yet have a 'public' place to put these,
and a question to Jim, Ionel, or others, what would
be your ideas on this... somewhere I, or others, can
easily upload binaries too... and be publicly
available for downloads...

So for the moment I have put a full set on my
site, in a single zip, all in a bin folder -

http://geoffair.org/tmp/tidy5-bin-4.9.1.zip

It contains static and dll libraries, and the exe
for dll32, dll64, static32 and static64, all built
by MSVC 10, so all in the msvc100 sub-folder.

You did NOT tell me your version of MSVC, nor
whether you are in a 32 or 64-bit OS... and
if your MSVC supports 64-bits...

Over time, I, or others, could probably provide
binaries for each version of MSVC, in different
Windows versions... Mine were using Windows 7,
64-bits...

But these are ONLY needed if you are unable to
build from the cloned SOURCE yourself...

The Tidy version 4.9.1 will increase as fixes
are added, 4.9.2, 4.9.3, etc, etc, until we are
tested and ready for a 5.0.0 release...

Thank you for using Tidy, and look forward to
hearing good results ;=))

Regards,
Geoff.

**Comment by geoffmcl** [comment]
@techresources I have moved your second issue to #156 and answered it there...

Have you had a chance to download and test the libtidy DLL I posted? 

Alternatively can you post your c#.net window application source somewhere so I can compile and try it with the latest tidy5 code? Thanks...

**Comment by balthisar** [comment]
I'll close this. @techresources, feel free to re-open this issue if it's still unresolved.
