### ISSUE TITLE
newlines inserted in <pre> tags

### ISSUE THREAD

**Issue by bobbens** [htacg/tidy-html5#158]
I've been hitting my head at this but can't see a way around it. What is happening is that my code like:

```
<pre>No newline here.
    Some indented content with newline.
Again no newline</pre>
```

Becomes:

```
<pre>
No newline here.
   Some indented content with newline.
Again no newline.
</pre>
```

Basically it is inserting a newline after the `<pre>` tag and before the `</pre>` tag. It should not touch anything inside the `<pre></pre>` area.

**Comment by geoffmcl** [comment]
@bobbens, thanks for adding this issue, but as far as I can see tidy has been adding these two newlines, one after a `<pre>` and one  before the `</pre>` since **BEFORE** the year **2000**, so this is a **VERY OLD** tidy feature ;=))

Also from several browser viewing tests, it seems browsers generally ignore these two newline characters. That is most browsers rendering it the same whether they are added or not, so it does not harm the document view...

On the other hand we do have a feature request to have an option to reduce the vertical spacing in tidy documents, and are considering this, but it have been marked as a 'feature', and no definitive milestone added at this time... see #163 ...

Accordingly I am re-labeling this as a feature, and assure you this would be looked at again if we do try to support a reduce vertical spacing option, since this would be another easy place to remove vertical spacing in the output.

**Comment by bobbens** [comment]
This can be, but on my set up this does introduce a large white-space below and above which makes it very visually unappealing. In fact, for my particular application this is the only show stopper I have found that prevents me from using tidy in my production environment. I look forward to it being fixed someday.

**Comment by camoy** [comment]
Stumbled over this bug today and was very frustrating (I had no idea where the extra newline was coming from). The newline before the ending `</pre>` __is__ rendered in my version of FF and Chrome. I hope this is fixed soon!

**Comment by geoffmcl** [comment]
@bobbens @camoy - Now we are post 5.0, `master` is now 5.1, and open for development, this **OLD** `bug` is revived... any help appreciated...
