### ISSUE TITLE
Multiple <main> elements allowed

### ISSUE THREAD

**Issue by michaeljwilliams** [htacg/tidy-html5#166]
Tidy does not complain about the usage of more than one main element in a single document, which is not allowed.

**Comment by geoffmcl** [comment]
@michaeljwilliams have coded a fix for this bug in the develop-500 branch, and bumped version to 4.9.16. If you get a chance pull the latest, and re-test. Thanks for the report.

**Comment by michaeljwilliams** [comment]
I'd like to, but I can't get CMake to work and thus can't compile.

**Comment by geoffmcl** [comment]
@michaeljwilliams - that's BAD... tell us more of the problem and we may be able to help...

What OS are you working in? Have you used CMake before? Does it work for other projects, or just a problem with tidy source? What cmake command did you use, or are you using the cmake-gui? Also give the full source directory, and the chosen build directory... etc...

I am out of time tonight... but be back tomorrow... but maybe other can help...

**Comment by michaeljwilliams** [comment]
I'm on OS X Mavericks. I've never (successfully) used CMake before. I simply tried to follow the instructions in the tidy readme. After I figured out that I needed to install CMake in order to follow the instructions (that wasn't clear), I found it online and installed it. I tried to compile tidy in the GUI and that threw errors at me, then I tried to install the CLI tools from CMake and that threw errors at me as well.

**Comment by geoffmcl** [comment]
@michaeljwilliams , ok I am Windows and Linux... no experience with OS X... but read some others had trouble getting CMake installed and working properly... I am sure one or more of our OS X users can help... hang in there ;=)) I'm sure we can get it working...

**Comment by balthisar** [comment]
Hi @michaeljwilliams, if possible uninstall the cmake GUI, and try to follow these steps in Terminal. I'm going through them a step at a time on a virgin copy of Mac OS X 10.9.5 with all software updates applied.

##CMake
```
cd ~/Downloads
curl -O http://www.cmake.org/files/v3.2/cmake-3.2.0-rc2.tar.gz
gunzip -c cmake-3.2.0-rc2.tar.gz | tar xopf -
cd cmake-3.2.0-rc2
./bootstrap
```
At this point Mac OS X may ask you to install the command line developer tools, if they're not already installed. Go ahead and do it. _If_ you had to install these tools, then try again:

`./bootstrap`

Continuing...

```
make
sudo make install
```

Now you have a working CMake.

## Tidy
```
cd ~/Downloads
git clone https://github.com/htacg/tidy-html5.git
cd tidy-html5/build/cmake
cmake ../.. -DCMAKE_INSTALL_PREFIX=~/Downloads
make
make install
```

When make is done, you will find all of the build files in your Downloads folder. The actual binary will be in `~/Downloads/bin/`. If you prefer to install Tidy "properly" then instead of the last two lines above, do this:

```
cmake ../..
make
sudo make install
```

Again, apologies for the inconvenience. The idea is that for 5.0.0 (i.e, when we release) we will have binaries for all of the major platforms.

**Comment by michaeljwilliams** [comment]
Thanks @balthisar I finally got it working, although I had to sh bootstrap rather than just trying to run it with ./bootstrap. And the bug is now fixed. Nice work.

![screen shot 2015-02-25 at 1 36 08 pm](https://cloud.githubusercontent.com/assets/10594600/6381124/a67c1bc6-bcf3-11e4-97fc-a5c8d745a1b3.png)
