### ISSUE TITLE
<p> moved out of <a>

### ISSUE THREAD

**Issue by ralfjunker** [htacg/tidy-html5#169]
Revision: 2e383c6
Date: 28.02.2015 20:32:38

Tidy moves a &lt;p&gt; tag out of an &lt;a&gt; tag.

Example:
```html
<a href="l1"><p>one</p></a>
```
Tidy processes this to:
```html
<!DOCTYPE html>
<html>
<head>
<title></title>
</head>
<body>
<a href="l1"></a>
<p>one</p>
</body>
</html>
```
Testing with FireFox 36, the &lt;p&gt; tag stays within the &lt;a&gt; tag.

Should not Tidy behave the same?

**Comment by geoffmcl** [comment]
@ralfjunker, yes this is a real **problem!** It stems from trying to keep HTML4-- parsing while trying to also correctly parse HTML5++

Others have tried to 'fix' this by redefining the TidyTag_A, bringing it into line with HTML5++

`{ TidyTag_A, "a", ... (CM_INLINE|CM_BLOCK|CM_MIXED), TY_(ParseBlock), ...`

But this led to other problems when parsing HTML4--, so I have reverted it to -

`{ TidyTag_A, "a", ... (CM_INLINE), TY_(ParseInline), ...`

For sure the following HTML5 sample, passes the W3C validator with no problem -

````
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>p moved out of a #169</title>
</head>
<body>
<a href="l1"><p>one</p></a>
</body>
</html>
````

But make a few changes, bringing it back to HTML4, and the validator will complain strongly -

````
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" 
"http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8">
<title>p moved out of a #169</title>
</head>
<body>
<a href="l1"><p>one</p></a>
</body>
</html>
````

And of course most browsers will display them the same, with the 'one' as a link... they have no role or interest in validating or fixing the document...

One **answer** to all this would be to have **two** separate tidy libraries - html4 and html5 - but I, and maybe others, hope it does not come to that...

For such a dual mode tidy the important question is at what point does tidy choose it is in html5 mode. There are some obvious indicators, like if the document has an earlier doctype, or the user has chosen a --doctype of not html5, then it should warn, and try to fix to suit. And if in html5 mode, should leave this alone...

Issue #167 is similar...

I seek **discussion**, and **help** on what I think is a tricky situation, but maybe there is a simple answer I have overlooked...

**Comment by balthisar** [comment]
This invites very serious discussion.

According to the [HTML5 reference](http://dev.w3.org/html5/html-author/#doctype-declaration) the only permitted doctype declarations for HTML5 are

- `<!DOCTYPE html>`
- `<!DOCTYPE html SYSTEM "about:legacy-compat">`

One might argue (and I'm necessarily arguing it, but only pointing it out) that today in 2015 with nearly everyone and every vendor on-board, we should expect that "html5 mode" is only ever triggered when Tidy detects these doctypes, otherwise fall back to legacy detection. It would _certainly_ make Tidy a lot more efficient if it could count on detecting this.

A big counterpoint, however, is that one of Tidy's key use cases is finding errors in HTML. One might argue that it's reasonable to assume that correcting a missing doctype (upon detecting the type of HTML) is a key function of Tidy.

If we were to decide that we needed two Tidy libraries - tidy4 and tidy5 - then we still have an issue wherein we expect the user to choose which library/executable to use in order to clean a document. If we have to default to forcing the user to make a choice, this choice already exists with --doctype.

(Geoff, correct me if I'm wrong: what would having two libraries gain us if still forcing the user to make a choice?)

Another possibility is to generate an warning: "Document content is ambiguous. Sorry. Please use a --doctype or specify a doctype in the source. Some changes in the output may not be desired." 

This is a tough call, and Geoff has raised this issue a few times in the past and never gotten the responses he's been seeking.

I wonder if we should take this to the mailing list?

**Comment by geoffmcl** [comment]
@balthisar You make a very good point about having **TWO** libraries is just another way of **FORCING** the user to choose. And if [s]he has to choose, then why not as a --doctype, or some other new parameter, on a **single** tidy?

And after your comments I am beginning to think the other way around on the html5 mode. It IS 2015, and html5 is getting lots of support, so tidy should default to html5 mode. That is if it finds NO doctype, like when given just a snippet of html, or finds one of the 2 declaration you mentioned, it STAYS in html5 mode.

So **ONLY** if given another --doctype, or some new parameter, by the user, OR it detects other than a html5 doctype, will it exit html5 mode, and try to correctly handle the legacy documents with appropriate warnings and fixing.

Yes, I have raised this issue a few times, from a long way back. It needs a resolution, to establish the code path for tidy to follow, and agree it should be placed everywhere, and anywhere that will get peoples attention...

We really **NEED** lots of **FEEDBACK** on this **TOUGH** issue.

**Comment by geoffmcl** [comment]
@ralfjunker , @balthisar in line with the above have reverted the TidyTag_A to HTML5, and added a service TY_(AdjustTags) to change the table back to legacy mode if it find other than a HTML5 DOCTYPE.

Now tidy handles the above cases differently, and hope this fixes this issue, and #167 at the same time.

But still seek **reviews** and **discussion** on this...

**Comment by balthisar** [comment]
@geoffmcl, I brought it to the mailing lists. Let's see if we have any responses.

I favor the solution you introduced.

**Comment by subhaze** [comment]
I was on the edge of pushing for 2 versions, but I do see where this has many problems of it's own. To avoid solving problems with problems, I'm moving over to the side of defaulting to HTML 5 as @geoffmcl stated:

> And after your comments I am beginning to think the other way around on the html5 mode. It IS 2015, and html5 is getting lots of support, so tidy should default to html5 mode. That is if it finds NO doctype, like when given just a snippet of html, or finds one of the 2 declaration you mentioned, it STAYS in html5 mode.

**Comment by skeet70** [comment]
Just thought I'd chime in that I agree with this statement:

> It IS 2015, and html5 is getting lots of support, so tidy should default to html5 mode. That is if it finds NO doctype, like when given just a snippet of html, or finds one of the 2 declaration you mentioned, it STAYS in html5 mode.

I don't see any reason that a current and maintained library should default to what is no longer the industry standard. Providing the functionality to choose if necessary to set tidy to html4 mode, or switch if the DOCTYPE informs it, seems like the correct way to go.

**Comment by geoffmcl** [comment]
@skeet70 yes, tidy has now been coded with an initial `table` that conforms to html5, but if the document is found to be html4--, then the table is dynamically adjusted to suit. That is just by changing the DOCTYPE different parsing, and thus different warning/errors are issued...

Currently this only effects the anchor and caption tags, but there could be more to add... But now the process is there... also see Issues #167 and #196...

The code at https://github.com/htacg/tidy-html5/blob/master/src/lexer.c#L2751

Accordingly am closing this, but re-open or create a new issue if still a problem...

Thanks for your `chime` ;=))
