### ISSUE TITLE
Unexpected newline in block anchor output

### ISSUE THREAD

**Issue by jacksonp** [htacg/tidy-html5#179]
Input:
````html
<a id="Section" href="#Section"><h1>Section</h1></a>
````
`tidy5 -indent -wrap 400` output:
````html
<body>
  <a id="Section" href="#Section">
  <h1>Section</h1></a>
</body>
````
Expected output to be the same as input. pprint.c module issue, see also #167.

**Comment by Pajamaman** [comment]
I don't think this is strictly related to anchor tags but to all block level tags. This markup:

```
<center>
<a name="Notes"><h3>Notes on the Sessions</h3></a>
</center>

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
```

Gets turned into this:

```
<div style="text-align: center">
    <a name="Notes" id="Notes">
    <h3>
        Notes on the Sessions
    </h3></a>
</div>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
```

We seem to be missing line breaks after both the closing h3 tag and the closing div tag.

**Comment by geoffmcl** [comment]
@Pajamaman, well you can get back a line break after the closing div tag using `--vertical-space yes`, but this does not fix the line break after the closing h3 tag!

But you seem completely **opposite** to @jacksonp, the openner of this issue, in that, if I read correctly, in his sample he wants the ouput to be the same as his single line input. That is with **no** vertical space added at all. Can not see how **both** aims can be satisfied!

That is why I personally do not like trying to **fix** pretty print issues. It seems the definition of `pretty` depends far too much on just personal preferences, so there is no clear path for all... perhaps only by increasing the options... but we already have over 90, which I am sure some already consider too many...

That said, if you, @jacksonp, or others want to submit a patch or PR on these `vertical-space` issues, including adding or changing options, then they will certainly be considered...

**Comment by Pajamaman** [comment]
You're right, I didn't realize @jacksonp wanted the output on one line.

While I understand your frustrations with pretty print issues, I think the "correct" behavior in this case is to add line breaks around open and close tags for all block level elements. So this:

```html
<center>
<a name="Notes"><h3>Notes on the Sessions</h3></a>
</center>

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
```

Should become this:

```html
<div style="text-align: center">
    <a name="Notes" id="Notes">
        <h3>Notes on the Sessions</h3>
    </a>
</div>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
```

The code in the OP should become this:

```html
<a id="Section" href="#Section">
    <h1>Section</h1>
</a>
```

"Correct" in the sense that it would at least be consistent. If the user doesn't want the line breaks around the tags for a certain element, they should add the element name to the new-inline-tags option or disable pretty print altogether.

**Comment by geoffmcl** [comment]
@Pajamaman well it is not exactly `frustration`, just no **clear** direction for me, as your post indicates, suggesting a different **correct** behaviour to what @jacksonp **wants** ;=))))

As stated, if you, or others want to submit a patch or PR they will be considered... 

The giant tag table - https://github.com/htacg/tidy-html5/blob/master/src/tags.c#L168 - allows you to check if a tag has CM_BLOCK or not, if that is your criteria... you need to decide what to do if it also has CM_INLINE, and other bit combinations...

Of course the current pprint.c is a can-of-worms that has just grown, Grown, and GROWN as each idea was added... maybe it is time for a complete re-write, maybe offering a user-selectable alternative of say `void TY_(PPrintTree5)( TidyDocImpl* doc, uint mode, uint indent, Node *node )` ;=))

One immediate nice addition would be being able to use tabs instead of spaces for the indent - see #108.

And others like #205 - no wrap on '=', #189 - vertical spacing, #180 - bad indentation, #163 - unnecessary vertical whitespace, #158 - newline in pre tag, and probably some more that I have missed cross referencing...

Dig in, and make tidy do what you think is **correct** ;=))

**Comment by geoffmcl** [comment]
@jacksonp @Pajamaman as you may have read else where have fully updated the `master` branch, and it contains **lots** of `newlines` features, fixes, changes... version 5.1.8 (2015.09.04).

I hope you get a chance to pull it, and check it out ;=)) And make sure you try the **new feature** `--vertical-space auto` option...

Since this release addresses and changes some of the above `spacing`, will close this for now, but feel free to re-open, or post a new issue.

**Comment by jacksonp** [comment]
Thanks @geoffmcl, I still get the same issue as originally reported (I don't see that there's a way for me to re-open this tho).

Btw, with `--vertical-space auto`, unwanted white-space is added before `<h1>`. Output:
````html
... <a id="Section" href="#Section">  <h1>Section</h1></a> ...
````

**Comment by geoffmcl** [comment]
@jacksonp do not understand ;=((

Version: tidy -v
```
HTML Tidy for Windows version 5.1.8
```

Input: input5\in_179.html
```
<a id="Section" href="#Section"><h1>Section</h1></a>
```

Config: input5\cfg_179.txt

```
show-body-only: yes
show-info: no
vertical-space: auto
wrap: 0
```

Output:
```
<a id="Section" href="#Section"><h1>Section</h1></a>
```

No space??? Even if I add a space before the h1 in the input, and/or remove the show-body-only... **still no space before the h1**?

#### What am I doing wrong?

**Comment by jacksonp** [comment]
tidy -v
    HTML Tidy for Linux version 5.1.8
I get the same output as you if I remove the -indent option, so it's probably that?
