### ISSUE TITLE
Bad indentation with -omit

### ISSUE THREAD

**Issue by jacksonp** [htacg/tidy-html5#180]
Input:
````html
<!DOCTYPE html>
<meta something="">
<meta another="">
<title>Test</title>
````
Output of `tidy5 --tidy-mark false -omit -indent`:
````html
<!DOCTYPE html>

<meta something="">
  <meta another="">

  <title>Test</title>
````
Expected output: same as input.

**Comment by geoffmcl** [comment]
@jacksonp, thanks for the report...

Actually it seems the -indent causes the problem, not the -omit. Remove it as the output is the same as the input.

And with -indent have pushed a small change to avoid the extra blank lines. But the extra line can be brought back with --vertical-space yes.

**Comment by jacksonp** [comment]
I do want indentation in the output... I also want to use `-omit` and it looks like the two don't work well together. Input:
````html
<!DOCTYPE html>
<meta something="">
<meta another="">
<title>Test</title>

<div>
<a id="Section" href="#Section"><h1>Section</h1></a>
</div>
````
Output with `-omit -indent` (everything after the first `meta` tag in the implicit `head` and everything after the opening  `div` in the implicit `body` are off):
````html
<!DOCTYPE html>

<meta something="">
  <meta another="">

  <title>Test</title>

<div>
    <a id="Section" href="#Section">
    <h1>Section</h1></a>
  </div>
````
Output with just `-indent` looks good:
````html
<!DOCTYPE html>

<html>
<head>
  <meta something="">
  <meta another="">

  <title>Test</title>
</head>

<body>
  <div>
    <a id="Section" href="#Section">
    <h1>Section</h1></a>
  </div>
</body>
</html>
````

**Comment by geoffmcl** [comment]
@jacksonp as mentioned in #179, with the 5.1.8 release, there have been lots of `space` changes, so will close this for now...

Hope you get a chance to pull `master` and re-run your tests... thanks...

**Comment by jacksonp** [comment]
Problem persists in master as of latest commit (5ede47f). I see one difference: there is less vertical spacing than previously, but don't think that's important here. Input:
````html
<!DOCTYPE html>
<meta something="">
<meta another="">
<title>Test</title>

<div>
<a id="Section" href="#Section"><h1>Section</h1></a>
</div>
````

Output:
````html
<!DOCTYPE html>
<meta something="">
  <meta another="">
  <title>Test</title>
<div>
    <a id="Section" href="#Section">
    <h1>Section</h1></a>
  </div>
````

**Comment by geoffmcl** [comment]
@jacksonp again do not quite understand ;=((

Using your Input, as input5\in_180-2.html

Config: input5\cfg_180-2.txt

```
show-info: no
indent: yes
// same as -omit
omit-optional-tags: yes
```

Output:
```
<!DOCTYPE html>
<meta something="">
    <meta another="">
    <title>
      Test
    </title>
  <div>
      <a id="Section" href="#Section">
      <h1>
        Section
      </h1></a>
    </div>
```

I guess I could open issues on -

 - that the first meta does not get indented, and 
 - the fact that the div only got an indent of 2 spaces.

But I will let others do that if they feel strongly about them... and maybe present a PR...

These do **not** happen if `-omit` is **not** used, so it should not be difficult to exactly track down why these small space changes happen... it is all in pprint.c for sure...

Output:
```
<!DOCTYPE html>
<html>
  <head>
    <meta something="">
    <meta another="">
    <title>
      Test
    </title>
  </head>
  <body>
    <div>
      <a id="Section" href="#Section">
      <h1>
        Section
      </h1></a>
    </div>
  </body>
</html>
```

##### So again, what am I missing?

Of course, I have to **remove** the `indent: yes` if I want to use `--vertical-space auto`, else I will get indent space added all over the place in the output...

I guess something the tidy.c console app could do would be to, just before it loads the file, check for that auto is on, then cancel any indent... And in the help add that `--vertical-space auto` implies `indent: no`...

But I think that is a thing the user of the tidy library API, in this case tidy.c, should check, and **not** add such a contrary configuration check **inside** the library. Maybe the user wants indent space, or now tabs, added to the single line html output ;=))

So, yes, this answers why you got a `space` in #179. You guessed correctly... the -i otpion is kinder contrary to wanting a very **compact** html output offered by `auto`...

**Comment by jacksonp** [comment]
Yes, this bug is just about the indentation being off with `-omit`.

`--vertical-space auto` was just an aside as far as I can see.

**Comment by geoffmcl** [comment]
@jacksonp ok, agree `--vertical-space auto` was more an aside...

And sorry it took me so long to `understand` this issue, although it should have been clear from the title `Bad indentation with -omit` ;=))

But would also appreciate ideas on what would be the **best** indenting in this case... with `--indent-space 2` maybe -

Expected Output 1:

```
<!DOCTYPE html>
  <meta something="">
  <meta another="">
  <title>
    Test
  </title>
  <div>
    <a id="Section" href="#Section">
    <h1>
      Section
    </h1></a>
  </div>
```

But really the doctype is not really a tag, so why the first indent? Maybe this would be better -

Expected Output 2:

```
<!DOCTYPE html>
<meta something="">
<meta another="">
<title>
  Test
</title>
<div>
  <a id="Section" href="#Section">
  <h1>
    Section
  </h1></a>
</div>
```

And then again, perhaps it should exactly mirror the indented output like when `-omit` is not used, just removing the omitted tags -

Expected Output 3:

```
<!DOCTYPE html>
    <meta something="">
    <meta another="">
    <title>
      Test
    </title>
    <div>
      <a id="Section" href="#Section">
      <h1>
        Section
      </h1></a>
    </div>
```

Maybe this third is more easily achieved, especially since the current output is already very close to it. The other 2 have more space changes, maybe meaning more code changes...

Of course these are only a `target` expectation... depends on what is needed to **fix** the indent after a tag has been omitted...

What do you, or others, think?

Am re-opening to remind me to look at this, unless someone beats me to it with a PR!

**Comment by jacksonp** [comment]
Thanks @geoffmcl. As far as I'm concerned: I agree the doctype shouldn't alter the indentation, and don't think the extra layer of indentation for tags that aren't there is a good idea (Output 3). Output 2 is the closest, this is the output I'd expect from running `tidy -omit -indent`:
````html
<!DOCTYPE html>
<meta something="">
<meta another="">
<title>Test</title>
<div>
  <a id="Section" href="#Section"><h1>Section</h1></a>
</div>
````

**Comment by geoffmcl** [comment]
@jacksonp LOL, I could have guessed you would `prefer` the **most** difficult ;=))

And more than that, you threw in **few** other additional requests!!!

 - do not wrap in title element
 - do not wrap in anchor element
 - do not wrap in h1 element, maybe all header elements...

Tidy has been wrapping those elements since year dot ;=)) Way back to `Dave Raggett's Original` release dated 04 Aug 00, 15 years ago, which is the earliest tidy I have!!!

That is to say these newlines are **bred** into tidy, in it's soul, in it's blood... The new feature `--vertical-space auto` was to get rid of them **ALL**... but it can **not** be `selective`, and keep some!

To keep a newline for some selected elements, cases, situations, things and not others, would take some really severe work... and that is after such a RFC is fully defined... which elements, cases, etc...

In fact I think to achieve that and **not** mess up lots of other things you would be better off re-writing the entire pprint module... 

This is very unlikely to happen. Certainly not by me... so will treat those additional **requests** as an aside... I am sure some have been voiced, discussed in other issues...

I am not saying changing the 15 year old behavior of tidy should not be concsidered, just not as part of this specific `Bad indentation with -omit` issue...

So will take your vote as for Output 2:, a reasonable choice, which at this time also has my vote... +2 for Output 2: ;=))

Now to do some debug runs to see if I can figure out why, where, what can be done **only** about the `messy` indent... and see what solutions are available...

**Comment by geoffmcl** [comment]
@jacksonp Ok, have now done quite a few debug sessions to try to work out what is going on, but the pprint module is **very** difficult to follow... but think I found a solution...

The following are some notes... I find it helps me understand the process if I try to explain it all to others, in glory detail... so feel free to skip down to **That did it!** - the solution...

Now it turns out there is also an alias option for `omit-optional-tags`, namely `hide-endtags`. In the code they are uses OR-ed together -

```
    Bool hideend  = cfgBool( doc, TidyHideEndTags ) ||
                  cfgBool( doc, TidyOmitOptionalTags );
```

And this is used only once, thankfully, in the `TY_(PPrintTree)(...)`, the PP function, which is repeatedly called to output every node. 

PP checks for more than a dozen specific node types, and this is in the `else /* some kind of container element */`, which again checks for 2 or 3 more specific node types, and the above code is again in the final `else /* other tags */` section. 

So it is sort of in the `general-general` case... the GG case... read lots of nodes go through here...

In here the tag is only printed, if it is `!hideend`, or it has attributes, so after the specific service has output the doctype, the following `html` and `head` tags are skipped.

The next `meta` tag is printed as one of the `special` PP cases, and anything in the pprint buffer is flushed, but there is nothing at this time. That is it is a node with `TY_(nodeCMIsEmpty)(node)`, so the tag is added to the pprint line buffer...

Now the second `meta` arrives, and this will flush the first to actual output, and since the `WantIndent(doc)` returns `no`, no leading spaces are added to the first... and it is printed flush left... then the second meta tag is added to the pprint line buffer...

Then the `title` tag arrives, and this will flush the second `meta` to output, but now `WantIndent(doc)` returns `yes`, and indent spaces are output **before** that 2nd `meta` is output, so it is indented...

Now that is because on the flush of the 1st meta, `pprint->indent[ 0 ].spaces` got set to `indent` which is 4 at this time. And the first test in `WantIndent(doc)` is to check `pprint->indent[ 0 ].spaces` and if this is greater than zero do some more checks and return `yes`, so the second `meta` gets this indent 4...

Why is the indent equal to 4? One of the parameters passed to PP is this `uint indent` value. 

On the first call to PP with the `root` node, and the next `doctype` node it is zero(0). Thus when the doctype is flushed to output, the mysterious `pprint->indent[ 0 ].spaces` stays zero. That is `WantIndent(doc)` will return `no`.

Now one of the services called in this GG case, and in some other cases in the PP, is `ShouldIndent(doc,node)`. If this returns `yes`, then the `indent` will be bumped by `spaces`, which defaults to 2. And that incremented indent will be passed to the PP to print the child nodes...

So when the `html` node came through, indent is bumped to 2, even though it was not printed. And then when the `head` came through, indent is again bumped by 2, making it 4, even though it is also not printed...

Now there's the rub! We have accumulated an indent even though the tags were not output!!!

Hmmm, an idea. If tidy knew earlier that it was not going to print that tag, then also don't bump the indent... or alternatively reduce the bumped indent when the tag is not printed... Let me try that latter idea... the least easiest code change...

**That did it!** ;=)))))))))))))

Output 2:

```
<!DOCTYPE html>
<meta something="">
<meta another="">
<title>
  Test
</title>
<div>
  <a id="Section" href="#Section">
  <h1>
    Section
  </h1></a>
</div>
```

Patch:

```
diff --git a/src/pprint.c b/src/pprint.c
index 4b4593d..7d011e8 100644
--- a/src/pprint.c
+++ b/src/pprint.c
@@ -2312,6 +2312,15 @@ void TY_(PPrintTree)( TidyDocImpl* doc, uint mode, uint indent, Node *node )
                           (TY_(nodeHasCM)(node, CM_HEAD) && !nodeIsTITLE(node)) )
                     TY_(PFlushLineSmart)( doc, contentIndent );
             }
+            else if ( ShouldIndent(doc, node) )
+            {
+                /*\
+                 * Issue #180 - If the tag was NOT printed due to the -omit option,
+                 * then reduce the bumped indent under the same ShouldIndent(doc, node) 
+                 * conditions that caused the indent to be bumped.
+                \*/
+                contentIndent -= spaces;
+            }
 
             last = NULL;
             for ( content = node->content; content; content = content->next )
```

Appreciated it if you could cut that patch into your local master and give it a try...

I have to do some other work to do to update the `test/testbase` folder to the current 5.1.8 master output so that before I commit this simple patch, I can re-run the full test suite to make sure this patch has no other adverse consequences... but it looks very sane...

Be back soonest... probably a few days...

**Comment by jacksonp** [comment]
Thanks @geoffmcl, sounds epic... That patch does the trick!

**Comment by geoffmcl** [comment]
@jacksonp ok the update of the `test/testbase` proved easier than expected so that is done...

And have pushed this pprint.c fix. And bumpted the version to 5.1.9 (2015.09.10) for this change...

And as far as I can see it has no effect on the some 227 tests done by `alltest.cmd`...

Thanks for sticking with this, making me see this was a completely different issue to the space and newline issues I had put it in...

If you can confirm all is well, maybe you can finally close this issue ;=))

**Comment by jacksonp** [comment]
@geoffmcl I can confirm 5.1.9 fixes it, thanks again!
