### ISSUE TITLE
Minor fix for Linux/Unix systems

### ISSUE THREAD

**Issue by bdheeman** [htacg/tidy-html5#187]
Build and install needs some fix, please check the diff:

    diff --git a/CMakeLists.txt b/CMakeLists.txt
    index ede7483..176b5e9 100644
    --- a/CMakeLists.txt
    +++ b/CMakeLists.txt
    @@ -209,7 +209,7 @@ if (UNIX)
    VERBATIM
    )
    
    - install(FILES ${CMAKE_BINARY_DIR}/${TIDY_MANFILE} DESTINATION local/man/man1)
    + install(FILES ${CMAKE_BINARY_DIR}/${TIDY_MANFILE} DESTINATION ${CMAKE_INSTALL_PREFIX}/man/man1)
    endif ()
    endif ()
    
    diff --git a/build/documentation/tidy1.xsl b/build/documentation/tidy1.xsl
    index 5058b97..db2e647 100644
    --- a/build/documentation/tidy1.xsl
    +++ b/build/documentation/tidy1.xsl
    @@ -24,7 +24,7 @@
    the $CONFIG variable, declared here:
    -->
    
    -<xsl:variable name="CONFIG" select="document('tidy-config.xml')"/>
    +<xsl:variable name="CONFIG" select="document('../cmake/tidy-config.xml')"/>

**Comment by geoffmcl** [comment]
@bdheeman, thanks for the diff...

Generation and Install of the TIDY_MANFILE in unix...

Agree with the correction of the location of the tidy-config.xml in tidy1.xsl. This gets rid of an xsltproc warning...

And I do agree `local/man/man1` appears wrong. It is my understanding that cmake automatically adds its CMAKE_INSTALL_PREFIX so should this not just be `man/man1`?
 
When I look in cmake_install.cmake I see that if no CMAKE_INSTALL_PREFIX is defined, it gets set to `/usr/local`, but then a little later the DESTINATION of tidy5.1 is hard coded to `/usr/local/man/man1`! Why is it not using the CMAKE_INSTALL_PREFIX?

However, if I add a specific `-DCMAKE_INSTALL_PREFIX=$HOME/projects/install/tidy-html5`, now the DESTINATION of tidy5.1 is as I expect `${CMAKE_INSTALL_PREFIX}/local/man/man1`... But that also seems wrong, in that now the default would be `/usr/local/local/man/man1`

Adding your suggested change, and not specifying an install prefix, and the DESTINATION goes back to the hard coded `/usr/local/man/man1`!

But now if I add my specific install location, it is ignored, and the hard coded `/usr/local/man/man1` is used again.

So it seems if I change to what you suggest, then any specific user install location is ignored, at least for that file. Now maybe that is correct since what would be the use installing a man page in some `remote` location...

Finally, if I change the CMakeLists.txt to what I suggest, then the install uses `${CMAKE_INSTALL_PREFIX}/man/man1` whether I give a specific prefix or not... so this seems the right choice...

And that includes using what some might prefer `-DCMAKE_INSTALL_PREFIX=/usr`, to override the cmake local default... so have pushed these...

But I am a 100% windows person, and have only been using unix for a relative short time, so look forward to further advice on what might be a better choice?

**Comment by geoffmcl** [comment]
@bdheeman, @anEffingChamp, @pedromorgan, @balthisar, @ryandesign as pointed out in Issue #193, the <a target="_blank" href="http://www.pathname.com/fhs/">Filesystem Hierarchy Standard (FHS)</a> doc states `usr/share/man/man1` is the correct place for this install, so have adjusted the CMakeLists.txt to `share/man/man1`... which I hope is the final choice...

This was also discussed in #177, and #181... and `-DCMAKE_INSTALL_PREFIX=/usr`, needs to be used  override the cmake `/usr/local` default....

Of course, until the release, while we continue to use `tidy5` as the name you need to use `$ man tidy5` to display this page...

Accordingly, am closing this, but flee free to reopen, or post another issue if there is still a problem...
