### ISSUE TITLE
Install manpages to share/man

### ISSUE THREAD

**Issue by ryandesign** [htacg/tidy-html5#193]
I am the maintainer of tidy in MacPorts. Tidy 4.9.24 installs its manpages into the man subdirectory of the specified prefix. The [standard on UNIX systems](http://www.pathname.com/fhs/) since over a decade is that manpages should be installed into the share/man subdirectory of the prefix.

**Comment by geoffmcl** [comment]
@ryandesign, ok, on reading the fhs document, I guess -

````
    install(FILES ${CMAKE_BINARY_DIR}/${TIDY_MANFILE} DESTINATION man/man1)
````

should be changed to -

````
    install(FILES ${CMAKE_BINARY_DIR}/${TIDY_MANFILE} DESTINATION share/man/man1)
````

Is that correct?

That is, it would be installed in `${CMAKE_INSTALL_PREFIX}/share/man/man1`?

I also think the default CMAKE_INSTALL_PREFIX on unix systems is `/usr/local`, unless a specific `-DCMAKE_INSTALL_PREFIX=/usr` is issued.

Further, cmake also allows a specific full path to be used, and it will ignore any 'prefix', like -

````
    install(FILES ${CMAKE_BINARY_DIR}/${TIDY_MANFILE} DESTINATION /usr/share/man/man1)
````

So maybe that would be better?

Being basically a Windows person would seek further comments on this change. And note manual generation is only done `if(UNIX)`, and if the `xsltproc` is found...

**Comment by ryandesign** [comment]
Yes, change `man/man1` to `share/man/man1` in CMakeLists.txt. That is what I'm doing in MacPorts.

Don't try to install into /usr when /usr is not the prefix the user requested.

**Comment by geoffmcl** [comment]
@ryandesign  changed it to `share/man/man1`

And agree should respect a user requested install prefix

Does this close this?

**Comment by ryandesign** [comment]
Yes, thanks!

**Comment by conraid** [comment]
why not add the variable MAN_INSTALL_DIR as in most software configured with cmake?
Slackware or BSD, for example, use /usr/man

**Comment by geoffmcl** [comment]
@conraid, sounds like a good idea...

How about something like :-

```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index ce2ee17..5aac7dc 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -23,6 +23,9 @@ set( LIB_TYPE STATIC )  # set default static
 option( BUILD_SHARED_LIB "Set ON to build Shared (DLL) Library"   OFF )
 option( BUILD_TAB2SPACE  "Set ON to build utility app, tab2space" OFF )
 option( BUILD_SAMPLE_CODE "Set ON to build the sample code"       OFF )
+if (NOT MAN_INSTALL_DIR)
+    set(MAN_INSTALL_DIR share/man/man1)
+endif ()
 
 if(CMAKE_COMPILER_IS_GNUCXX)
     set( WARNING_FLAGS -Wall )
@@ -213,7 +216,7 @@ if (UNIX)
             VERBATIM
         )
 
-        install(FILES ${CMAKE_BINARY_DIR}/${TIDY_MANFILE} DESTINATION share/man/man1)
+        install(FILES ${CMAKE_BINARY_DIR}/${TIDY_MANFILE} DESTINATION ${MAN_INSTALL_DIR})
     endif ()
 endif ()
```

This would allow you to add a -DMAN_INSTALL_DIR=some/install/place for other distributions if different to the default.

If you would like to add a pull request, you could be the author of this change ;=))

@ryandesign, any objection to this change?

**Comment by geoffmcl** [comment]
@conraid, @ryandesign since there have been no futher comments on this have pushed this small cmake change, and bumped the version to 4.9.27

I tested it in linux, and using the commands -

```
$ cd build/cmake
$ cmake ../.. -DMAN_INSTALL_DIR=man -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release
```

Then the cmake_install.cmake shows that the tidy5.1 man file would now be installed to `/usr/man', so it seems this would now accomodate Slackware, BSD, and other man install locations...

Note the final cmake command `-DCMAKE_BUILD_TYPE=Release` is **required** if you want to build a release binary without `assert` macros. That is add -DNDEBUG to the compile. See discussion on #30

Please test and advise if any problems... thanks @conraid for this added flexability...

**Comment by conraid** [comment]
Yes, with 
-DMAN_INSTALL_DIR=man/man1
man is installed in 
usr/man/man1/tidy5.1.gz
it's ok

p.s.
I don't know if it's a problem in my configuration or another, maybe I open another ticket, but I have to change "../documentation" with "documentation" in TIDY1XSL variable in CMakeLists.txt, otherwise I get an error
warning: failed to load external entity "../documentation/tidy1.xsl"

**Comment by geoffmcl** [comment]
@conraid, thanks for checking so promptly... interesting that it becomes a .gz file in your system... but glad it worked...

As for the location of the tidy1.xsl I guess it depends on where you actually `run` cmake... The recommended location is **build/cmake**, so from there `../documentation` is correct...

But in general it is NOT a good thing to use relative paths, since this then does depend on where you run cmake.

I have just pushed a few more small CMakeLists.txt changes, including using an absolute path. That means you should be able to run cmake **ANYWHERE** and the man files will still be found.

If there is still a problem, it is probably better to open a separate issue...

**Comment by conraid** [comment]
In Slackware man pages are gzipeed. In script build there is
```bash
if [ -d ${PKG}/usr/man ]; then
    find ${PKG}/usr/man -type f -exec gzip -9 {} \;
fi
'''

for document I used build dir, this is a build script section
```bash
mkdir -p build
cd build
cmake \
[options] \
..
```

Now it's ok.
Thanks

**Comment by ryandesign** [comment]
Thanks.

> I tested it in linux, and using the commands -
> 
> ```
> $ cd build/cmake
> $ cmake ../.. -DMAN_INSTALL_DIR=man -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release
> ```
> 
> Then the cmake_install.cmake shows that the tidy5.1 man file would now be installed to `/usr/man', so it seems this would now accomodate Slackware, BSD, and other man install locations...

Note that `man` will not look for tidy5.1 in /usr/man; it will look for it in /usr/man/man1. What you've done is fine, but will start to be inconvenient for you if you ever install manpages in categories other than man1.

**Comment by dwlamb** [comment]
Could someone advise where things stand with the man pages bug?  I just completed upgrade to Tidy HTML5 and found there were no man pages.  I found this thread on google.  I followed the commands of  geoffmcl above and took note of the comments from ryandesign.

At a bash shell prompt, I did a find 'find / -name \*tidy\*gz'.  That yielded:

/usr/share/man/man1/csstidy.1.gz
/usr/share/man/man1/perltidy.1p.gz

I have tried 'man tidy'  and 'man tidy5' and received as messages that there are no man pages for those topics.

**Comment by geoffmcl** [comment]
@dwlamb if `$ man tidy` fails then I do not think `tidy.1` is installed... there is no `5` any more...

In my Ubuntu 14.01 it is installed in `/usr/share/man/man1/tidy.1`. Note it is **not** a gz file...

I assume you are building from git source? What commands are you using? 

My litle mantra is -

```
$ git pull       # update the source
$ cd build/cmake # get into build folder
$ ./build-me.sh  # build it
```

That script adds the important option `-DCMAKE_INSTALL_PREFIX=/usr`. The cmake default if this is not given is `/usr/local/...`. And it also adds `-DCMAKE_BUILD_TYPE=Release`, unless you add `DEBUG`, to build the library without asserts...

Then in the `bldlog-1.txt` file generated you should see `*** Generating man tidy.1 custom commands...`. Alternatively there will be a `*** NOTE: xsltproc NOT FOUND!...` if xsltproc is not installed...

So, do you have `xsltproc` installed?

And if all is well the final command is `$ [sudo] make install`, and you should see what is installed, and exactly where... about 10 items, including tidy.1...

Then my `$ man tidy` pops up the page with the version matching `version.txt` in the source...

Hope this helps...
