### ISSUE TITLE
drop-empty-elements dropped? (heh)

### ISSUE THREAD

**Issue by InconceivableVizzini** [htacg/tidy-html5#200]
Has drop-empty-elements been replaced with a different flag?

If I use the older experimental state of the tree, https://github.com/htacg/tidy-html5/tree/c63cc39, drop-empty-elements works fine. If I use master, no beans.

**Comment by geoffmcl** [comment]
@InconceivableVizzini, do not completley understand your question. Perhaps you could add some test samples, and show what you expect... what elements? what config?

Reading through the git log since that initial tree, I can read several changes in the dropping 'empty' tag code...

 1. commit/6f9dc2327ed2c61bd375e7815efe855b6bcf33bb Fix for #103 - don't drop empty dd tags.
 2. commit/bf1c2f67a91c8ecc349a41a01c7d13debcafda67 Added drop-empty-elements options. Fixes #19.
 3. commit/f4edfc693b9123e07aab67f37ec738217c177a6e Empty `<progress>` tags no longer stripped #10
 4. commit/f6a3bbecdbf3bc2832e6bffc8f86b8de6ed3f2d2 fix for ISSUE #7: empty canvas no longer stripped
 5. And maybe others...

These mainly seem concerned with **NOT** dropping certain empty elements...

Maybe your test samples will make it clear what you expect... thanks...

**Comment by InconceivableVizzini** [comment]
When using pytidylib and the master branch of tidy-html5 I receive "unknown option: drop-empty-elements" if I attempt to use the option at all. However, building tidy-html5 using the commit I linked to works fine.

**Comment by geoffmcl** [comment]
@InconceivableVizzini, just some quick experiments, after installing pytidylib in my Ubuntu 14.04...

Ran the following little script - excuse any typos - writing this in a different machine so can not use copy and paste...

````
from tidylib import tidy_document
tidyoptions={
'numeric-entities': True,
'tidy-mark': True
}
document, errors = tidy_document('''<p>f&otilde;o <img src="bar'>''',
  options=tidyoptions)
print document
print errors
````

This showed me I presently had **OLD** libtidy 2009 installed... so made a clean clone of master, and ran -

 1. cd build/cmake
 2. cmake ../.. -DBUILD_SHARED_LIB:BOOL=TRUE -DCMAKE_INSTALL_PREFIX=/usr
 3. make
 4. sudo make install
 5. cd /usr/lib
 6. sudo rm libtidy.so
 7. sudo rm libtidy.so.0
 8. sudo ln -s libtidy5.so.4.9.25 libtidy.so.4
 9. sudo ln -s libtidy.so.4 libtidy.so
 10. ls -ls libtidy* # just to check it all looked good

That is did a fresh build and install, but this presently only builds and installs libtidy5.so.4.9.25, so deleted the current install links, and created new libtidy.so link to my 4.9.25 library...

Now running the above script showed a tidy-mark of `Linux version 4.9.25`. So added a little more to the script -

````
from tidylib import tidy_document
tidyoptions={
'numeric-entities': True,
'tidy-mark': True,
'drop-empty-element': False
}
document, errors = tidy_document('''<p>f&otilde;o <img src="bar'></p><p>''',
  options=tidyoptions)
print document
print errors
````

And as expected the output still included the 2nd empty para `<p></p>`. And it was dropped when I changed the drop-empty-element to True, and got warning trimming empty `<p>`...

So this **ALL** works for me ;=)) Not sure what your problem is exactly but hope this helps track it down...

**Comment by geoffmcl** [comment]
@InconceivableVizzini since no further recent comment assume you have got this solved, and am closing this for now...

Feel free to re-open, or open other issues... thanks...
