### ISSUE TITLE
error/warn is special apostrophe (’) used in config file

### ISSUE THREAD

**Issue by 0-F** [htacg/tidy-html5#201]
This apostrophe `’` (not ') can't be used in the config file comments.
(Tidy version 4.9.23 for Windows)

doc.html =

    <!DOCTYPE html>
    <html>
    <head><title></title></head>
    <body>&
    </body>
    </html>

a.txt = `// hello`

`tidy5.exe -config a.txt doc.html` return

    line 4 column 7 - Warning: unescaped & which should be written as &amp;
    Info: Document content looks like HTML5
    1 warning, 0 errors were found!

It's ok, `&` is remplaced by `&amp;`.

---

Now, if I put this apostrophe `’` in config file...
a.txt = `// ’`
Tidy return

    Warning: replacing invalid character code 146
    line 4 column 7 - Warning: unescaped & which should be written as &amp;
    Info: Document content looks like HTML5
    1 warning, 0 errors were found!
    
    Character codes 128 to 159 (U+0080 to U+009F) are not allowed in HTML;
    even if they were, they would likely be unprintable control characters.
    Tidy assumed you wanted to refer to a character with the same byte value in the 
    specified encoding and replaced that reference with the Unicode equivalent.

Also, if I run `tidy5.exe -config a.txt` without an html file, I have again `Warning: replacing invalid character code 146`

**Comment by geoffmcl** [comment]
@0-F characeter sets is always a difficult question to answer, but let me try...

First, the config file **MUST** be ASCII only encoded! It has always been this way in Tidy!

In your email, the `special apostrophe`, sometimes called the `right curly quote mark`, or `&rsquo;`, `’`, is encoded as 0x92. I am not sure where that value came from! Maybe Apple is using that instead of 0x60, but NOT sure... Maybe you could help me undertand this...

Second the config file is read by the same input routines as the html is read, so when the 'reader'  encounters the 0x92, or decimal 146, it spits out the warning - `Warning: replacing invalid character code 146`.

And then later explains -

````
Character codes 128 to 159 (U+0080 to U+009F) are not allowed in HTML;
even if they were, they would likely be unprintable control characters.
Tidy assumed you wanted to refer to a character with the same byte value in the
specified encoding and replaced that reference with the Unicode equivalent.
````

The ONLY problem with this explanation is that it says `not allowed in HTML`. Of course it should/could also say not allowed in the config file in this case... which, as stated, should be ASCII only...

Now in my Windows 7 machine, when I tap the `special apostrophe` key I get 0x60, decimal 96, in the file, which is the correct ASCII value for this particular character. And I can also enter this by typing the key sequence `Alt+096`... Consequently I get no tidy warning... 

And this is the same in my linux (Ubuntu) machine... 

Also using copy and paste can change the character values..

As you point out the other warning is concerning the replacing of the `&` with `&amp;`, which is a normal warning and action of Tidy...

Do a hex dump of your a.txt - `$ xxd -g 1 a.txt` - to ensure I am right about the value in the file. And if other than 0x60, changing it to 0x60 should remove this warning.

So at this time I can not see any problem, issue with Tidy to fix ;=)).

**Comment by 0-F** [comment]
Thanks for reply.
This apostrophe came from http://tidy.sourceforge.net/docs/tidy_man.html (`’` is replaced by `&rsquo;` in html code).
I copy-pasted tidy-mark's comments in my config file. In these comments there is a `&rsquo;` 0x92 apostrophe.

    // [...] to indicate that the document has been tidied. Tidy won’t add a meta element if [...]
    tidy-mark: yes

By replacing it this solve the problem but the `not allowed in HTML` is a little confusing. ^^
