### ISSUE TITLE
Support for custom tags

### ISSUE THREAD

**Issue by Metalgrid** [htacg/tidy-html5#204]
[AngularJS](https://angularjs.org/) uses alot of custom tags and also allows you to create your own. Is it possible to support custom tags, e.g. load an additional list of tags from a file? For example, I have a `<submit-button>` tag that translates to `<input type="button">`, but this tag is not supported and tidy5 bails.

**Comment by geoffmcl** [comment]
@Metalgrid note I have added the `special apostrophe` to be able to `see` html...

Tidy already supports adding `custom` tags through the `config` file - see `new-blocklevel-tags`, `new-empty-tags`, `new-inline-tags` and `new-pre-tags`... You should be able to use these to add say `<submit-button>`, and others...

AngularJS is not yet supported by the W3C, so we would be unlikely to add this at this time.

But I would be willing to work with you to ensure the addition of such `new` tag through the config file works correctly... and maybe even enhanced such an `external` approach...

When you get a chance please experiment and test... add some sample config and html for testing... thanks...

**Comment by geoffmcl** [comment]
@Metalgrid, have just tested the following html snippet -

```
<form>
First name:<br>
<input type="text" name="firstname">
<br>
<submit-button>
</form>
```

Using a config file -

```
tidy-mark: no
show-info: no 
new-empty-tags: submit-button
show-body-only: yes
```

Then using the command `tidy5 -config input5\cfg_204-2.txt input5\in_204-2.html`, and got the following output -

```
line 5 column 1 - Warning: <submit-button> is not approved by W3C
1 warning, 0 errors were found!

Info: Document content looks like HTML5
<form>First name:<br>
<input type="text" name="firstname"><br>
<submit-button></form>
```

This indicates tidy5 supports custom tags added through a config file... exiting only with a mild warning... which could be suppressed with `--show-warnings no`, or written to a warning file with `-f warning.txt`...

So am closing this for now... free free to re-open, add more samples, etc... but as far as I see tidy5 **supports** custom tags from an input config file.

**Comment by mtangoo** [comment]
adding this to docs will be good than digging up in issues

**Comment by geoffmcl** [comment]
@mtangoo you mean like this - http://www.htacg.org/tidy-html5/quickref.html#new-empty-tags ?

And viewing that reminds me we must also update those docs to version 5.0.0, although not much changed since that 4.9.28/35...

One **very** important thing, especially for those using `libtidy` in their own projects, and that is the re-naming of two header files - See Major API change - #224, #223, #221

 1. renamed:    `"buffio.h" -> "tidybuffio.h"`
 2. renamed:    `"platform.h" -> "tidyplatform.h"`

But we could **always** do with more, better documentation. Feel like writing some? I will certainly help getting it `published`...

And some more could be added to our **very bare** wiki - https://github.com/htacg/tidy-html5/wiki

A reminder that tidy also has it own home page - http://www.html-tidy.org/ - and welcome additions to these pages... 

The `source` of these pages is in the `gh-pages` branch of the main repo - https://github.com/htacg/tidy-html5 - Once you have cloned this repo, do -

 - `cd tidy-html5`
 - `git checkout gh-pages`
 - `git pull` - optional - only needed if not first checkout

The html site is generated via `yaml`... see `_config.yml`... and the subdirectory `index/_posts` contains the current set of index pages...

And more programmer documentation on - http://www.html-tidy.org/developer/ - see subdirectory `documentation/_posts` for the current set of pages...

As stated, contributions, additions, corrections always **very** welcome...

**Comment by mtangoo** [comment]
You got it correct! @geoffmcl 
Thank you for that!
