### ISSUE TITLE
Tidy doesn't cleanup attribute names with colon. 

### ISSUE THREAD

**Issue by girishsubramanyam** [htacg/tidy-html5#208]
For example: Here addthis:url is a invalid attribute name and Xalan parser fails. Can we an option to clean up the attribute names which has a colon in it. Like ref:json / addthis:url
<div id="addthis-xsdji" class="addthis_toolbox addthis_default_style addthis_20x20_style" addthis:url="http://www.dailymotion.com/video/xsdji_rick-astley-never-gonna-give-you-">

**Comment by girishsubramanyam** [comment]
<div
                id="addthis-xsdji"
                class="addthis_toolbox addthis_default_style addthis_20x20_style"
                addthis:url="http://www.dailymotion.com/video/xsdji_rick-astley-never-gonna-give-you-up_music"
                data-title="Rick Astley - Never Gonna Give You Up"
                data-content_version="us"
                data-video_xid="xsdji"
                data-user_xid="">

**Comment by geoffmcl** [comment]
@girishsubramanyam note to add html to a post it must be surrounded by a single special backquote, 0x60, for inline or 3 or 4 around a block. It is best to use the Preview before adding a comments. And clicking the `Markdown supported` leads to a helpful page...

Here is your sample expanded to a full html block, correctly quoted -

```
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Tidy doesn't cleanup attribute names with colon. #208</title>
</head>
<body>
<div id="addthis-xsdji"
class="addthis_toolbox addthis_default_style addthis_20x20_style"
addthis:url="http://www.dailymotion.com/video/xsdji_rick-astley-never-gonna-give-you-up_music"
data-title="Rick Astley - Never Gonna Give You Up"
data-content_version="us"
data-video_xid="xsdji"
data-user_xid="">
</div>
</body>
</html>
```

So tidy correctly identifies the problem with `line 8 column 1 - Warning: <div> proprietary attribute "addthis:url"`, but if I understand you correctly you want an `OPTION` to ask Tidy to **FIX THIS!**.

But what should tidy **fix** it to? Should it remove the bad attribute? Should it convert the colon to an underscore, or to what? That is **how** should it fix it?

Tidy can not read the author's mind, so has no way of deciding what the author intended if it was just a typing mistake. ;=))

Another option could be considered, but need answers, comments on exactly **what action** should be taken to suit **all** such cases. And is there a clear use case for this?

**Comment by girishsubramanyam** [comment]
Hi Geoff,
Definitely this isn't a typo :)
This has been a long time problem, i can name a few website which use attribute name with colon. After tidying these html files when passed to xalan to extract information it fails with an error.  Can we provide user an option to replace a character in attribute name, in our case colon with underscore.

Examples:
http://tv.ibtimes.com/entrepreneur-maneesh-goyal-how-he-made-it-big-and-continues-succeed-2679
fb:like:layout="button_count" class="addthis_button_facebook_like at300b
g:plusone:size="medium" class="addthis_button_google_plusone at300b

http://www.dailymotion.com/video/xolgjo_21221222396_lifestyle
addthis:url

http://www.buzzfeed.com/summeranne/the-25-most-epic-cat-beards-of-all-time#.pnBkp6NXZ
script src="http://s3-ak.buzzfed.com/static/js/General_concat_header.js?v=201504281400" type="text/javascript" ref:jsconf="true"

**Comment by geoffmcl** [comment]
@girishsubramanyam I am still not exactly sure of your use case, but if you just want the tidy output to pass through another parser, what about `--drop-proprietary-attributes yes`?

This would remove all `proprietary attribute` from the tidy output.

Alternatively, you could pass the tidy output, or even the input before tidy, through say a perl script that could easily change all attributes with a colon to say an underscore. This could be very fast...

But concerning an additional option, could it simply be change all colons in attribute names to an undercore, say `--munge-attributes yes`, default to, **or** would you need this to be very generalised say `--change-attribute-char :2_`, and say `--change-attribute-char @2-`, etc? 

That is giving 3 characters - first is the character to change, a separator, and the 3rd the substitution - This could probably also be just passing in two char - first is the character to change and the 2nd the substitution...

Of course the former is much simpler since it is only a switch and a search for a `:`, and change it to an `_`... 

The latter would be more complicated, since each char in the attribute name has to be looked up in a list, and the user substitute character exposed/returned...

But I am hoping the existing `--drop-proprietary-attributes yes`, or even the pre or post parsing with another script will be suitable for your use...

**Comment by girishsubramanyam** [comment]
Geoff,

--drop-proprietary-attributes yes drops most of the custom attributes and we wont be able to extract required  information  from html pages. 

Pre/Post processing cannot be achieved. As the docs are passed through a series of pipelines and the number of docs parsed are in billions.

--change-attribute-char :2_ is a better solution.

**Comment by geoffmcl** [comment]
@girishsubramanyam, hmmm, series of pipelines... billions of documents...

One wonders then what is tidy's role in this massive data/information mining... it does not sound like the tidied output is ever seen anywhere except passed to the next in the toolchain... and whether some other pre html parser, perhaps faster than tidy, would not be better...

So at this time I can not really see a case for an additional option for tidy... to abitrarily change one proprietory attribute name to another proprietory name...

But in reviewing the code, it would not be too difficult to catch a colon and substitute an underscore, or other transformations, as the attribute name is added to the lexer... see `lexer.c(3246): ParseAttribute(TidyDocImpl* doc, ...)`.

This could be as simple as -

```
lexer.c(3359):
        if ( !cfgBool(doc, TidyXmlTags) && TY_(IsUpper)(c) )
            c = TY_(ToLower)(c);
        if (c == ':') c = '_'; /* plus other subs... */
        TY_(AddCharToLexer)( lexer, c );
```

And you would have your desired library.

Accordingly, am closing this, but feel free to re-open with new information, or with a patch/PR for consideration...
