### ISSUE TITLE
microdata / microformat / RDFa support

### ISSUE THREAD

**Issue by anEffingChamp** [htacg/tidy-html5#209]
Is there any way to add support for structured metadata to the validator?

http://schema.org/docs/gs.html
http://www.w3.org/TR/xhtml-rdfa-primer/
http://microformats.org/

**Comment by geoffmcl** [comment]
@anEffingChamp, well there is certainly presently no **easy** way to support additional `attributes`!

First **all** attributes known to tidy are enumerated in **tidyenum.h**. So that is where each **new** attribute must be first added. Then the 'text' name, and a 'parser' in `static const Attribute attribute_defs []`.

Then for each element, tag tidy supports, an attribute dictionary is constructed in attrdict.c.

Take the first as an example `const AttrVersion TY_(W3CAttrsFor_A)[] =`, followed by each attribute allowed for that element, in a structure `typedef struct _AttrVersion { TidyAttrId attribute; uint versions; } AttrVersion;`.

Then as each tag is defined, in tags.c, it inherits a pointer to the list of attributes supported by that element. Again the stucture entry for the anchor tag -

```
  /* W3C defined elements */
  { TidyTag_A, "a", VERS_ELEM_A, &TY_(W3CAttrsFor_A)[0], (CM_INLINE|CM_BLOCK|CM_MIXED),
  TY_(ParseBlock), NULL }, /* Issue #167 & #169 - default HTML5 */
```

Now, some work has been done to make that big table `dynamic`. That is it is constructed with html5++ support, but if the document has an html4-- doctype, then some elements in that table can be dynamically changed.

So `in theory` that could be extended to add attribute for each particular element. It could say read the information from perhaps an xml file which enumerated additional attributes for some elements.

So to say extend again the anchor tag to allow the rdfa `property` attribute, the existing `TY_(W3CAttrsFor_A)` could be copied into allocated memory, that additional attribute added, and the address of that new attribute structure for `a` put in the table.

Not easy, and there are some other considerations, but not impossible. And opens the way to say externalise **ALL** attributes for tags. Then the supported list for each tag could be loaded from an exernal file on library start-up. And such extensions then becomes just an adjustment of that exernal file.

However, this would substantially slow down the library start up... but perhaps not too much...

I left the explicit comment in the above example `/* W3C defined elements */`, and note in the `xhtml-rdfa-primer` link the words `Publication as a Working Group Note does not imply endorsement by the W3C Membership`. So at this stage, support for `rdfa` in tidy is unlikely.

Of course this does not stop anyone from coding such changes for their own `extended` tidy library... and presenting that as a patch or PR for consideration...

I will leave this virtual `feature request` open for a while in case others want to add comments... and thanks for bringing it up.

**Comment by Aeyoun** [comment]
Just posting an example with OpenGraph Protocol data so others searching for this more easily can find it in the future. It’s a very common example because Facebook.

    <!DOCTYPE html>
    <html prefix="og: http://ogp.me/ns# article: http://ogp.me/ns/article# "
        vocab="http://ogp.me/ns" lang="en">
        <head>
            <meta content="Some kind of title" property="og:title" />
    …
    line 2 column 1 - Warning: <html> proprietary attribute "prefix"
    line 3 column 1 - Warning: <html> proprietary attribute "vocab"
    line 5 column 1 - Warning: <meta> proprietary attribute "property"

**Comment by geoffmcl** [comment]
@Aeyoun, thanks for posting another example...

I just constructed a full sample using your content, and much more, and note it fully passes the W3C validator, so I guess this **MUST** be looked at sooner rather than later ;=()

```
input5/in_209-2.html
<!DOCTYPE html>
<html prefix="og: http://ogp.me/ns# article: http://ogp.me/ns/article# "
    vocab="http://ogp.me/ns" lang="en">
    <head>
        <meta content="Some kind of title" property="og:title" />
        <meta charset="utf-8">
        <title>microdata / microformat / RDFa support #209</title>
    </head>
<body vocab="http://purl.org/dc/terms/">
   <div resource="/alice/posts/trouble_with_bob">
      <h2 property="title">The trouble with Bob</h2>
      <p>Date: <span property="created">2011-09-10</span></p>
      <h3 property="creator">Alice</h3>
   </div>
   <div resource="/alice/posts/jos_barbecue">
      <h2 property="title">Jo's Barbecue</h2>
      <p>Date: <span property="created">2011-09-14</span></p>
      <h3 property="creator">Eve</h3>
   </div>
</body>
</html>
```

The current tidy5 issues 12 warnings for this...

As always, appreciate a patch or PR implementing these...

And accordingly changed the milestone to 5.1

**Comment by skynet** [comment]
:+1:

**Comment by halindrome** [comment]
First a general comment - @geoffmcl was looking at the wrong resource for the definition of RDFa.  RDFa is an approved W3C extension to HTML5.  So yeah, it would be great if this tool supports it.  You can see the core definition of RDFa at http://www.w3.org/TR/rdfa-core.  The (X)HTML version of it is at http://www.w3.org/TR/html-rdfa.   I will note that microdata is NOT an approved W3C Recommendation, but it is supported by the validator so...

As to how to support RDFa in tidy - yeah, this could be tricky.  RDFa attributes are technically legal on ALL elements.  So given the way tidy defines what attributes are legal on what elements, the easiest thing would be to add vocab, typeof, property, resource, prefix, content, about, rel, rev, datatype, and inlist to every element.  Note that technically these are even legal in HTML4 context, but that is sort of debatable.  

I will see if I can put together a pull request that supports this in its simplest form.

**Comment by geoffmcl** [comment]
@halindrome thanks for the additional links... will get around to some careful reading... and I too note they seem accepted by the validator... is the validator ahead of the docs? Or indicating the way? Which should tidy follow?

> RDFa attributes are technically legal on ALL elements.

This gives me the idea that this could be just a table of say `RDFa` attributes, rather than the heavy cut and paste operation to add them to the attributes allowed for each element...

Maybe not even individually enumerated in TidyAttrId;, except perhaps as TidyAttr_RDFa... but then you have to deal with API items like tidyAttrGetId(TidyAttr)...

Then if the user adds an option like `--allow-rdfa-attributes yes` or whatever, coud default to on, every attribute collected is first checked in this `RDFa` attribute list...

This compare service could then also have exceptions depending on the specific node they are on, or the indicated doctype, or ..., if need be...

Anyway, just an idea off the top of my head on hearing `ALL` elements...

> I will see if I can put together a pull request that supports this in its simplest form.

That would be very much appreciated... thanks...

**Comment by geoffmcl** [comment]
@halindrome just wondering how this is going? 

Can I do anything to help?

Can anyone else help with this?

I am seeing more and more sites using these RDFa attributes, so it becomes important Tidy begins to have some support...

We should be able to start small, avoid the `PROPRIETARY_ATTRIBUTE` warning... It is only used once - [LN1343](https://github.com/htacg/tidy-html5/blob/master/src/attrs.c#L1343) ... after a `AttributeIsProprietary(node, attval)` returns `yes`.

It could have an additional condition to return `no`, like maybe -

```
   if (isRDFa_Enabled() && matchesRDFa(attval) && inHTML5Mode())
    return no;
```

The first checks the user option is on, the second that is matches a RDFa global list, and the 3rd that we are still in HTM5 mode...    

### *** HELP NEEDED ***

**Comment by halindrome** [comment]
I actually finished the implementation.  I didn't make it an option, since
it is a part of the HTML5 recommendation and support for it is required in
user agents.

On Fri, Nov 6, 2015 at 9:16 AM, Geoff McLane <notifications@github.com>
wrote:

> @halindrome <https://github.com/halindrome> just wondering how this is
> going?
>
> Can I do anything to help?
>
> Can anyone else help with this?
>
> I am seeing more and more sites using these RDFa attributes, so it becomes
> important Tidy begins to have some support...
>
> We should be able to start small, avoid the PROPRIETARY_ATTRIBUTE
> warning... It is only used once - LN1343
> <https://github.com/htacg/tidy-html5/blob/master/src/attrs.c#L1343> ...
> after a AttributeIsProprietary(node, attval) returns yes.
>
> It could have an additional condition to return no, like maybe -
>
>    if (isRDFa_Enabled() && matchesRDFa(attval) && inHTML5Mode())
>     return no;
>
> The first checks the user option is on, the second that is matches a RDFa
> global list, and the 3rd that we are still in HTM5 mode...
> *** HELP NEEDED ***
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/htacg/tidy-html5/issues/209#issuecomment-154434937>.
>



-- 
Shane McCarron
halindrome@gmail.com

**Comment by geoffmcl** [comment]
@halindrome that is great news... are you going to share this code with granddaddy tidy?

I note your current fork is quite a number of commits behind htacg:master... You probably already know this, but this is my little **update a fork** mantra -

```
$ git remote add upstream git@github.com:htacg/tidy-html5.git # once only
$ git checkout master
$ git status
$ git stash    # if not clean
$ git fetch upstream
$ git rebase upstream/master
$ git stash pop # if reuired, and fix conflicts
$ git push      # update the fork
```

Then you could create a PR for us to look at...

Maybe you are right about **not** needing an option, which it would seem we would want to default to `on` anyway...

If the above fork/PR is too much trouble, then you could just post, or send me a patch from `$ git diff -u > ../RDFa.patch`...

Maybe this has already been solved ;=))

**Comment by halindrome** [comment]
I had intended to create a pull request.  I got sucked into W3C meetings in
Tokyo last week, and this week I have been trying to catch up!

On Fri, Nov 6, 2015 at 11:28 AM, Geoff McLane <notifications@github.com>
wrote:

> @halindrome <https://github.com/halindrome> that is great news... are you
> going to share this code with granddaddy tidy?
>
> I note your current fork is quite a number of commits behind
> htacg:master... You probably already know this, but this is my little *update
> a fork* mantra -
>
> $ git remote add upstream git@github.com:htacg/tidy-html5.git # once only
> $ git checkout master
> $ git status
> $ git stash    # if not clean
> $ git fetch upstream
> $ git rebase upstream/master
> $ git stash pop # if reuired, and fix conflicts
> $ git push      # update the fork
>
> Then you could create a PR for us to look at...
>
> Maybe you are right about *not* needing an option, which it would seem we
> would want to default to on anyway...
>
> If the above fork/PR is too much trouble, then you could just post, or
> send me a patch from $ git diff -u > ../RDFa.patch...
>
> Maybe this has already been solved ;=))
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/htacg/tidy-html5/issues/209#issuecomment-154479216>.
>



-- 
Shane McCarron
halindrome@gmail.com

**Comment by geoffmcl** [comment]
@halindrome we now seem to have our first RDFa issue #333... hope you can help in this...

Am closing this as the first initial cut done... feel free to re-open or add a new issue... thanks...
