### ISSUE TITLE
Missing spaces following <a> tags 

### ISSUE THREAD

**Issue by DanSmall** [htacg/tidy-html5#212]
I may be missing something somewhere but I was not expecting this Python code:

    from tidylib import tidy_document
    tidyoptions={
    'tidy-mark': True,
    'drop-empty-elements': False
    }
    document, errors = tidy_document('''<!DOCTYPE html><head><title>Test case</title></head><body><a href="/index.html">Text before a space</a><a href="/index.html"> text after a space</a></body></html>''',
      options=tidyoptions)
    print document
    print errors

to give this result:

    <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
    <html xmlns="http://www.w3.org/1999/xhtml">
      <head>
        <meta name="generator" content="HTML Tidy for HTML5 for Linux version 4.9.26" />
        <title>
      Test case
        </title>
      </head>
      <body>
        <a href="/index.html">Text before a space</a><a href="/index.html">text after a space</a>
      </body>
    </html>

I was expecting the space within the second <a> tag, at the beginning, to be retained.
The original html renders as "Text before a space text after a space". The tidied html renders as "Text before a spacetext after a space".

**Comment by geoffmcl** [comment]
@DanSmall, no you are not missing anything ;=))

This is like a regression due to the fact that in tidy5 mode the anchor element is treated as a block element, thus is parsed by ParseBlock, while earlier CVS tidy treats it as an inline element, and is parsed by ParseInline.

Thus if you added a doctype of say 4.1, or earlier, tidy5 would adjust the table back to html4-- mode, and this leading space in the anchor text would be coalesed into text node before the anchor.

When ParseInline is called the mode is MixedContent, so the space is added to, and left in, the lexer, so can be worked on later, while ParseBlock is called with mode IgnoreWhitespace, so the leading space is dropped, and just lost forever...

As you point out a simple case of `<a href="#1">A</a><a href="#2"> B</a>` will be **fixed** by cvs tidy to `<a href="#1">A</a> <a href="#2">B</a>`, rendered as `A B`, while tidy5 will presently output `<a href="#1">A</a><a href="#2">B</a>`, rendered as `AB`! A case of the missing space!!!

Am looking for a fix, unless you, or others find it first and add a pull request... thanks for reporting...

**Comment by geoffmcl** [comment]
@DanSmall, turned out to be a simple patch but am always suspicious of simple fixes ;=))

As suspected, this was due to the fact that in html5 mode the anchor tag is now parsed in ParseBlock, and in the interests of speed, normally leading text spaces of block tags were removed unconditionally by setting IgnoreWhitespace mode. 

Now, since an anchor tag is marked as both CM_BLOCK and CM_INLINE, the MixedContent mode is retained if there is a likehood, that this leading space may need to be moved out to before the block tag, restoring the previous behaviour.

Have run a full set of diagnostic tests in this 4.9.28 version of tidy, and everything seems ok.

Hope you get a chance to test and close...

**Comment by DanSmall** [comment]
Thanks for fixing the bug so quickly and for the great description of the problem. I can confirm that my tests show that now it is fixed, as you said it would be, with the output:

    <a href="#1">A</a> <a href="#2">B</a>

**Comment by DanSmall** [comment]
@geoffmcl You were right to be "suspicious of simple fixes".

I'm re-opening the issue as I have found another similar case where the space is lost. If the markup used previously is enclosed in a div tag the space is lost

    <div><a href="#1">A</a><a href="#2"> B</a></div>

It gives:

    <div>
      <a href="#1">A</a><a href="#2">B</a>
    </div>

The html renders differently before and after running tidy_document in the browsers that I have tested it in. Using HTML Tidy for HTML5 for Linux version 4.9.30. Unfortunately my C skill-set is non-existent so I am unable to contribute to a fix.

**Comment by geoffmcl** [comment]
@DanSmall thanks for re-opening this... at this stage can only confirm your results... will find time to look into it, unless someone else beats me to it ;=))

**Comment by geoffmcl** [comment]
@DanSmall have pushed a further fix which should now preserve the space to maintain the correct broswer view. Did this by changing the `mode` to `MixedContent` if it is likely that a leading space may be needed to create a space text node to insert before this element.

And found at a deeper layer that for no good reason it seems `ParseTag` is called with a hard coded `IgnoreWhitespace` while code above it has potentially set the `mode` variable to `MixedContent` in certain cases, but it is not used??? But want to test and think about this change some more...

Have bumped the version to 4.9.32 and hope you get a chance to pull an update, re-compile and test, and maybe again `close` this issue, hopefully forever this time ;=)) but thanks for testing...

**Comment by DanSmall** [comment]
@geoffmcl Many thanks for fixing this.
I have tested with a number of test cases and can confirm that it behaves exactly as you said it would, even when the markup is enclosed within div tags.

**Comment by EvansMike** [comment]
Hi Geoff

I've just run into this bug and it seems you've fixed it for html input however, it seems to still exist for xml input.

**Comment by geoffmcl** [comment]
@EvansMike thanks for the report...

But as usual, to speed up testing, fixing, can you provide a **small** sample input, the configuration used, the tidy version used, the output, and the `expected` output... thanks.

Remember to bracket code in 3 back-ticks to render it literally...

**Comment by EvansMike** [comment]
In a test file, text is:
```
<h2>The Things</h2>
<p>The required things are readily available from online sellers. Refer to <a href="https://some.random.com">free things</a> at random site, then:</p>
```
```
tidy  test
line 1 column 1 - Warning: missing <!DOCTYPE> declaration
line 1 column 1 - Warning: inserting implicit <body>
line 1 column 1 - Warning: inserting missing 'title' element
Info: Document content looks like HTML5
3 warnings, 0 errors were found!

<!DOCTYPE html>
<html>
<head>
<meta name="generator" content=
"HTML Tidy for HTML5 for Linux/x86 version 5.1.21">
<title></title>
</head>
<body>
<h2>The Things</h2>
<p>The required things are readily available from online sellers.
Refer to <a href="https://some.random.com">free things</a> at
random site, then:</p>
</body>
</html>
```
Spaces are preserved but I don't want the header footer parts, so using -xml 
```
tidy -xml  test
No warnings or errors were found.

<h2>The Things</h2>
<p>The required things are readily available from online sellers.
Refer to 
<a href="https://some.random.com">free things</a>at random site,
then:</p>
```
Note the missing space after the </a> tag. Expected output is to preserve the space.
Using HTML Tidy for Linux/x86 version 5.1.21 compiled form GitHub on Fedora18.

**Comment by geoffmcl** [comment]
@EvansMike thanks for the sample, and I can see a missing space, and will try to look at this when using -xml...

Alternatively, if you do not want the header footer parts then you can also use `--show-body-only yes`, which does preserve the space -

```
$ tidy5 --show-body-only yes --show-info no input5\in_212-6.html
No warnings or errors were found.

<h2>The Things</h2>
<p>The required things are readily available from online sellers.
Refer to <a href="https://some.random.com">free things</a> at
random site, then:</p>
```

Preserving the space when using `-xml`, which tells tidy to treat the input as well formed xml, may also be possible... but maybe not! I do not think `well formed` xml can have a space here! Will see when and where this space is lost...

**Comment by geoffmcl** [comment]
Or even trimmer adding `-q` (quiet) -

```
$ tidy --show-body-only yes -q input5\in_212-6.html
<h2>The Things</h2>
<p>The required things are readily available from online sellers.
Refer to <a href="https://some.random.com">free things</a> at
random site, then:</p>
```

**Comment by EvansMike** [comment]
I missed "--show-body-only yes" in the man page, that works just fine.  
I'm actually doing all this Python, to build a website from asciidocs, using pytidylib so I'm not seeing errors anyway.  Yes I know I should pipe them somewhere for checking but...
Many thanks.

**Comment by ilmari-lauhakangas** [comment]
Should the remaining XML issue be filed as a separate report? I hit it while [indenting some LibreOffice help files](https://gerrit.libreoffice.org/#/c/71556/).

**Comment by geoffmcl** [comment]
@ilmari-lauhakangas yes, maybe open a **new** XML issue, if you think there is one...

This original issue seemed more about HTML initially... and not losing a space in certain cases... which affects browser rendering... like `<div><a href="#1">A</a><a href="#2"> B</a></div>`... must be rendered as `A B`, not `AB`, which seems **solved**... hence **closed**...

Then later it switched to `XML`... where still the space can be lost... and I never did get around to discovering why... maybe because I am unsure the space needs to be preserved in `XML`... need references, discussion, or something...

So yes, if you want to continue this `XML` issue more, then please open a **new** issue, with sample, samples, test config, and the reason why this is wrong... thanks...

**Comment by ilmari-lauhakangas** [comment]
Created issue #818
