### ISSUE TITLE
Popularize Tidy

### ISSUE THREAD

**Issue by skynet** [htacg/tidy-html5#222]
Would be helpful to have a couple of articles describing the advantage of passing HTML through Tidy. For example, the HTML code will be cleaner, easier to read and HTML5-Valid. Benchmarking is also important, in order to find out the extra server-load and latency introduced by parsing and re-writing HTML through tidy-html5. I believe that for a normal Web application / Web page rendering the overhead is no more than 1-2%. Not to mention that caching is always recommended when building HTML dynamically and in that case the overhead will be completely eliminated.

Here's a very old article: http://www.w3.org/People/Raggett/tidy/
Looking at most Websites the code looks simply ... messy. That's one of the dark sides of Web development - most companies can't care less about clean and lean code, and that will eventually reflect in the overall quality of their Web presence.

**Comment by geoffmcl** [comment]
@skynet could not agree more...

My (perceived) advantages of using Tidy on each new or edited web pages - now a few thousand on my `sprawling` web site ;=)) are -

 1. So I can say I keep my web pages Tidy! And add the tidy logo. ;=))
 2. Nicely space indented for the MSVC IDE integrated web content 'source' editor.
 3. It acts as a quick validator of type, so can add W3C validation icon with little fear.

While the MSVC IDE web content editor also uses, suggests indenting, it is not very complete, or flexible, so after manually writting to a page, my last step is to still run tidy... I have it all setup in a macro...

However, I see a **LOT** of web contents with either -

 * very little regards for code layout - extreem is single line, sort of compressed html, or 
 * has its own which is probably then acceptable to the owner and the chosen content editor. 
 
It seems sites `written` like this would have little or no use for Tidy!

I am also not too sure about using tidy to reduce page load overhead. In my case at least, it usually adds spaces (weight) to the file, since I like the visual source indenting and vertical spacing...

I guess a person either falls in love with what tidy does, and thus will use it all the time... others not so much... so not sure what characteristics need to be put in an article to attract **new** users... just so they can decide if they love/hate tidy ;=))

**Comment by skynet** [comment]
If I look at the source for a Web page and I see the HTML code as being clean and well organized, to me that's a clear indication that something good is going on there. On the contrary, if code is dirty and ugly I dismiss whatever services they offer since I don't see that particular Website built under a sustainable development environment. Google might take into account (and who can say that they don't) source code cleanliness as yet another plus signal for their ranking algorithm.

**Comment by vielmetti** [comment]
I wrote up how I use `tidy` here:

http://vielmetti.github.io/post/2015/2015-09-10-xml2json/

as a part of a web parsing pipeline.

**Comment by skynet** [comment]
:+1: Think we should probably list your article somewhere. Any ideas?

**Comment by vielmetti** [comment]
The obvious place @skynet  would be a link somewhere from http://www.html-tidy.org/ but it's not clear where on those pages.

**Comment by geoffmcl** [comment]
@skynet, @vielmetti I agree the obvious place is http://www.html-tidy.org/...

As recently mentioned the `source` of these pages is in the `tidy-html5` repo, in the `gh-pages` branch - `$ git checkout gh-page`... Simple to modify, understand, add to... and do **not** seek alternative web page technologies...

The present 7 `headings`, or *.md pages are -

```
"TIDY", "WHAT IS TIDY?", "DOX", "HISTORY", "ACK", "GET TIDY", "FAQS"
```

Maybe the best choice here is "WHAT IS TIDY?", which ends with `TidyLib is used today in desktop applications, web servers, and more.`.

To that we could add say a link, like `Here is a list of <a href="proj.html">projects</a> that use the TidyLib API, or the tidy condole app.`... Put the list in proj.html...

Also at present there is a section in "GET TIDY" talking about `Software using TidyLib`, but is does not list anything... So such a list could be added there... or maybe this could be moved to the above...

Alternatively, the above 7 headers could be expanded. Maybe add a "USES OF TIDY" page...

More suggestions welcome... our web pages could certainly do with some TLC ;=))

**Comment by balthisar** [comment]
Given we added the Tidy + section on the main page, and the /plus portion of the website, I'll close this issue for now.

Please do feel free to open it again if there are any new suggestions. Especially if (as @skynet indicated) you know of any specific articles worth mentioning about tidy code.
