### ISSUE TITLE
tidy installs platform.h

### ISSUE THREAD

**Issue by ryandesign** [htacg/tidy-html5#223]
Tidy installs an include file called platform.h in the general include directory (e.g. /opt/local/include in MacPorts). This is a problem because the name of the file is so generic.

This can cause problems with other programs that happen to have a private include file of the same name in their source directory. With a generic name like "platform.h", this is not unlikely. When they write `#include "platform.h"` they expect to get their private file, but `-I/opt/local/include` might be in `CPPFLAGS`, either because the package manager or the user put it there (MacPorts does), or because the project got it from the pkg-config file or *-config script of one of its dependencies. If the project's build system is such that `-I/opt/local/include` appears before `-I.` in the compiler invocation, then tidy's platform.h would be used instead of the project's, leading to build failure. That would be an error in that project's build system, but such errors are very common.

In MacPorts, this problem [affects qscintilla](https://trac.macports.org/ticket/26958), and also [scite](https://trac.macports.org/ticket/28230), which uses qscintilla, and probably anything else that uses scintilla or qscintilla.

Please consider either not installing platform.h, or renaming it to tidyplatform.h such that its name is less generic and its association with tidy is clear (which would match the naming of the file tidyenum.h), or moving it and all other installed include files that aren't tidy.h (including buffio.h, whose name is also generic) into a tidy subdirectory (e.g. /opt/local/include/tidy).

**Comment by geoffmcl** [comment]
@ryandesign this is a very **valid** point. One that has concerned my for quite some time, as I have experienced these generic header `name` problems several times before...

One of the worst is the many projects that use and install a `config.h` ;=() And although tidy does have a `config.h`, it is only local, and not installed.

I think I would go for the platform.h to tidyplatform.h, and buffio.h to tidybuffio.h rather than the alternative of changing to <tidy/titdy.h>, thus installing in a tidy sub-directory, but will reflect upon this a little...

And now is a good time to make this change before the release, so will not reflect for too long ;=)).

Look forward to any other comments...

**Comment by geoffmcl** [comment]
@ryandesign done and issued 5.0.0.RC1 at the same time...
