### ISSUE TITLE
why is tidy wrapping my fragments in html > body tags?

### ISSUE THREAD

**Issue by airtonix** [htacg/tidy-html5#233]
incoming: 

```html
<p>test</p>
```

outgoing:

```html
<!DOCTYPE html>
<html>
  <head>
    <title></title>
  </head>
  <body>
    <p>test</p>
  </body>
</html>
```

- This should be an opt in feature... it breaks the principle of least surprise.
- There isn't any obvious issue tickets talking about it
- nor are there any obvious options flags to prevent it.

**Comment by geoffmcl** [comment]
@airtonix thanks for reporting...

I was not aware **Tidy!** promises to not break `the principle of least surprise`. To me it does some quite `surprising` things, pun intended ;=))

But in this case there is an option to prevent this, namely `--show-body-only yes` or `--show-body-only auto` and you will get back what you gave...

Note this will not happen if the first element of fragment has the CM_HEAD bit set - see #232 for details...

This option defaults to `no`, and I do not think there would be general agreement to defaulting this to `yes` to avoid this fragment of `surprise`, since that would introduce many `surprises` to those presentling a full html file...

And since **Tidy!** is a venrable app it does strongly tend to try to **not** `surpise` the long term users! That is do what it has always done, only better... maybe with new, more options...

So giving this fragment to **old** versions like `tidy04aug00 (2000)`, `tidy-2004`, `tidy-cvs (2009)`, ..., they **all** do the same wrapping of the fragment into full, viable html...

Ergo, this is one of those **tidy has always done this** `principles`! ;=))

I do see arguments both ways, with maybe a new option like `--omit-implicit-elements`, or something... but tend to fall into the `do not change this` pool at present... 

Will leave it open for now for other comments, ideas...

Again, thanks for opening the topic...

**Comment by geoffmcl** [comment]
@airtonix since there have been no further comments for over a month am closing this, but feel free to re-open or post another issue...
