### ISSUE TITLE
Disable trimming empty elements

### ISSUE THREAD

**Issue by mperham** [htacg/tidy-html5#237]
I've got a document which uses Bootstrap glyphicons like so:

```
<li> <span class="glyphicon glyphicon-ok-sign"> </span></li><li><span class="glyphicon glyphicon-ok-sign"></span></li><li><span class="glyphicon glyphicon-ok-sign"></span></li>
```

tidy5 strips out all of the empty lis and spans, making the document worthless.  I just want a tool which pretty prints the HTML, not something which mangles the document.  Possible/reasonable?

**Comment by geoffmcl** [comment]
@mperham have you tried the option `--drop-empty-elements no`?

Seems this will do what you want?

And maybe `--drop-empty-paras no` if you want to also keep empty `<p>` elements...

Also, if like the sample shown, it is just a html snippet, then you may want to add `--show-body-only yes`...

And just a reminder, `-help-config` will output the considerable list of Tidy! options, and `-show-config` will list the current defaults...

If installed in a unix/linux system then `$ man tidy` should bring up manual page tidy(1) with option descriptions...

And the same thing can be seen on - http://www.html-tidy.org/quickref.html -

I guess Tidy! would prefer to call it `fixing`, rather than `mangling` the document!

But it is agreed it takes some time to get with the some 94 **diverse** options of Tidy! ;=))

**Comment by mperham** [comment]
Thank you @geoffmcl, I had no idea about those options or help screens.  I'm used to curl, which prints out all zillion options on its help screen.
