### ISSUE TITLE
It doesn't seem to recognize html5 doctype

### ISSUE THREAD

**Issue by nkmathew** [htacg/tidy-html5#240]
Version info:

    HTML Tidy for Windows version 5.0.0.RC1

Error message:

    >tidy -config tidy.cfg -indent -modify test.html
    Config: missing or malformed argument for option: doctype

Config file:

    doctype:html5
    indent:yes
    indent-spaces:2
    wrap:120
    tab-size:4
    newline:LF
    quiet:yes
    show-warnings:no
    add-xml-space:yes
    tidy-mark:no

Before:

    <html>
    <head>
    <title>Testing tidy-html5</title>
    </head>
    <body>
    <p>Hello World</p>
    </body>
    </html>

After:

    <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 3.2//EN">

    <html>
    <head>
      <title>Testing tidy-html5</title>
    </head>

    <body>
      <p>Hello World</p>
    </body>
    </html>

**Comment by geoffmcl** [comment]
@nkmathew I seem unable to repeat this problem! ;=((

I used a config file as above, **except** removed the last tidy-mark:no option so I could **see** the version...

Command: `> ...\test>tidy-5.0.0 -config input5\cfg_240.html input5\in_240.html`

Output:

```
<!DOCTYPE html>
<html>
  <head>
    <meta name="generator" content="HTML Tidy for HTML5 for Windows version 5.0.0.RC1">
    <title>
      Testing tidy-html5
    </title>
  </head>
  <body>
    <p>
      Hello World
    </p>
  </body>
</html>
```

I get these **same** results with the current `master`, and the later `issue-228` branches of the repo, except for the versions being `5.1.2` and `5.1.6.D231` respecively...

Now, if I use an **OLD** cvs version of tidy, namely one built from the now **old-out-of-date** sorceforge cvs repo, I do get something similar to what you show...

```
...\test>tidy-cvs -config input5\cfg_240.html input5\in_240.html
Config: missing or malformed argument for option: doctype
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 3.2//EN">
<html>
  <head>
    <meta name="generator" content="HTML Tidy for Windows (vers 25 March 2009), see www.w3.org">
    <title>
      Testing tidy-html5
    </title>
  </head>
  <body>
    <p>
      Hello World
    </p>
  </body>
</html>
```

You need to check your `PATH` environment variable! Or maybe a `TIDY` environment variable...

It really seems like you are using a truly ancient version of tidy ;=)) `>tidy -v` should reveal what it is...

**Comment by nkmathew** [comment]
I've been running the version from 2009 all this time without even realizing. I was formatting the file from with SciTE which happens to ship with one of the first versions of tidy which gets picked up first instead of the one in my PATH.
Had to delete it for it to work

**Comment by geoffmcl** [comment]
@nkmathew glad you have updated to a later Tidy! version...

Concerning SciTE, maybe you could somehow advise `Neil` that the latest version of Tidy! is **here** ;=))

I do not know much about Scintilla/SciTE but in checking out some web pages I note they all still seem to refer to the now very **outdated** tidy sourceforge sites...

We have tried very hard to get in touch with the tidy sourceforge site maintainers, and offered to assist in updating that sf site to the latest code here, but have not had much luck so far...

So we will have to put up with the type of problem you encountered for some time yet...

**Comment by nkmathew** [comment]
The installers are made by Troy(of ebswift), not Neil.
He has updated it for the current version, v3.6.0, so it's all good

http://opensource.ebswift.com/SciTEInstaller/


-- 
nkmathew

**Comment by geoffmcl** [comment]
@nkmathew thank you for the SciTE `Troy` installer information...

Just out of interest, if a Tidy binary **is** included with the SciTE 3.6.0 installer, what **version** of tidy is it?

As you may have noted, I just recently merge the `issue-228` branch into the `master` branch and bumped the version to 5.1.8 (2015.09.04), with a new option `--vertical-space auto`, but it also contains quite a number of other bug fixes...

Probably, if you can compile tidy from the git source, you could update the tidy binary in the SciTE installation, and thus benefit from using the **latest and best** ;=))

Over time I will also try to get around to adding a final tidy 5.0.0, and a tidy 5.1.8, to  http://www.htacg.org/binaries/ ... 

Since the tidy binary consists of just one executable file it should be very easy to update it in any other project install... Of course if they installed in the usual `Program Files` directory in Windows you may need to run as administrator to do the copying and over-writing...

**Comment by nkmathew** [comment]
Don't think he wanted or had the time to build it himself. The exe(with dll) was obtained from the binaries site:

    $ "C:\Program Files (x86)\SciTE\tidy5.exe" -v
    HTML Tidy for Windows version 4.9.35

Can't say I follow the project closely, I just needed to get rid of a minor annoyance. I'll build the latest version from the repo when the need arises ;)

**Comment by geoffmcl** [comment]
@nkmathew again thank you for the information...

Yes, it does look like he got the exe/dll from the binary site, which is good to know...

Tidy version 4.9.35 is certainly quite recent... circa Jun 9 2015... is quite stable, and contains some good featues and bug fixes...

I have now added **both** a final tidy 5.0.0, and a tidy 5.1.8, releases to http://www.htacg.org/binaries/ ... so assume he would pick these, or a later version, on the next SciTE release cycle...

With the tidy version `5.+.+` release the name reverted to just `tidy.exe`, dropping the `5`, and the exe is linked with the **static** version of library tidy, so the DLL would not be needed...

As stated you could probably update your current SciTE installation just by downloading the tidy-5.1.8-win32.zip, extract the files somewhere, and copy the tidy.exe to the SciTE install, renaming it to tidy5.exe...

Hmmmm, I just tried to install firsts scite-3.6.0.msi and then scite-3.6.0x64.msi, and found **both** still contains `tidy.exe` 32-bit... Maybe I can understand the 32-bit, since have not been able to find a windows 64-bit scintilla/SciTE download... and have nearly done this from source... But this `tidy.exe` is still the **OLD 2009** version!!!

Also I found these `msi` installers contained no `*.properties` files, so I get no color coding for each language! The manual install of `wscite360.zip', I downloaded from http://www.scintilla.org/SciTEDownload.html, that I did earlier, contained some 79 `properties` from `abaqus - yaml`... and includes `html`, `perl`, ... which I use now and then...

#### What did you download? Install? From where?

Sorry to add more questions, but I would like to understand how you got `tidy5.exe`, v4.9.35?

On a separate note, have you tried [Notepad++](https://notepad-plus-plus.org/)? Like SciTE, it also uses the `scintilla` library... is fast, efficient, and includes the ability to run a tidy exe... and **lots** of other great features...

**Comment by nkmathew** [comment]
Not sure why you're not getting any `properties` files. The files should be in **C:\ProgramData\SciTE** after installation.

He must've forgotten to update the installers in the download page or something, idk. The updated ones can be found here:

www.ebswift.com/temp/scite-3.6.0.msi
http://www.ebswift.com/temp/scite-3.6.0x64.msi

He thought it would be a good idea to rename the binaries so that they don't shadow any other(newer) versions you may have in your path when running tidy on a file from within SciTE.

NPP is not really my cup of tea, it  doesn't have an output pane as good as SciTE's and is less tweak-able as far as I know. The "great features" offered by npp can be replicated in a text editor like Vim with a couple of plugins thrown in.
