### ISSUE TITLE
Code Style

### ISSUE THREAD

**Issue by skynet** [htacg/tidy-html5#245]
What about using something like https://github.com/bengardner/uncrustify in a git-hook to impose a consistent coding-style?

**Comment by geoffmcl** [comment]
@skynet wow, you find some interesting things...

I downloaded and built it from source to give it a try... called it `unc` rather than having to type in `uncrustify` all the time ;=))

ZUTE! And I thought our Tidy! was **heavy** with so many `options` until I read, from `$ unc -?` -

```
There are currently 502 options and minimal documentation.
```

And similar to Tidy! has a `--show-config` which lists them all, with a brief description...

I guess you could merrily spend weeks, months, or more!, getting the `configuration` you like... Thankfully, like Tidy! it can all be kept in a configuration file...

I saw some `interesting` options, like one I was faced with recently, remove a BOM...

```
# Control what to do with the UTF-8 BOM (recommend 'remove')
utf8_bom                                 = ignore   # ignore/add/remove/force
```

But there are just so many options ;=()

Hmmm, while I think it seems an interesting tool for some projects, I do not think it is needed for Tidy!

First do not like the idea of **impose** a style! For a start who is to choose that style? By votes? How? 

Some things would probably be simple to more or less agree, like 4-space indenting, and no tabs, no C++ commenting `\\`, opening `{` takes a new line, etc... but I can see personal preferences and differences getting in the way of others being universally agreed...

And if I understand a `git-hook` correctly I really do not like the idea that after I push a change, a `git-hook` can alter that file, make indent changes, and my local repo would be immediately behind... That would not feel good ;=((

And besides, Tidy! source already has a style, unfortunatley only really documented by reading the source, but in general people do tend to follow this `style`...

I guess one of the first things would be to try and **document** the Tidy! `style` ;=))

As a consequence of this exploration found [UniversalIndentGUI](http://universalindent.sourceforge.net/) which lists `HTML Tidy` as a supported feature, unfortunatley with the **old** sourceforge URL, as well as this `uncrustify`...

Having some difficulty compiling this GUI from source until I get around to building [QScintilla](https://riverbankcomputing.com/software/qscintilla/intro) first... a dependency...

Anyway, just a personal comment on this... maybe there are others with a different ideas...

**Comment by skynet** [comment]
Thanks, @geoffmcl - was just a suggestion. Keeping the code clean is always a good idea.

**Comment by geoffmcl** [comment]
@skynet certainly agree with `keeping the code clean` is important...

Have started a CODESTYLE.md file, in the repo, with some initial ideas... Maybe you, or others, have things to add to this... to make it a full and complete `Tidy Style` document...

A little off topic, but also have got very interested in the [scintilla](http://www.scintilla.org/) library, and an editor, `SciTE` that uses it... 

Some of the first real fun coding I did (in Intel 8086 asm) was on what I called `the world's fastest IBM PC editor`!, so have always liked playing with `editors`... which, in a way, is what Tidy! is... So thanks for opening this box of butterflies ;=))

**Comment by skynet** [comment]
I'd love to help but going through terrible time constraints on other projects these days. We need to reach out to community. Here's a perfect model for how we should ask for help:

https://github.com/snowplow/snowplow/blob/master/CONTRIBUTING.md

Let me know if you can create this file and a better Contributing section in the https://github.com/htacg/tidy-html5/blob/master/README.md file.

**Comment by geoffmcl** [comment]
@skynet good idea!

Added a [CONTIBUTING.md](https://github.com/htacg/tidy-html5/blob/master/CONTRIBUTING.md), and a link to it from README.md...

**Comment by geoffmcl** [comment]
@skynet while `Code Style` is a **forever** open topic, will close this for now...

**Comment by skynet** [comment]
:+1:
