### ISSUE TITLE
Removal of empty <i> tags

### ISSUE THREAD

**Issue by bizharvest** [htacg/tidy-html5#247]
Seems to remove empty <i> tags which are the standard tags used for bootstrap icons. I have set drop-empty-elements to false and even added 

new-inline-tags => 'i'
new-empty-tags => 'i'

Though I don't think those two should be needed.

Any help with this would be greatly appreciated.

**Comment by geoffmcl** [comment]
Hi @bizharvest, thanks for reporting, but I can not seem to find a problem with the `--drop-empty-elements false` option. It seems to work for me...

Input: file input5\in_247.html
```
<p>Empty <i></i> italics</p>
```

Config: file input5\cfg_247.txt
```
drop-empty-elements: false
show-info: false
show-body-only: true
```

Version: from `tidy -v`, from the current `master` branch -
```
HTML Tidy for Windows version 5.1.2
```

Output: as expected, using `...\test> tidy -config input5\cfg_247.txt input5\in_247.html`, namely -

```
No warnings or errors were found.

Info: Document content looks like HTML5
<p>Empty <i></i> italics</p>
```

Got the same results from the version `5.0.0.RC1`, in the `release/5.0.0` branch, and the latest `5.1.7.D231`, from the `issue-228` branch...

Of course it will **not** work with the sourceforge cvs source, version `HTML Tidy for Windows released on 25 March 2009`, since it does **not** support this `drop-empty-elements` option...

What **version** of Tidy! are you using? Where did you get it? Or what source, and branch, if you compiled from source...

If there is still a problem for you, then please provide a small input sample, the config used, the output, and if different to output, the expected output...

Hope this helps...

**Comment by bizharvest** [comment]
Thanks for your time. Upon further review I realized that when I translated my php array into commandline I was not properly passing in "false" as a parameter. It was simply passing an empty string which of course is not the same thing. 

I changed my logic to detect false and translate it into "false" as a string and everything now works as expected.
