### ISSUE TITLE
Feature request, -asjson or -asjxon

### ISSUE THREAD

**Issue by vielmetti** [htacg/tidy-html5#250]
I use `tidy` in a Unix pipeline that starts with a messy HTML page and ends up with a JSON document that I extract a few things out of with `jq`. This generally works pretty well, and is reasonably portable, except for one key element: the `xml2json` step. 

A great weird idea for `tidy` is to offer a canonical `-asjson` output, that would be the one-step version of the pipeline that looks like `tidy -asxml | xml2json`. 

The difficult element of this is that there is no one canoncial `xml2json` command everywhere, though there are implementations that I have found in C++, Go, Perl, and Python. They each do the task as advertised in a slightly different way, and thus offering substantial opportunities for non-portability.

There is a Mozilla document at https://developer.mozilla.org/en-US/docs/JXON which describes "JXON", and the "Parker Convention", as standardization efforts, so to the extent feasible that's a likely target.

Comments welcomed (and lots of thought welcomed before trying to write code).

A longer writeup of the problem space here: http://vielmetti.github.io/post/2015/2015-09-10-xml2json/

**Comment by geoffmcl** [comment]
@vielmetti as you may know from the Tidy! source, tidy is really two(2) separate items...

 1. tidy library - libTidy - a C library with an extensive API, in `tidy.h`, and
 2. a console app, tidy, canonical example usage of the API to achieve its goals.

So while I do not think the conversion of the xml output to json is a job for libTidy - json is **not** html nor xhtml - we build our own DOM like tree of elements, so no change to libTidy needed...

But it could be a function written into a console app that uses libTidy to get the XML!

Starting with say the `tidy.c` source, renaming it to maybe `tidy-json.cxx`, and including say the `xml2json.hpp` from https://github.com/Cheedoong/xml2json, or some other `conversion` code/modules, then you could add the -tojson switch.

This would take the tidy-json input and convert it to xml in a tidyBuffer with -

 - `tidySaveBuffer(doc,buf)`, or
 - a user buffer with `tidySaveString(doc,ubuf,plen)`, 
 
instead of using the normal `tidySaveFile` or `tidySaveStdout`, and pass that buffer to `xml2json`, returning the required json string... `json_str = xml2json( buf.bp );`...

If you wanted to share that source, maybe we could add such a `tidy-json.cxx` to console or experimental folders, as another choice, another example of what can be done with the libTidy API...

Or like my [tidy test](https://github.com/geoffmcl/tidy-test) be a separate repo, and use the `FindTidy.cmake` in there to find and link with an installed version of libTidy...

Possibilities are endless ;=))

And maybe I will get a chance to try it in my `tidy test`! I just found I first built `xml2json` back in 20140215, by adding a CMakeLists.txt and doing some WIN32 porting... 

I updated my local clone, re-built and installed it. So now I have an installed set of some 33 xml2json.hpp, rapidjson/* and rapidxml/* headers to easily link into a new app ;=)) 

Will see how that progresses... if I get the time, interest...

So at present do not see this as a `Feature Request`, more `Technical Support` for using the API...

Hope this helps.

**Comment by vielmetti** [comment]
Not important enough to keep on the issues list, so closing.

**Comment by geoffmcl** [comment]
Well sorry now I spent so much time of researching and preparing a 
detailed answer if it was not so important...

But trying to promote the libTidy API is always a good thing, so no 
problem...
