### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by mtangoo** [htacg/tidy-html5#268]
Path: http://www.html-tidy.org/documentation/
broken section is " configuration quick reference here " which points to http://www.html-tidy.org/tidy-html5/quickref.html

**Comment by vielmetti** [comment]
The link to "API Documentation" immediately below it is broken as well, http://www.html-tidy.org/tidy-html5/tidylib_api/

**Comment by vielmetti** [comment]
Also on

http://www.html-tidy.org/

> Currently the HTACG team is working hard putting the finishing touches on the new, stable version of Tidy, but you can be sure that we are developing solutions to provide binaries for your operating system as well as distribution through all of the common Linux/Mac software repositories.

It would be good to update this text to reflect current progress including distribution through `homebrew` and `port` on the Mac. I'm not sure where that web site lives or what controls it.

**Comment by geoffmcl** [comment]
@mtangoo, @vielmetti thanks for reporting these, and the suggested content enhancement...

All welcome, but I would certainly appreciate any help in `fixing` these...

The site pages are stored in the tidy-html5 repo, `gh-pages` branch. To get the source just -

```
$ cd tidy-html5
$ git pull
$ git checkout gh-pages
$ git pull
```

All the contents, links etc are in the `_posts/*.md` docs... 

I have tried a few times to fix these URL's, but as indicated **need** HELP! Maybe there is something about the _config.yml, or other yaml parameters that I do not understand...

Conversly, the content of the API docs, http://www.html-tidy.org/tidy-html5/tidylib_api/ pages are generated in the tidy-html5 `master` branch, using `xsltproc` and `doxygen`, so a fix of a link in those documents starts with the source in the `documentation` folder...

See doxygen.cfg, *.dox and tisy1.xsl files, and others...

And to generate the API documentation you need to do the standard tidy build and then add an important cmake option -DBUILD_DOCUMENTATION:BOOL=YES to add a documentaion target...

```
$ ch tidy-html5
$ git checkout master
$ git pull
$ cd build/cmake
$ ./build-me.sh # simple build, and then, and if ok...
$ ./build-me.sh -DBUILD_DOCUMENTATION:BOOL=YES
$ [sudo] make documentation
```

That last step will `generate` the API documentation in `documentation/temp/tidylib_api`... 
Can be locally viewed with say `firefox index.html`...

There are about 3 outstanding doxygen warnings during this step that need looking at, but do not seem the stop the API docs generation...

The publishing is a separate step, consisting of again checking out the `gh-pages`, and copy the site files generated above to the `tidylib_api` folder, and pushing the result... easy...

But of course any change in the content must be **fixed** in the relevant sources...

@pedromorgan has also setup an API documentation site, read #248, namely http://tidy5docs-htacg.rhcloud.com/, but I have no idea how to get, or publish these...

Any help on this site pages and/or api documentation gen is **much** appreciated ;=))

**Comment by mtangoo** [comment]
If no one fixes it until I have time I will do that!
Thanks for good work

**Comment by geoffmcl** [comment]
@mtangoo thanks... look forward to it when you get the chance...

**Comment by pedromorgan** [comment]
Working on a Patch..Now
Do I do this aginst "master"..
What happened to develop....

**Comment by geoffmcl** [comment]
Yes, the old `development-500` branch has been deleted after its contents were merged with `master`... 

This is also true for the `indent-with-tabs` and `issue-228` branches. Their content has been merged to `master` and will get around the deleting them in due course...

Will shortly be merging and deleting the `issue-65` branch, after a little more testing...

There are currently only 3 relevant branches -
 
  1. **release/5.0.0** - Is release 5.0.0
  2. **master** - the default stable branch
  3. **gh-pages** - the site pages
 
The idea is additional, new branch will be create now and then, to isolate say possible code  regressions, errors, and thoroughly test them, before merging to `master`...

But this issue is about site pages content, not code, so -

 - If correcting site pages - http://www.html-tidy.org - then it is the `gh-pages` branch.
 - If correcting doxygen generated API docs - http://www.html-tidy.org/tidylib_api/ - then it is the `master` branch...
 
Look forward to help getting the site fixed and updated...

**Comment by balthisar** [comment]
Fixed.
