### ISSUE TITLE
docs: update Mac documentation to reflect availability on Fink

### ISSUE THREAD

**Issue by vielmetti** [htacg/tidy-html5#276]
Per #272 the Fink package manager now has tidy-html5 , as seen on https://sourceforge.net/p/fink/package-requests/1044/

Next, the tidy-html5 documentation is to be updated to reflect this.

A related issue is #271 (Macports docs).

**Comment by geoffmcl** [comment]
@vielmetti tidy still waits for **actual** help on the site pages updates, rather than just very welcome suggestions... thanks...

So who out there can assist with this?

**Comment by balthisar** [comment]
@vielmetti, I couldn't install fink behind my picky proxy (the last time I used fink it came on a disk image). Thus I'll ask for your support on this:

Q: assuming fink is already run and installing, what's the terminal command for installing tidy-html5? Include sudo if necessary.

I've made changes to the "Get Tidy" section of the website; fink is now listed as coming soon. As soon as I have an install instruction here I'll add it to the web page. I'm GMT+8 so allow for the chance I'll be asleep.

**Comment by balthisar** [comment]
@vielmetti, I managed to get fink installed on an El Capitán install at home. When I `fink install libtidy5` it seems to install the libraries but I can't find the executable anywhere in `/sw/`. Because the documentation was built it's pretty obvious the binary was built, but seems like it wasn't installed.

Are you getting different results? I hate to add documentation to the site that doesn't work for others.

**Comment by vielmetti** [comment]
@balthisar - I do not alas have a primary computer running fink to know how it should happen. However, the suggestion I'd have is to do `fink install tidy` and see if it brings in the executable.

The commentary on the above Fink project from the maintainer reads:

"I just added libtidy5/libtidy5-shlibs to cvs. The binary is still called 'tidy'."

**Comment by balthisar** [comment]
I'll have another go at it tonight.

**Comment by geoffmcl** [comment]
@vielmetti, @balthisar this fink [package](http://pdb.finkproject.org/pdb/package.php/tidy) pages shows 5.0.0 is there... that is great.. thanks...

Maybe there is a later page, or is it possible to get that updated to release [5.1.25](https://github.com/htacg/tidy-html5/releases/tag/5.1.25)? 

Do we have to file another bug report like in #272, or what? 

Some distribution systems reply on our release [feed](https://github.com/htacg/tidy-html5/releases.atom). Is something like that possible for `fink`?

Any help appreciated...

**Comment by balthisar** [comment]
I've tried to reach out to the package maintainer; I'll see if we get anywhere. I see that he maintains 1600 packages, so he may not even notice my email.

**Comment by danielj7** [comment]
Hi! I'm the tidy maintainer for Fink. I just updated it to 5.1.25. Now that I know it's being updated frequently I'll be sure to check more often. :) If you find it's not up-to-date again, please don't hesitate to email me about it. Contact information is shown with `fink info tidy`.

As you've discovered, there are 3 related packages: `tidy` (actually binary), `libtidy5` (headers and lib symlinks) and `libtidy5-shlibs` (shared library). You should only every need to install `tidy` unless you want to manually build something that links to the lib. The lib packages are really just to be dependencies for other packages.

**Comment by balthisar** [comment]
@danielj7, _awesome_! Thank for so much for coming through! I also received your email response and I will try to answer as soon as my VPN starts working again or I get back to work (gmail not so welcome where I'm at).

Because this issue reflects documentation (and the documentation still says "coming soon" for fink), I'll leave this open until I update our website (will install fink in VM and verify installation method).

**Comment by balthisar** [comment]
Documentation now live on http://www.html-tidy.org, and so closing.
