### ISSUE TITLE
Provide an HTML5 parser/deserializer that MediaWiki/PHP could use

### ISSUE THREAD

**Issue by hexmode** [htacg/tidy-html5#277]
MediaWiki developers are looking for [a replacement to tidy that would parse and reserialize HTML5](https://phabricator.wikimedia.org/T89331).  Would the library here be able to produce a DOM tree for manipulaton?

**Comment by hexmode** [comment]
In MW's bugs, this effort is tracked under https://phabricator.wikimedia.org/T113976

**Comment by geoffmcl** [comment]
@hexmode I read through the links you provided, and some deeper links, but still not sure what is required? Exactly what are you/they looking for???

First I note some of the `blocks` were raised against sourceforge tidy, which has been frozen since circa 2009!

We, HTACG, have approached the SF Tidy maintainers, with an aim to doing something about that... but presently no suitable response... so sf is just there, frozen... now causing never ending confusion...

So the first thing would be to update to using only http://www.html-tidy.org/, and source https://github.com/htacg/tidy-html5, and re-test **all** to see if tidy still **sucks** ;=()

I would suggest it has improved a lot over the last 5+ years in github, especially since June 2015 when we release 5.0.0... and the current 5.1.14+ contnues to improve...

But this re-test might prove impossible since it felt like some had already made up their mind about tidy... and given that I read several that were not happy with tidy's handling of space and newlines, and for sure, like a browser, tidy removes most `space`, unless encoded as `&nbsp;`, so this in itself may not be suitable...

But, yes, given a stream or buffer to parse tidy produces an internal DOM tree. As the tidy.h sample code `dumpNode()` shows, you can iterate through all the nodes... if this is what you want... and build your own tree from that...

But there are presently no internal DOM tree sevices - to create nodes, append or insert nodes, delete nodes, deal with attributes, create, add, delete, sort, and add a text node, etc, etc - exposed. They are all `private`, internal to the library...

I suppose given a use case such services could be added to the API, but this would **not** be an easy task, like all the text is not actually kept in the node tree, but rather as offsets into a lexer buffer... which is part of the document...

And one could argue this is **NOT** really the purpose of libtidy, to include manipulation of tidy's internal DOM tree, presently deliberately kept **very** opaque...

Anyway, maybe I do not understand the question... hope this helps...

**Comment by hexmode** [comment]
Geoff McLane writes:

> @hexmode I read through the links you provided, and some deeper links,
> but still not sure what is required? Exactly what are you/they looking
> for???

They (WMF developers) are looking for a way to get a DOM tree that they
can query and then produce HTML from.  They're looking for a complete
HTML5 parser for this.

I am looking for a way to get this without introducing Yet Another
Service.  They already have a service in development, but I hope that we
can make this available to people using MW without requiring YAS be
deployed.

If Tidy could expose a "true" DOM, I think that would get us a long way
there.

> So the first thing would be to update to using only
> http://www.html-tidy.org/, and source
> https://github.com/htacg/tidy-html5, and re-test **all** to see if
> tidy still **sucks** ;=()

Even if tidy doesn't suck anymore, the needs have grown to include HTML5
parsing and reserialization.

> But, yes, given a stream or buffer to parse tidy produces an internal
> DOM tree. As the tidy.h sample code `dumpNode()` shows, you can
> iterate through all the nodes... if this is what you want... and build
> your own tree from that...

Maybe this would be enough.

> Anyway, maybe I do not understand the question... hope this helps...

Thanks for your response.

**Comment by tstarling** [comment]
MediaWiki does not need Tidy to expose its DOM. MediaWiki does not need a DOM, it needs HTML, which is what Tidy already provides. But MediaWiki does not need anything else that Tidy does -- we only need a precisely HTML 5 compliant parser and a slightly customised serializer. That's why we are going to use an HTML 5 parser library instead of Tidy.

Since 2004, MediaWiki has been using Tidy as the final stage in its wikitext to HTML translator, to convert user-input tag soup into XHTML. But Wikipedia's wikitext markup has a lot of reusers and independent parser implementations, and it is archived forever, so what we really needed was a stable tag soup specification which would allow anyone to understand how wikitext is converted into XHTML. In 2004, there was no such specification, so we used Tidy because it was the best, most mature tool to do roughly what we wanted. But now we have a tag soup specification in the form of the HTML 5 parsing algorithm, so we are migrating to it.

It's a sad day to leave behind a project we've depended on for so many years, but we are leaving it behind. I say this as the lead developer of this migration project. We will continue to provide a configuration option which allows Tidy to be used, so hexmode can keep using it on the wikis he supports. And the new HTACG Tidy can probably be used with this configuration by just changing the binary location.

**Comment by hexmode** [comment]
@tstarling thanks for weighing in and helping to clarify the issue.  I think a big part of my confusion comes from [this comment](https://phabricator.wikimedia.org/T89331#1681614):
>Given a string, you need a HTML5 parser to parse it into a DOM -- that and nothing less and nothing more. HTML5depurate is one such solution.

That seems to contradict your statement:

> MediaWiki does not need a DOM, it needs HTML, which is what Tidy already provides. But MediaWiki does not need anything else that Tidy does -- we only need a precisely HTML 5 compliant parser and a slightly customised serializer.

I will defer to your statement and I apologize by muddying the issue by asking for a DOM.

(For what its worth, my clients wouldn't have a problem using HTML5depurate.  it isn't their needs I'm concerned about here.)

**Comment by hexmode** [comment]
@geoffmcl, given the above and the investment tidy-html5 has already made without, I guess, aiming for precise HTML5 compliance, is this ("a precisely HTML 5 compliant parser and slightly customized serializer") something you have any interest in making possible?

**Comment by geoffmcl** [comment]
@hexmode again I am confused by your question...

What is libTidy if it is not a `HTML parser` with a configurable serializer called `Pretty Printing`, rendering its internal DOM like tree to HTML or XHTML, to a file, buffer, or stdout? Maybe fixing some html problems along the way...

Now, can we say libTidy is a `precisely HTML 5 compliant` parser? Hmmmm...

Well it is as `precise` as we can make it, and `HTML 5 compliant` is precisely what has been added here at htacg, on top of an already great `HTML 2 to 4` parser, having two internal modes, html5++ and html4--, to deal with the differences...

So, yes, for sure, I am interested in making that possible...

Or are you talking about a separate project to build Yet-Another-HTML-Parser (YAHP!)? Well I  could also be interested in that, but for different reasons ;=))

**Comment by hexmode** [comment]
I think the particular issues were
[<table> in fosterable position in another <table> - tidy (html4) vs html5 treebuilding differences](http://phabricator.wikimedia.org/T69007), [Parsoid and Tidy differ in how they deal with misnested tags](http://phabricator.wikimedia.org/T65699), [Empty elements in DOM: PHP parser+tidy strips them; Parsoid doesn't](http://phabricator.wikimedia.org/T69452).

At least, those were the ones mentioned at the top of the bug.

I also found a link to [this w3c draft](http://www.w3.org/TR/2011/WD-html5-20110525/tree-construction.html#tree-construction) which, afaict, is what people are talking about when the mention "precise html 5 compliance".

Feel free to close this if you still don't understand the request and/or don't have any interest.

**Comment by geoffmcl** [comment]
@hexmode if it is a tidy problem I am interested ;=))

As previously stated, your links all look like OLD bugs... using the OLD sf tidy cvs 2009 source, or even the now old HTACG up to 2014, maybe even early 2015 tidy source... 

They would need to be **RE-TESTED**, against current 5.1.14, and if there is a continuing problem then we would appreciate an issue, with sample html, config, output, expected, filed at https://github.com/htacg/tidy-html5/issues... that would be great...

Now, I do not have time to test the 3 links you gave, but I did find one I could quickly **re-test**, namely https://phabricator.wikimedia.org/T65699

Running the sample html given through tidy 5.1.14 shows no problem here. The warnings tell what it found -

```
line 1 column 214 - Warning: <code> is probably intended as </code>
line 1 column 234 - Warning: discarding unexpected </span>
```

So now no problem over the missing `</code>` nor the extra `</span>`, both are corrected in the output... so who is going to close that bug?

How many more of the bug links are like that?

So I repeat again. I am **very** interested in tidy 5.1.14 issues!

I am sorry your pointer to a W3C draft document did not help me understand "precise html 5 compliance", in that I could not find `precise`, `html 5`, nor `compliance` on that page???

Tidy is not a browser! Its DOM tree is never modified by say document.write()... it is a HTML Parser, fixer, and Pretty Printer... that's all... how it arranges such a node tree to achieve that does not seem very relevant... but there is some DOM tree interrogation in the API...

So, give that no tidy 5.1.14 bug has been identified here yet, and anyway would prefer them in their own separate issue, will close this for now. 

As always, feel free to re-open, or file a new issue... thanks...
