### ISSUE TITLE
Milestone 5.1

### ISSUE THREAD

**Issue by skynet** [htacg/tidy-html5#284]
5.1 - due by October 20, 2015
68% complete  14 open  31 closed
are we on track with this release?

**Comment by geoffmcl** [comment]
@skynet no, not really... 

I would like to see this `issue-65` branch fully tested, issues #65 and #280 closed, and maybe some others... and merged into `master` first...

Besides I thought the original idea was to aim at a new release each 6 months, and the first 5.0.0 was delayed and delayed until June 30 2015, so that would suggest the Dec/Jan 2016 for the next release...

On the other hand when #65 and #280 are closed, there are also some very good, and important, fixes in this 5.1.++, so maybe an earlier release is warrented. What do you think?

Anyway, for now will moved this date out to Nov 20 for now...

**Comment by skynet** [comment]
:+1:

**Comment by geoffmcl** [comment]
@skynet as you have no doubt seen I have moved the next release version discussion to #334, so closing this...

Now have release 5.1.25 into several distributions... [AUR](https://aur.archlinux.org/packages/tidy-html5/), [homebrew](http://braumeister.org/formula/tidy-html5)... 

Still pushing others, like Debian [bugs](https://bugs.launchpad.net/ubuntu/+source/tidy/+bug/1029209) and Ubuntu [question](https://answers.launchpad.net/ubuntu/+source/tidy/+question/276623)...

And have begun a discussion on the steps, etc... appreciate your input...

**Comment by skynet** [comment]
:+1:

**Comment by geoffmcl** [comment]
@skynet it remains **fun** so why not... and I do like getting your `thumbs-up` icon now and again... thanks ;=))

**Comment by skynet** [comment]
glad I can help in some way :) :+1:
