### ISSUE TITLE
Emphasis erroneously combined with parent element

### ISSUE THREAD

**Issue by claviska** [htacg/tidy-html5#288]
If `drop-font-tags` is `true`, any inline element containing `b`, `u`, `i`, or `strike` will inherit the respective style attribute(s) and the emphasis element(s) will be dropped.

Example input:

```html
<i>Test</i>

<div>
    <i>Test</i>
</div>

<a href="#">
    <i>Test</i>
</a>

<span>
    <i>Test</i>
</span>
```

Example output (linebreaks added for clarity):

```html
<i>Test</i>

<div>
    <i>Test</i>
</div>

<a href="#" style="font-style: italic">Test</a>

<span style="font-style: italic">Test</span>
```

The only flag I can find to affect this behavior is `drop-font-tags`, which I discovered by process of elimination. According to the docs:

> This option specifies if Tidy should discard `<FONT>` and `<CENTER>` tags without creating the corresponding style rules. This option can be set independently of the clean option.

That plus the inconsistent behavior demonstrated above leads me to believe this is a bug.

Note: While this wouldn't normally affect the visual representation of the markup, it does alter the structure. A large number of websites and apps use icon libraries with a syntax such as `<i class="fa fa-pencil"></i>`, and this behavior breaks them in the cases above.

**Comment by geoffmcl** [comment]
@claviska thanks for reporting, but at this moment struggling to understand what you think the bug is!

Except of course the name of the option, `drop-font-tags` does seem to be a little misleading in what is says in the help, and what it in fact does... Is this what you are referring to as a bug?

If this option is on, then for each node, the service `Node* CleanNode( TidyDocImpl* doc, Node *node )` will be used. The comment on the head of that service is `/* Applies all matching rules to a node */`, which already seems a better desription of what it will do.

And this same service is called when the clean (-c) option is on, the only difference being that after applying all matching rules to a node, it will move the style to a class, so the output becomes -

```html
<style type="text/css">
 span.c2 {font-style: italic}
 a.c1 {font-style: italic}
</style>
</head>
<body>
<i>Test</i>
<div><i>Test</i></div>
<a class="c1" href="#">Test</a>
<span class="c2">Test</span>
```

And yes, these are the **only** two options that call CleanDocument... and again the comments in the code seem a better description than the current help text, namely -

```
    /* replaces presentational markup by style rules */
    if ( clean || dropFont )
        TY_(CleanDocument)( doc );
```

So at present I see nothing `inconsistent`, other than the actual help desription. What would be a better option name, and decription?

And why do you think this `breaks` something if `<i class="fa fa-pencil"></i>` is used?

So an input of -

```html
<span>
 <i class="fa fa-pencil">Test 5</i>
</span>
```

becomes an output of -

```html
<span style="font-style: italic"
class="fa fa-pencil">Test 5</span>
```
or if clean (-c) is used -

```html
<span class="fa fa-pencil c2">Test 5</span>
```

This looks `consistent`?

Anyway, for the moment marking this as a `feature`, but hope you can clarify what you expect. thanks...

**Comment by claviska** [comment]
Thanks for the quick reply. Given that info, it makes more sense. However, it's not evident from the docs that `drop-font-tags` would trigger this behavior.

From a user's perspective, I was trying to identify what was causing these conversions to happen and narrowed it down to `drop-font-tags`. Given its description in the docs, I assumed it was likely a bug. (I scoured the rest of the options to verify I wasn't missing anything.)

Perhaps a more intuitive name would help, or a bit more detail in the docs as to what `drop-font-tags` actually does.

I'll leave this open for consideration and additional thoughts—but if you think it's a non-issue you're more than welcome to simply close it :)

**Comment by balthisar** [comment]
I have a special interest in the internal documentation (which I want to cleanup in general anyway), so let me take a stab at this.

Things are a bit complicated because `clean` is affected by `drop-font-tags` but `drop-font-tags` has some behavior if `clean` isn't used. This gives us the following interactions:

- `clean` == YES && `drop-font-tags` == YES moves certain tags to css, excluding <font> tags, which are simply removed.
- `clean` == YES && `drop-font-tags` == NO moves certain tags to css, including <font> tags.
- `clean` == NO && `drop-font-tags` == YES moves certain tags to style attributes, excluding <font> tags which are simply removed.
- `clean` == NO && `drop-font-tags` == Leaves all of this alone.

So I can kind of see how the name `drop-font-tags` was chosen; it simply doesn't describe that it _also_ cleans (to style attribute instead of &lt;style&gt; tag) some tags, and there's not a way to drop &lt;font&gt; tags without also performing minimal cleaning.

I think there's is an inconsistency here, whether or not it's the same inconsistency that @claviska mentioned. One could argue that the removing `drop-font-tags`' "cleaning" behavior is the most consistent thing, and leave it to mean _only_ that &lt;font&gt; will be dropped. However this would upset current workflows that implement the current behavior. It's not API-breaking, but it's behavior-breaking and so might be suitable for a minor point release.

**Discussion for possible future point release:**
- Remove the cleaning behavior from `drop-font-tags`.
- Add new `clean-legacy-tags` with a picklist: no, yes, css
    - _no_ makes no cleanup at all (like today's `drop-font-tags` NO and `clean` NO)
    - _yes_ cleans up to style attributes (similar to today's `drop-font-tags`)
    - _css_ does what `clean` does today.
- Because we can't break an API in a minor point release, we still have to do something with `clean`. We can just say it has no effect, as it won't break an API, and marked for removal in the next major release.
  
**Discussion about what we can do today:**
- Add a synonym to `drop-end-tags` and call it `clean-legacy-tags`, which kind of opens the door to a possible future as described above. There are a couple of synonyms already (e.g., `hide-endtags` and `omit-optional-tags`). `drop-end-tags` to be limted as above at next point release.
- _Justification_: although it doesn't clean _all_ legacy tags, it is clearly cleaning some legacy tags. If we encompass more legacy tags in the future then there's no need for a name change. What it does exactly would then be clarified in the new description.
- _New Description_: This option determines if Tidy should perform cleaning of certain legacy presentational tags (currently &lt;i&gt;, &lt;b&gt;, &lt;center&gt; when enclosed within appropriate inline tags) and also determine if Tidy should drop occurrences of the &lt;font&gt; tag. If this option is YES, the &lt;font&gt; tag will be dropped completely regardless of the value of `clean`. Additionally if this value is YES then legacy tags will be replaced with a style attribute on the enclosing tag. However if `clean` is also set to yes, it will override the cleaning behavior of `clean-legacy-tags` and use CSS &lt;style&gt; tags instead of style attributes. This option is a synonym for `drop-font-tags` which has deprecated behavior.
- _New description for `clean`_: This option determines if Tidy should perform cleaning of some legacy presentational tags (currently &lt;i&gt;, &lt;b&gt;, &lt;center&gt; when enclosed within appropriate inline tags, and &lt;font&gt;). If this value is YES then legacy tags will be replaced with CSS &lt;style&gt; tags and structural markup as appropriate. However if `drop-font-tags` is set to YES, then &lt;font&gt; tags will simply be dropped and the style will not be preserved in CSS.

It appears that only <b>, <i>, and <center> are supported. It seems no one has opened an issue for tt, big, small, sup, or sub, so I won't bother opening one now.

**Comment by geoffmcl** [comment]
@claviska absolutely agree it was not evident from the name, nor the docs description...

@balthisar thanks for picking up on this...

This all looks good, but one comment about changing an option name, and about changing what the option actually does... the behaviour...

I feel, if changing a very old option name, I would prefer that that old option name continue to exist for quite a period of time, which I would expect to be quite long, but we could add a `nag` during that period... something like -

The option `drop-font-tags` is depreciate, and will be removed [maybe a when]. Consider using `clean-legacy-tags` and/or `blah blah` instead [because... etc] - a big nag.

This annoying `nag`, maybe output even if quiet is on, out to stderr, is to warn the user to change that old configuration file, script, or whatever... sooner better than later... or suffer...

And likewise for the behaviour. The old option name should continue to do exactly as before, while the new option or options, replacements and/or enhancements, of course offer another, hopefully better, at least clearer idea...

Of course, this is **not** about the docs help descriptions. For sure they should be changed soonest to better reflect what the option really does, even if its name implies something else...

I guess the original `drop-font-tags` only did that. But now it does a great deal more. I am still struggling to prepare a big list of what it does! And as you suggest, could be increased to cover other things, or at least the new option could, but somehow the help description just never got changed... It sure needs to...

Anyway, just my 2 c ;=))

**Comment by geoffmcl** [comment]
issue-288 - 20151027

If options clean and/or drop-font-tags is on, CleanNode( doc, node ) is called. It "Applies all matching rules to a node.".

It presently has 8 actions, only the last is related to font!

#### 1. Bool Dir2Div
```
    Symptom: <dir> <li> where <li> is only child
    Action: coerce <dir> <li> to <div> with indent.
    if ( nodeIsDIR(node) || nodeIsUL(node) || nodeIsOL(node) )
```

#### 2. Bool NestedList
```
    Symptom: <ul><li><ul>...</ul></li></ul>
    Action: discard outer list
    if ( nodeIsUL(node) || nodeIsOL(node) )
```

#### 3. Bool Center2Div
```
    Symptom: <center>
    Action: replace <center> by <div style="text-align: center">
    if ( nodeIsCENTER(node) )
```    

#### 4. Bool MergeNestedElements( DIV and SPAN )
```
    Symptom <XX><XX>...</XX></XX>
    Action: merge the two XXs
```
    
#### 5. Bool BlockStyle
```
  Symptom: the only child of a block-level element is a
  presentation element such as B, I or FONT
  Action: add style "font-weight: bold" to the block and
  strip the <b> element, leaving its children.
  example:
    <p>
      <b><font face="Arial" size="6">Draft Recommended Practice</font></b>
    </p>
  becomes:
      <p style="font-weight: bold; font-family: Arial; font-size: 6">
        Draft Recommended Practice
      </p>
  This code also replaces the align attribute by a style attribute.
  However, to avoid CSS problems with Navigator 4, this isn't done
  for the elements: caption, tr and table
```

#### 6. Bool InlineStyle
```
the only child of table cell or an inline element such as em
```

#### 7. Bool InlineElementToCSS
```
    Transform element to equivalent CSS
    if ( FindCSSSpanEq(node, &CSSeq, yes) )
```

#### 8. Bool Font2Span (eventually)
```
  Replace font elements by span elements, deleting
  the font element's attributes and replacing them
  by a single style attribute.
    if ( nodeIsFONT(node) )
```  

Of course each has other conditions that need to be met. Essentially it converts lots of things to an inline style...

This is done when either option is on, and only if clean is on, will that inline style be converted to a class, C1, C2, etc... ie css is generated.

Hope this helps.

**Comment by balthisar** [comment]
That simplifies things a bit... both `clean` and `drop-font-tags` do the same thing, except the former puts them into a class, and the latter into inline styles. I updated my lengthy comment above to fix my logical matrix (I used &lt; instead of \&lt;, obscuring the behavior differences). Actually there's still a major difference: `drop-font-tags` just ignores the &lt;font&gt; if set to YES. Given the name _alone_ this makes sense. It's the additional things it does that makes it evil!

I'll take a stab at adjusting the documentation tomorrow. Forget everything about future point releases; inline styles aren't really best practices anyway, so I don't think there's a need to add new options to support _only_ this. Given `clean`, I would instead recommend that we simply deprecate `drop-font-tags`, note it in the documentation, and add the `nag`s. It doesn't really do anything useful. Future `clean` without `drop-font-tags` would act is if `drop-font-tags` were in its default NO.

**Current proposed doc change:**
> Deprecated; do not use. It will be removed from future versions of Tidy. Use `clean` instead. If you do set this option to YES it will perform as `clean` except styles will be inline instead of put into a CSS class. &lt;font&gt; tags will be dropped completely and their styles will _not_ be preserved. If both `clean` and this option are set to YES, &lt;font&gt; tags will _still_ be dropped completely, and other styles will be preserved in a CSS class instead of inline. See `clean` for more information.

I would still use most of the new, proposed description for `clean` as stated above.

Thoughts?

**Comment by geoffmcl** [comment]
@balthisar, wow, as we dig into this, and begin to understand more, `--drop-font-tags yes` is really a disaster! It really does just **toss** the font tag into the bit bucket ;=()

Simple example: Some big, red text "Test 6!"

```html
<p><font size="10" color="red">Test 6!</font></p>
```

With drop-font-tags on this becomes something completely different! NO size or color perserved ;=(( Really! ZUTE!! I certainly can not see a use case for such document mangling!!!

```html
<p>Test 6!</p>
```

And with clean, get something nearly reasonable, but is still seems wrong in size -

```html
<style type="text/css">
 span.c3 {color: red; font-size: 70%}
...
<p><span class="c3">Test 6!</span></p>
```

Why is the font size **reduced** to a small `70%`! That should be more like `170%`, or something, but that is another topic...

So yes, I certainly agree with your big **do not use** warning in the docs for drop-font-tags...

Concerning the proposed docs for clean, I would perhaps change the `However`, to `Warning`, but perhaps we should not even mention this ugly drop-font-tags... but as you like...

So if we amend those two description, is that it for now? 

Let any other issues, like this size problem, consider additional tags like tt, big, small, ..., and the validator warns about the use of the font tag in html5, but tidy does not, etc, be posted separately on a case by case basis...

Let's at least have suitable descriptions ;=)) 

Thanks @claviska for bringing this up. What do you think about the new descriptions, and the warning on drop-font-tags?

On a separate issue I feel confident about all the improvements in the `issue-65` branch, so have now merged it into `master`, bumped the version to 5.1.17, so your changes can now go in `master`. Thanks...

**Comment by claviska** [comment]
The proposed changes make the behavior much more clear, and perhaps deprecating `drop-font-tags` is the right move since its far more destructive than I realized.

Didn't mean to open up a can of worms here, but glad it helped to make these options more clear for users :)

**Comment by balthisar** [comment]
I've created branch `tidy_doc_cleanup`. @geoffmcl if you want to pull in 2d0f971 for next release, then it should address this issue. I don't want to merge into `master` and bump the release number over a documentation change.

I'll do some other cleanup in the docs in general, but specifically commit 2d0f971 in the new branch will close this issue. I'll keep this open until the next merge into `master`, though.

**Comment by geoffmcl** [comment]
@balthisar, ok cherry-picked 2d0f971 to `master`... and like seeing the new descriptions ;=))

And after a pull, build, install in linux, read the new tidy,1 doc with `$ man tidy`... looks good... thanks...

**Comment by balthisar** [comment]
The documentation fix is in master, so I will close this.
