### ISSUE TITLE
indent directive fails

### ISSUE THREAD

**Issue by NWSE-ICO** [htacg/tidy-html5#30]
tidy -i
Assertion failed: (option_defs[ optId ].type == TidyInteger), function prvTidySetOptionInt, file config.c, line 392.

Mac OSX 10.6.8 
Textmate uses the -i directive in it's HTML-bundle/tidy command.

**Comment by mcmayer** [comment]
For future reference and in case someone else faces weird assertion failures:

Lines like these
```C
tidyOptSetInt(tidy_doc,TidyShowErrors,1);
```
mysteriously croaked on me, giving an assertion failure:
```bash
Assertion failed: (option_defs[ optId ].type == TidyInteger), function SetOptionInt, file ../../src/config.c, line 381.
```
In the end it turned out that I linked against libtidy instead of libtidy5. Such wrongly linked executables may actually run.

It's only a guess: In the case of #30 somehow the linker must have picked up the wrong libtidy.

**Comment by geoffmcl** [comment]
@mcmayer thanks for adding your findings...

Indeed, until we actually **officially** release a tidy from this HTACG repo it is presently generating a **libtidy5** library, either as static or shared library, and a **tidy5** binary... just to keep any **old** tidy from being overwritten on install to allow for comparisions...

So I do not know how a tidy5 build could link with libtidy, instead of libtidy5? But if I am reading this correctly you are in fact linking libtidy5 to your own app, using what ever build system you have chosen. In this case you certainly need to fix that to look for libtidy5 at this time... being prepared to change it back once we have released a new tidy...

And actually, even if this very unlikely event did happen I still can not see how an 'assert' was triggered. At this time the basic API remains unchanged... and tidyOptSetInt and TidyShowErrors existed back in the soureforge CVS repo that this repo started from... and that CVS repo has not been changed for more than 5 years...

But checking the assert line number of 381 shows whatever `libtidy` you used, linked with, it was **neither** the CVS repo, which has this assert at line 386, **NOR** the latest htacg src 4.9.26 where it is at line 384 of  config.c - see https://github.com/htacg/tidy-html5/blob/master/src/config.c#L384. So one wonders exactly what tidy library you are using. Or you have made some personal modifications!

Further assertions should only exist if you have NOT defined **NDEBUG** in the build. So what you are building is a quasy partial DEBUG version, that can fire assertions, and abort. This should **ONLY** be for testing, never for a **release**. Once NDEBUG has been defined, the `assert` macro compiles as **nothing**. Check out assert.h for this macro...

Anyway, as stated, thanks for reporting...

**Comment by mcmayer** [comment]
Hi, thanks for following up.
I installed tidy-html5 on a Mac using homebrew, following this hint: http://stackoverflow.com/questions/13380012/tidy-html5-on-mac-os-how-to-install, and I definitely linked against the wrong library (the MAC OS libtidy of ”31 Oct 2006”). It was a typo in my Makefile. I think it’s very good to call it tidy5 for the time being.
My guess was that the enums in tidyenum.h changed since then. (It seems plausible that there is some change in almost 10 years.) If that’s not the case I don’t have a good explanation for the assert failure. On the other hand, if I link against the wrong lib then all bets are off anyway. I’m actually surprised it linked and ran at all.
NDEBUG: It was not -D defined:
$ brew install --HEAD tidy
==> Installing tidy from homebrew/homebrew-dupes
==> Cloning https://github.com/htacg/tidy-html5.git
Cloning into '/Library/Caches/Homebrew/tidy--git'...
remote: Counting objects: 714, done.
remote: Compressing objects: 100% (570/570), done.
remote: Total 714 (delta 105), reused 640 (delta 103), pack-reused 0
Receiving objects: 100% (714/714), 570.75 KiB | 308.00 KiB/s, done.
Resolving deltas: 100% (105/105), done.
Checking connectivity... done.
==> Checking out branch master
==> cmake ../.. -DCMAKE_C_FLAGS_RELEASE= -DCMAKE_CXX_FLAGS_RELEASE= -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/tidy/HEAD -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -DCM
==> make install
🍺  /usr/local/Cellar/tidy/HEAD: 12 files, 1.2M, built in 14 seconds
I don’t know cmake that well, is it supposed to define NDEBUG for release? 
The library was installed in /usr/local/lib/libtidy5.a.

**Comment by geoffmcl** [comment]
@mcmayer, know nothing about Homebrew, but it looks like it is just a script to do the cloning, building and installing... something you can easily do manually, or build you own script, or modify and use the .../build/cmake/build-me.sh that comes with the source, except that does not include the cloning... and this build information is in the README.md document of the source...

BUT I am confused about what it is exactly doing, **especially** why it explicitly sets the CMAKE_C_FLAGS_RELEASE to **nothing**! And why it sets the CMAKE_INSTALL_PREFIX to `/usr/local/Cellar/tidy/HEAD`... These options do **NOT** make sense...

And you are certainly right about the enumerations having changed over the years... forgot about that... so yes the `library' and options `enumerations` **MUST** match, else the behaviour will be very unpredictable...

In linux I just did the following 5 steps, in a directory of my choice in my $HOME -

 1. $ git clone git@github.com:htacg/tidy-html5.git tidy-html5
 2. $ cd tidy-html5/build/cmake
 3. $ cmake ../.. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr
 4. $ make VERBOSE=1
 5. $ sudo make install

If you do not have a github.com account, with your ssh credentials, then the repo name may have to be changed to the read only `https://github.com/htacg/tidy-html5.git`...

And it compiled tidy5 and libtidy5.a. The VERBOSE=1 showed me that each source compile **includes** the flag -DNDEBUG, which, as stated would remove all asserts from this `Release` build. And the install was -

 1. /usr/lib/libtidy5.a
 2. /usr/include/tidy.h, plus 3 other headers, including tidyenum.h...
 3. /usr/bin/tidy5
 4. /usr/share/man/man1/tidy5.1
 
Then anywhere is my system I can now run `$ tidy5 ...`, and `$ man tidy5` brought up the 4.9.26 man page... all as expected...

From the little I know about the MAC OS X, you **may** need to add `-DCMAKE_FIND_FRAMEWORK=LAST` to line 3.!

You said `The library was installed in /usr/local/lib/libtidy5.a`, which is indeed the **default** cmake install location, and is why I add `-DCMAKE_INSTALL_PREFIX=/usr`, to get things in the more `traditional` locations... 

But in your case `/usr/local/lib` does NOT make sense since cmake is being explicitily told `-DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/tidy/HEAD`, which to me tells cmake to generate a Makefile that should intall the library in `/usr/local/Cellar/tidy/HEAD/lib`, and the tidy5 in `/usr/local/Cellar/tidy/HEAD/bin`???

So blew that all away and started fresh, and now added `-DCMAKE_C_FLAGS_RELEASE=` to the line 3. and I **DO NOT GET** -DNDEBUG added to the compile lines!!! So it clears this, and also the -O3 full optimized flag so the resulting binaries were `different` ... This seems a **BAD** option to add...

Further, in another trial, if I do not add `-DCMAKE_BUILD_TYPE=Release`, again I do not get -DNDEBUG!

HTH.
