### ISSUE TITLE
Bad-looking cast from unsigned int to character string

### ISSUE THREAD

**Issue by benkasminbullock** [htacg/tidy-html5#306]
In tidy-lib.c, tidyOptGetDefault is returning an unsigned int cast to a string pointer:

https://github.com/htacg/tidy-html5/blob/768ad46968b43e29167f4d1394a451b8c6f40b7d/src/tidylib.c#L358
<pre>
ctmbstr TIDY_CALL       tidyOptGetDefault( TidyOption topt )
{
    const TidyOptionImpl* option = tidyOptionToImpl( topt );
    if ( option && option->type == TidyString )
        return (ctmbstr) option->dflt;
    return NULL;
}
</pre>
Notice here that it checks the option->type is TidyString, then it returns a cast to dftl, rather than returning pdflt.

However, in config.h, it says

https://github.com/htacg/tidy-html5/blob/768ad46968b43e29167f4d1394a451b8c6f40b7d/src/config.h#L42

    ctmbstr             pdflt;      /* default for TidyString */

If it is truly casting an unsigned integer to a character string, then possibly pdflt above is unnecessary, or something? I'm not sure exactly what's happening here but I thought I'd point it out.

Again, this is from cpantesters (darwin):

http://www.cpantesters.org/cpan/report/fccd5c2a-8d30-11e5-8307-f47b3216c2f9

Please ignore the other errors in the above cpantesters report, which are entirely from code written by me, and unrelated to the HTML Tidy project.

**Comment by geoffmcl** [comment]
@benkasminbullock thanks for spotting this!

If is a clear case where adding a `cast` can mask what is obviously a `typo`. Of course it shows up now because in 64-but systems a pointer (ctmbstr) is 64-bits, while on most systems a uint will be 32-bits only.

Looking back in history, this `cast` is there in the 2009 cvs source, so was inherited by this htacg repo way back. Sooo it has been waiting for a long time for someone to spot it.

If you get a chance, pull the latest 5.1.24 and re-test... and maybe close this... thanks

**Comment by benkasminbullock** [comment]
I have tested against 496c81c48d540f7f9ddf485cceef9443c8c7ad08 with the following:

https://gist.github.com/benkasminbullock/a57de76e7a294371afd6

Please feel free to incorporate this if you want to. I confirmed that it is working. I note that the default strings for options may be `NULL` according to these results.

The above file's output is in the [TAP](https://en.wikipedia.org/wiki/Test_Anything_Protocol) format.

**Comment by geoffmcl** [comment]
@benkasminbullock have added it to my [repo](https://github.com/geoffmcl/tidy-test) of tidy test apps... thanks...
