### ISSUE TITLE
prvTidyParseNamespace: Assertion `parent->tag != node->tag' failed.

### ISSUE THREAD

**Issue by tspivey** [htacg/tidy-html5#308]
Tidy, latest master.
I get an assertion failure when tidying [this article](http://www.buzzfeed.com/nicolasmedinamora/did-the-fbi-transform-this-teenager-into-a-terrorist).
I've pared it down to this simple test case:
```
tyler@ubuntu:~$ echo "<svg><defs></g>" | tidy
line 1 column 1 - Warning: missing <!DOCTYPE> declaration
line 1 column 1 - Warning: inserting implicit <body>
line 1 column 6 - Warning: replacing unexpected g by </g>
line 1 column 12 - Warning: discarding unexpected </g>
tidy: /home/tyler/tidy-html5/src/parser.c:1558: prvTidyParseNamespace: Assertion `parent->tag != node->tag' failed.
Aborted
```

**Comment by geoffmcl** [comment]
@tspivey thanks for narrowing this down to a very simple case, and yes I can repeat it in windows.

This seems a very nasty **bug**!

Will look at it soonest, unless you or someone else beats me to it with a PR or a patch.

**Comment by CMB** [comment]
So the real issue with the original page is that the parser gets
confused.  Sometimes the author used &lt;path&gt; &lt;/path&gt;,
sometimes they used &lt;path /&gt;, and
in some instances, they closed the tag twice, like so:
&lt;path /&gt; &lt;/path&gt;

Here's another small representative sample:
http://the-brannons.com/issue308html.html

**Comment by geoffmcl** [comment]
@CMD Thanks Chris for the second small sample... and like the first this also triggers the same  **assert**!

I have looked a little using Tyler's simple "<svg><defs></g>" sample, and at the moment of the assert the node is of course the `</g>` end tag, but the parent is of course the `<defs>` tag, so we have an assert! They are not the same, but **why should they be**.

So what I can **NOT** figure out is what is the reason for having this assert at all! At this point it seems that particular assert could just be **removed** and there would be no problem, as it is when you compile the `Release` configuration.

Even the first of the two warnings, here in ParseNamespace, does not make good sense -

 1. line 1 column 6 - line 1 column 6 - Warning: replacing unexpected g by `</g>`
 2. line 1 column 12 - line 1 column 12 - Warning: discarding unexpected `</g>`

Further, the second warning DISCARDING_UNEXPECTED is not acted on, in that I can not see the node is freed, and that first warning NON_MATCHING_ENDTAG, is used 4 times in parser.c, and in none of the other cases have such an assert. And simply tidy is **not** replacing an unexpected g by `</g>`.

This first warning is for things like `<b>bold<b>`, where tidy assumes the second `<b>` is just a user typo, and replaces it with a `</b>`...

There is another clear case in ParseInline, which separates the 2 warnings, and makes good sense -

```
    if ( node->tag == element->tag )
    {
        TY_(ReportError)(doc, element, node, NON_MATCHING_ENDTAG );
        TY_(FreeNode)( doc, node);
    }
    else
    {
        TY_(ReportError)(doc, element, node, MISSING_ENDTAG_BEFORE );
        TY_(UngetToken)( doc );
    }
```

Note, this is one warning or the other, not together, depending on whether the tags are equal, or not...

I need to think more about this... as usual, when in doubt, I do nothing!!!

But meantime can I suggest you use the option `-DCMAKE_BUILD_TYPE=Release` when building libtidy, so that there are no asserts...

And would appreciate any other comments on what is **the best thing to do here** for the Debug version, and to fix what looks like a mess...

**Comment by geoffmcl** [comment]
@tspivey, @CMD, Ok, also tried the second case, and it seems the same things...

So rather than do nothing have pushed the following patch to a `issue-308` branch for testing...

```
diff --git a/src/parser.c b/src/parser.c
index 583b2ef..19ecf54 100644
--- a/src/parser.c
+++ b/src/parser.c
@@ -1587,10 +1587,11 @@ void TY_(ParseNamespace)(TidyDocImpl* doc, Node *basenode, GetTokenMode mode)
 			else
 			{
 				/* unmatched close tag: report an error and discard */
-				TY_(ReportError)(doc, parent, node, NON_MATCHING_ENDTAG);
+				/* TY_(ReportError)(doc, parent, node, NON_MATCHING_ENDTAG); Issue #308 - Seems wrong warning! */
 				TY_(ReportError)(doc, parent, node, DISCARDING_UNEXPECTED);
 				assert(parent);
-				assert(parent->tag != node->tag);
+				/* assert(parent->tag != node->tag); Issue #308 - Seems would always be true! */
+                TY_(FreeNode)( doc, node); /* Issue #308 - Discard unexpected end tag memory */
 			}
 		}
 		else if (node->type == StartTag)
```

As can be seen have decided -

 1. the NON_MATCHING_ENDTAG seems the wrong warning here!
 2. removed the assert which seems would just about always be true
 3. and freed the discarded tag, to free the memory.
 
Appreciated if you get a chance to checkout this branch `issue-308` and test... thanks...

**Comment by CMB** [comment]
@geoffmcl Works well for me, thank you.

**Comment by geoffmcl** [comment]
@tspivey, @CMD, now merged `issue-308` branch to `master` and will get around to deleting it... bumped version to 5.1.32

Hopefully can close this as `fixed`... but feel free to re-open or open a new issue...
