### ISSUE TITLE
Latest 5.1.14 binary overwritten by old package in Ubuntu repository.

### ISSUE THREAD

**Issue by Janghou** [htacg/tidy-html5#309]
Downloaded the latest tidy-5.1.14-64bit.deb for Ubuntu 14.04 LTS, and installed it after removing old tidy
http://www.htacg.org/binaries/.

But now the old packages in the default repository  wants to overwrite the new tidy-html5 package for a security update:
    `Changes for tidy versions:
    Installed version: 5.1.14
    Available version: 20091223cvs-1.2ubuntu1.1`

What's the cause: a version number/dates needs bumping in the binary?

**Comment by geoffmcl** [comment]
@Janghou yes I can see the problem, but how to fix it?

If seems a version `20091223cvs-1.2ubuntu1.1` is for some reason considered later than `5.1.14`!

Need **help** for a unix/linux guru. How do we make `5.1.14` appear to be the latest, and greatest, which it is?

**Comment by Janghou** [comment]
Doesn't that makes sense? (20091223 > 5.1.14)
Name the version 20151116 and the problem is gone IMHO

I fixed it locally. I did build a deb myself locally, after downloading source, etc. 
...
- cmake ../.. -DCMAKE_INSTALL_PREFIX=/usr/
- make
- (sudo) checkinstall 

In the last step I bumped the version number to 20151118.
That way a deb package is created that I installed after removing the old one. Now update warnings are gone.

Dunno why old package in debian repository has a date version number, but that seems to be the knack here.

**Comment by geoffmcl** [comment]
@Janghou glad you found a solution... generate your own deb using a higher version number! Ingenious...

> Probably: (20091223 > 5.1.14)

Well, simply back in that epoc that was the distribution versioning used by the then maintainers. As far as I am aware none of those individuals are presently active in tidy development, although would welcome them back...

So I do not think we, htacg, should consider going back to using that `date` versioning, just to remove an `update` warning, but that is a possibility... and this is **tidy**, we are **tidy**, so that name has to stay. It is meant to replace the old with the new...

Of course what I hope is the Ubuntu distribution, all debian repositories, etc, are updated to the latest tidy, using the current versioning, some time soon... elsewhere we have some discussion on how to help distributions easily update. I hope that is being worked on too... read some things like `proper` tagging, but need some **help** to get this right!

Anything you can do, like filing say a ubuntu distribution [bug](https://launchpad.net/ubuntu/+filebug/?no-redirect)!, which it sort of is, would be most appreciated.

**Comment by Janghou** [comment]
At the moment I think `tidy-html5` should be considered a fork, so naming it `tidy-html5` would make sense.

And it will solve the package issue immediately, the deb has nearly no use now.

Once `tidy-html5` is recognized as an official update for tidy, the branches can be merged. 

Remember naming the package tidy-html5 has no influence on the binary, to execute it's still: `tidy` 
I named my local build package tidy-html5, and it works fine. 

Also the original tidy (some libraries), could be compiled into PHP, is that possible with the new updated one?

Maybe this can help:
https://www.debian.org/doc/manuals/distribute-deb/distribute-deb.html

**Comment by geoffmcl** [comment]
@Janghou well at this time this **is** canonical tidy, as that [655200](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=655200) bug notes at the bottom. 

See the tidy [history](http://www.html-tidy.org/#history) page for the timeline...

There was a time when we did consider a split to handle legacy html4--, and modern html5++, but now modern htacg tidy handles **BOTH** without problems, so we tossed the `5`, and kept both the package and binary names of `tidy`. There is only **one** tidy!

I have been working with tidy since 2006/7, and am a developer on the SF CVS site, and with this [HTACG](http://www.htacg.org/) group. All development on the SF site ceased around 2009, and we hope to get around to updating that web site, and deciding what to do about that old CVS source **soon**!

Thank you for the [question](https://answers.launchpad.net/ubuntu/+question/274893) and you seems to have a solution that worked for you, but not at all sure if this means the debian repo will be updated?

Concerning PHP, yes @skynet has successfully compiled tidy with PHP - see #190, and others...

Coincidently I think we should be considering a new tidy release around mid-december 2015. The last 5.0.0 was in June. The current `master` is at 5.1.24 with lots of fixes and features... very `stable`...

And that would certainly be the time to make a concerted effort to get tidy distributed and into repos, etc... so thanks for the [link](https://www.debian.org/doc/manuals/distribute-deb/distribute-deb.html)... we alreayd have the package building built into CMakeLists.txt...

**Comment by Janghou** [comment]
No I don't have a future proof solution, Ubuntu is Debian based so the point is to get this package into Debian. I have no idea how to quicken that procedure, so I just asked around.

The only thing I solved was creating a deb package that is not immediately overwritten, like the package that is now offered for download: either  the version number has to be bumped or the package has to be forked for now.

**Comment by geoffmcl** [comment]
@Janghou thanks for your help on this one...

I am sure you now understand why we do not want to `break` our current, more or less [Semantic](http://semver.org/), versioning system, just to avoid a warning about a very old distribution.

But can you document exactly what you did, just in case others run into this ugly `overwrite` problem!

Was it simply that you **altered** the `version.txt` file prior do doing `$ make package`, or `$ [sudo] make install`? or was it more complicated than that? 

As a separate question why do you use `$ [sudo] checkinstall`? The Makefile generated by cmake already has **both** `install` and `package` targets... Or does `checkinstall` do more, or something different?  Have never used it...

But if it was just the `version.txt`, you changed it to what exactly? It looks like you just changed the first line to `20151118`. Was that it? If it was more complicated can you describe the steps.

Just to document this so even I can understand ;=))

And we will continue to try to work with distros... you may have noted I re-opened #120 for this purpose...

Thanks again...

**Comment by Janghou** [comment]
They're probably several ways to generate a `deb` package. I used [checkinstall](http://manpages.ubuntu.com/manpages/wily/man8/checkinstall.8.html) somewhere in the past, so I used it this time again. Just to try out, I did not change anything.

Like written above, I ran `checkinstall` after make. 

And created a default, ./doc-pak directory. Then I filled out some fields, to circumvent the `overwrite issue I renamed the package to tidy-html5 and the version to the date 20151116, one of the former should be enough, though

    apt-cache show tidy-html5

    Package: tidy-html5
    Status: install ok installed
    Priority: extra
    Section: tidy-html5
    Installed-Size: 2168
    Maintainer: xxx@xxxx
    Architecture: amd64
    Version: 20151119-1
    Provides: tidy-html5
    Description: tidy-HTML5
    Description-md5: xxxxxxxxxxxxxxxxxxxxxx

Be aware that although the package is called tidy-html5, the binary is `tidy`:
   
    tidy --version
    HTML Tidy for Linux version 5.1.24

I'm not sure that `checkinstall`  is the way to go.
>  just to avoid a warning about a very old distribution.

Maybe old, but I'm afraid the original `tidy` is still the actual distribution of tidy. 

Probably changing first line of  `version.txt` to 20151118 will help to. Have'n tried that.

**Comment by geoffmcl** [comment]
@Janghou thanks for explaining what you did... not sure I undestood exactly, but hopefully it will help others who run into this problem...

As replied on https://bugs.launchpad.net/ubuntu/+source/tidy/+bug/1029209 
we are doing our best to get this issue fully resolved...

And have an outstanding [question](https://answers.launchpad.net/ubuntu/+source/tidy/+question/276623) on the issue.

Hopefully soon...

**Comment by balthisar** [comment]
@Janghou, I came across this. I know I'm late to the party, but does this help:

http://askubuntu.com/questions/441879/why-do-some-packages-have-extra-numbers-on-the-front-of-their-version-string

Adding an epoch to the deb should override the old date-based version, which has implied epoch 0.

I'm not sure how we generate deb packages in CMake yet. I'll add this to my to-do list. It may be as simple as `set(CPACK_PACKAGE_VERSION "$1:{LIBTIDY_VERSION}")`, but seeing that CMake doesn't seem to directly support a `CPACK_PACKAGE_VERSION_EPOCH` or similar, I'm not sure. I'll have to try to come up with something this weekend.

**Comment by behnam** [comment]
Epoc is the right way of handling this in this case, as @balthisar pointed out. Could you please just set that and build a new binary?

**Comment by geoffmcl** [comment]
@behnam yes, it seems for package distribution repos, that is the way to make sure an update is later than the previous, by adding an epoch...

Maybe @balthisar will be more successful than I in doing something like that to the binaries we post to on our  [site](http://binaries.html-tidy.org/), but as he suggests, maybe the CMake/CPack we use to build the binaries does not easily support this. And why would we add an epoch anyway?

And @Janghou has documented how he was able to proceed...

I think the packages built by maintainers of say the Ubuntu, Debian, etc distros are built from source using more 'traditional' package building processes, and they **can** add that epoch, if it is needed, to ensure a package will be seen as later, even though it has what appears to be a lesser release version than they have already released.

Now we **are** working hard to get **`Tidy`** updated in the various repos! See #324, https://answers.launchpad.net/ubuntu/+source/tidy/+question/276623 and https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=655200... Anything you can do to nudge this process along would be **much** appreciated... thanks... 

But as indicated I am not sure we could, or should! begin adding an `epoch` to our binary distributions... And now that we have #324 open directly addressing this will close this...
