### ISSUE TITLE
Inserting then trimming doubled message

### ISSUE THREAD

**Issue by benkasminbullock** [htacg/tidy-html5#315]
At revision 496c81c48d540f7f9ddf485cceef9443c8c7ad08, the following input:

    <p>
    This
    <pre>
    end
    </pre>
    </p>
    
run with 

    ./tidy --show-body-only yes --quiet yes ~/moo.html

outputs the following messages:

    line 6 column 1 - Warning: inserting implicit <p>
    line 6 column 1 - Warning: trimming empty <p>
    <p>This</p>
    <pre>
    end
    </pre>

It seems odd that the parser first decides to insert a &lt;p&gt; then decides to delete it rather than just deleting the empty &lt;/p&gt; with no content before it. Would an "unexpected &lt;/p&gt;" here not be a better warning?

**Comment by geoffmcl** [comment]
@benkasminbullock like #314 thought at first these warnings may seem a little odd...

But there is an option to not trim empty elements, `--drop-empty-paras no`, which will keep an empty `<p></p>` para after the `</pre>`, thus no second warning...

So at the moment can not see a `better` solution here... but suggestions welcome...

**Alternatively**, as I think you are implying, the behaviour of tidy could be changed to choose to drop an unexpected `</p>`, especially when there is going to be no content before it, with an appropriate warning. Perhaps this makes more sense that inserting an implicit `<p>`? Not sure! Would need to think and experiment...

This has been the tidy behaviour since some time before the last CVS 2009 release. And interestingly tidy2000 would default to replacing the `</p>` with a `<br>`. There is still a `--coerce-endtags yes` option, which coerces `<b>bar<b>` to `<b>bar<\b>`, but it does not seem to affect this p/pre sample case...

So that is a **feature** change, which are always up for discussion...

Comments, PR, patches welcome...

**Comment by geoffmcl** [comment]
No further comment since Nov, so closing this for now...

Please feel free to re-open, and raise another issue... thanks...

**Comment by benkasminbullock** [comment]
We're supposed to comment repeatedly on unclosed bugs?

**Comment by Garrett-R** [comment]
Is a `pre` tag inside a `p` tag legal HTML?

I put the following into [w3's validator](https://validator.w3.org/nu/#textarea):
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Test</title>
</head>

<body>
<p>
    <pre></pre>
</p>
</body>
</html>
```

And here was the result, saying this is not legal HTML:

![image](https://user-images.githubusercontent.com/6614695/128106800-6cb66a8d-77f8-416b-b950-3b26d8e37e78.png)
