### ISSUE TITLE
tidy-html5 produces additional tags

### ISSUE THREAD

**Issue by mindnektar** [htacg/tidy-html5#33]
Minimal example: Out of

``` html
<span><a href="/">Test</a></span>
```

you get

``` html
<span><a href="/"><span>Test</span></a></span>
```

I'd like Tidy not to produce surplus tags--so pretty much the behaviour from the html4 version. I didn't manage to find anything helpful on http://w3c.github.com/tidy-html5/quickref.html
Is there anything I overlooked?

Thanks
Martin

**Comment by jznf** [comment]
@sideshowbarker 
I guess this issue should be reopened since it's not fixed yet even after years.

I've tried version 5.2.0 from http://binaries.html-tidy.org/ on OSX and latest Debian, the behaviour is the same:

`<!DOCTYPE html>
<html>
    <head>
        <title></title>
    </head>
    <body>
        <span><button>OK</button></span>
    </body>
</html>`

results in 

`<!DOCTYPE html>
<html>
    <head>
        <meta content="HTML Tidy for HTML5 for Mac OS X version 5.2.0" name="generator">
        <title></title>
    </head>
    <body>
        <span><button><span>OK</span></button></span>
    </body>
</html>`

options set are:

`'indent-attributes': 0,
'wrap-attributes': 0,
'tidy-mark': 1,
'drop-empty-elements': 0,
'preserve-entities': 1,
'indent': 1,
'indent-spaces': 4,
'hide-comments': 1,
'doctype': 'html5',
'sort-attributes': 'alpha',
'split': 1,
'merge-divs': 0,
'merge-spans': 0,`

used via pytidylib6==0.2.2 but behaves the same when used directly with default settings.

**Comment by geoffmcl** [comment]
@jznf thanks for the report...

You have certainly found a case where tidy, since sometime before 2009, will propagate the `<span>` to inside the `<button>` block, thus producing `additional` tags...

But as @sideshowbarker reported way back then, this does **not** happen in the original minimal html sample given, by @mindnektar, so this is a **new** case, thus would prefer we open a `new` Feature Request issue for this... thanks...

I call it a `Feature Request` since this propagation in certain circumstances has been tidy's action for maybe upwards of 10 years. That is, it is deliberate coded behavior, so is not a **bug**, per se... We would need to explore why this was chosen... why was it thought needed? ie what case or cases did it fix along the way? And maybe we would need a `new` tidy option to now stop doing this... all of this points to this being a `new` issue... that needs its own discussion... thanks...

**Comment by jznf** [comment]
Ok, thanks. I've opened #461
