### ISSUE TITLE
tidy-html5 inserts duplicate meta name generator

### ISSUE THREAD

**Issue by ncouture** [htacg/tidy-html5#353]
When parsing files who were previously parsed by tidy-html5 with the tidy-mark option enabled (which is the default), the <meta name="generator"> tags inserted by tidy-html5 are inserted again, resulting in duplicate meta name generator tags.

### reproduction
```bash
file="eggs.html"
while [[ $(tidy -m "$file" 2> /dev/null) != 0 ]]; do
    grep 'meta name="generator' "$file" | wc -l
done
```

output:
```ascii
1
2
3
4
5
6
7
8
9
10
11
12
[ ... ]
```

**Comment by geoffmcl** [comment]
@ncouture sorry seem unable to repeat this problem!

What version of tidy are you using? `$ tidy -v` I was using 5.1.32... but repeated it using an old 4.9.35 I have with the same result... so I do not think it is version related...

I just get an **endless** list of 1's!!!

Further the bash testing seems faulty! If I read the intent correctly the `while` should be repeated until the tidy exit value is 0. Well that should only be once, since tidy should find no warnings on the second run on the tidied file? So why do I get an endless list of 1's? But I am no `bash` expert...

I also tried a simpler -

```bash
#!/bin/bash
#< test-353.sh - 20160124
BN=`basename $0`
TMPFIL="temp.html"
TMPEXE="tidy"
if [ -f "$TMPFIL" ]; then
    rm -v $TMPFIL
fi
touch $TMPFIL
$TMPEXE -v
echo "$BN: Doing 4 tests..."
$TMPEXE -m $TMPFIL 2> /dev/null
echo "$BN: First exit value '$?'"
grep 'meta name="generator' "$TMPFIL" | wc -l
$TMPEXE -m $TMPFIL 2> /dev/null
grep 'meta name="generator' "$TMPFIL" | wc -l
$TMPEXE -m $TMPFIL 2> /dev/null
grep 'meta name="generator' "$TMPFIL" | wc -l
$TMPEXE -m $TMPFIL 2> /dev/null
grep 'meta name="generator' "$TMPFIL" | wc -l
echo "$BN: Last exit value '$?'"
cat $TMPFIL
# eof
```

where only the first shows an exit value of `1`, and the last `0`... and the file only contained 1 meta...

Please carefully check again, and advise.

**Comment by ncouture** [comment]
The problem seems to be in a modification I have brought to the code -- I am unable to reproduce with the master branch.

```diff
diff --git a/console/tidy.c b/console/tidy.c
index bb9e823..038eb9a 100644
--- a/console/tidy.c
+++ b/console/tidy.c
@@ -964,8 +964,7 @@ static void optionvalues( TidyDoc tdoc )
 static void version( void )
 {
 #ifdef PLATFORM_NAME
-    printf( "HTML Tidy for %s version %s\n",
-             PLATFORM_NAME, tidyLibraryVersion() );
+    printf( "My generator name\n");
 #else
     printf( "HTML Tidy version %s\n", tidyLibraryVersion() );
 #endif
diff --git a/src/lexer.c b/src/lexer.c
index ace9452..3bab81d 100644
--- a/src/lexer.c
+++ b/src/lexer.c
@@ -1544,12 +1544,7 @@ Bool TY_(AddGenerator)( TidyDocImpl* doc )
     
     if (head)
     {
-#ifdef PLATFORM_NAME
-        TY_(tmbsnprintf)(buf, sizeof(buf), "HTML Tidy for HTML5 for "PLATFORM_NAME" version %s",
-                         tidyLibraryVersion());
-#else
-        TY_(tmbsnprintf)(buf, sizeof(buf), "HTML Tidy for HTML5 version %s", tidyLibraryVersion());
-#endif
+        TY_(tmbsnprintf)(buf, sizeof(buf), "My generator name");
 
         for ( node = head->content; node; node = node->next )
         {
```
