### ISSUE TITLE
Publish tidy-html5 to a Debian repo

### ISSUE THREAD

**Issue by mcandre** [htacg/tidy-html5#354]

**Comment by geoffmcl** [comment]
@mcandre as some background I would add -

Both I and @balthisar have added to an old bug report - https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=655200#70

Maybe a current Debian user could file a **new** bug? Add their voice to ours...

For Ubuntu I am holding open a question - https://answers.launchpad.net/ubuntu/+source/tidy/+question/276623 - Maybe other Ubuntu users could add to this, or add something new?

As first I thought it may be the holiday season that delayed things, but we are now nearly at the end of January 2016 and still no results!!!

It is really ugly that the tidy offered is a 2009 cvs source release... or have I missed something here?

**What else can we do?**

**Comment by geoffmcl** [comment]
Hi Manfred,

Re: Update HTML Tidy package

Thank you for help searching around for a solution to this... you
are a great help...

In fact your search link leads to an email from Jason, clearly
saying he no longer has time to maintain HTML Tidy, dated 2011-06-01
01:05:31 GMT
http://article.gmane.org/gmane.linux.debian.devel.general/162695/match=

So am also sending this to the MIA team -

Dear MIA Team,

Hi, I hope you can help HTML Tidy.

Back in 2011-06-01 Jason advised he no longer has time to maintain
HTML Tidy. Manfred's search reveals his last action was in 2013 -
http://search.gmane.org/?query=&author=Jason+Thomas&group=gmane.linux.debian.*&sort=date

I do not know your process in choosing a new maintainer, but note
for example that Daniel offers his help, twice -
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=655200#65
and
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=770129#20

Hope you can help get HTML Tidy updated, when you get a chance.

Last release: https://github.com/htacg/tidy-html5/releases/tag/5.1.25

Regards,
Geoff.

**Comment by geoffmcl** [comment]
On Mon, Jan 25, 2016 at 05:38:37PM +0100, Geoff McLane wrote:
> Hi Manfred,
> 
> Re: Update HTML Tidy package
> 
> Thank you for help searching around for a solution to this... you
> are a great help...
> 
> In fact your search link leads to an email from Jason, clearly
> saying he no longer has time to maintain HTML Tidy, dated 2011-06-01
> 01:05:31 GMT
> http://article.gmane.org/gmane.linux.debian.devel.general/162695/match=
> 
> So am also sending this to the MIA team -
> 
> Dear MIA Team,
> 
> Hi, I hope you can help HTML Tidy.
> 
> Back in 2011-06-01 Jason advised he no longer has time to maintain
> HTML Tidy. Manfred's search reveals his last action was in 2013 -
> http://search.gmane.org/?query=&author=Jason+Thomas&group=gmane.linux.debian.*&sort=date
> 
> I do not know your process in choosing a new maintainer, but note
> for example that Daniel offers his help, twice -
> https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=655200#65
> and
> https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=770129#20
> 
> Hope you can help get HTML Tidy updated, when you get a chance.

The MIA team doesn't "choose" a new maintainer, the most it can do is
orphaning a package, and usually that's a really lenghty process.

Whoever wants to adopt (and *maintain*) it, I think he should feel free
to do so, given the maintainer words in
https://lists.debian.org/1306890331.558.1.camel@localhost (linked by you
above).
If he is not a Debian developer, that's not really a problem, just find
a DD willing to sponsor such update, or otherwise send a RFS (request
for sponsorship), as usual.

-- 
regards,
                        Mattia Rizzolo

GPG Key: 66AE 2B4A FCCF 3F52 DA18  4D18 4B04 3FCD B944 4540      .''`.
more about me:  http://mapreri.org                              : :'  :
Launchpad user: https://launchpad.net/~mapreri                  `. `'`
Debian QA page: https://qa.debian.org/developer.php?login=mattia  `-

**Comment by geoffmcl** [comment]
Hi Mattia, hi Jason,

> Whoever wants to adopt (and *maintain*) it, I think he should feel free
> to do so, given the maintainer words in
> https://lists.debian.org/1306890331.558.1.camel@localhost

I'm willing to adopt the tidy package, and would suggest it for
collab-maint, as I am not a Debian Developer:

https://wiki.debian.org/Teams/CollabMaint

Cheers!

Daniel

**Comment by geoffmcl** [comment]
I am holding my [question](https://answers.launchpad.net/ubuntu/+source/tidy/+question/276623) open... 

Daniel has offered to adopt tidy package maintenance, but things seem to be moving very slowly... if at all..

Anything **anybody** can do to move this along would be much appreciated... 

Specifically, could any Debian or Ubuntu developers, who are familiar with Tidy, please **HELP**!

**Comment by geoffmcl** [comment]
Just posted this on my [question](https://answers.launchpad.net/ubuntu/+source/tidy/+question/276623) to keep it open... 

```
*** HELP *** HELP *** HELP ***

Does **nobody** care that Ubuntu still offers a 2009 package of Tidy?

When 2015 releases are available - https://github.com/htacg/tidy-html5/releases - and we are moving towards the next...

Has Daniel's offer to take over orphaned Tidy been accepted? Being worked on? Any indication when this might happen?

As repeated, repeated, is there anything I can do as a Tidy maintainer to assist?

Somebody please HELP!
```

**Can anybody HELP with this?**

**Comment by geoffmcl** [comment]
Since we are considering a release 5.2 shortly, changing the milestone on this to **indefinite**!

**Comment by geoffmcl** [comment]
Cross posted on [question](https://answers.launchpad.net/ubuntu/+source/tidy/+question/276623)...
Hi Daniel,

As can be seen here - https://github.com/htacg/html-tidy.org.binaries/issues/1 - I
am trying to script a DEB build... one that passes `lintian`... I seem to have 
narrowed it down to a few remaining issues...

Maybe you could help with this? Then when/if you take over orphaned Tidy 
distribution, the ground work would have been done...

Or maybe you or others could point me to some good tutorials on building 
an acceptable DEB... thanks...

Geoff.

**Comment by geoffmcl** [comment]
@mcandre - **Wow**, this feels like a break-through!

Check out https://github.com/danielhjames/tidy-packaging 

Can others **help** Daniel, me, and Tidy with this? Thanks...

I am still learning Debian packaging, but understand a test can be done with -

````
$ dpkg-buildpackage -S -uc -us
$ pbuilder-dist sid amd64 build tidy_20160404-1.dsc
````

All help very much appreciated...

**Comment by danielhjames** [comment]
Hi @geoffmcl @mcandre 

pbuilder-dist takes quite a lot of setup and you may not need it. It is only necessary to use pbuilder-dist for a clean chroot build, like when making packages for distribution.

All you really need for a local test is the orig.tar.gz and the debian directory from the above git repo.

You can omit the -S option on dpkg-buildpackage (which means create a source package only) and you will get installable .deb packages built for the host distro.

**Comment by geoffmcl** [comment]
See #406 for a DEB build problem... Maybe you can help...

**Comment by danielhjames** [comment]
tidy-html5 is now in the New queue for acceptance into Debian: https://ftp-master.debian.org/new.html

**Comment by geoffmcl** [comment]
As @danielhjames points out, some **massive** steps forward ;=))
 
 http://anonscm.debian.org/cgit/collab-maint/tidy.git/

Thank you! Read all about it -

On 08/06/16 15:28, Ludovic Rousseau wrote:
> Hello,
>
> Packaging for version 5.2.0 is available at http://anonscm.debian.org/cgit/collab-maint/tidy.git/
>
> Daniel, thanks for your work.
> Use gbp to build the package push commit to the collab-maint project.
> If you can't push your commits to git.alioth.org just send them to me (or create a github clone so I can get them from there).
>
> I also uploaded this new version to Debian. The package should be available soon in unstable.
>
> tidy is back up to date in Debian. :-)
>
> Bye
>

**AND**

On 08/06/16 15:37, Ludovic Rousseau wrote:
> One .deb is new and so require manual review. The delay is generally a few days.
>
> I just got this email:
>
> binary:libtidy5 is NEW.
> source:tidy-html5 is NEW.
>
> Your package has been put into the NEW queue, which requires manual action
> from the ftpteam to process. The upload was otherwise valid (it had a good
> OpenPGP signature and file hashes are valid), so please be patient.
>
> Packages are routinely processed through to the archive, and do feel
> free to browse the NEW queue[1].
>
> If there is an issue with the upload, you will receive an email from a
> member of the ftpteam.
>
> If you have any questions, you may reply to this email.
>
> [1]: https://ftp-master.debian.org/new.html
>

**AND**

On 08/06/16 16:29, Daniel James wrote:
> Hi Ludovic,
>
>> binary:libtidy5 is NEW.
>> source:tidy-html5 is NEW.
>
> Given the suffix number changes, it's only fair that the package be
> checked over again ;-)
>
> I've pushed a first commit to collab-maint for some non-urgent
> maintenance, just to check it works:
>
> http://anonscm.debian.org/cgit/collab-maint/tidy.git/commit/?id=9aa28147ef9bb83e9f89d4683ab6890656acd03b
>
> Thanks for setting this up!
>
> Daniel

**AND**

On 08/06/16 17:29, Ludovic Rousseau wrote:
> 2016-06-08 16:29 GMT+02:00 Daniel James <daniel@64studio.com>:
>
>     Hi Ludovic,
>
>     > binary:libtidy5 is NEW.
>     > source:tidy-html5 is NEW.
>
>     Given the suffix number changes, it's only fair that the package be
>     checked over again ;-)
>
>     I've pushed a first commit to collab-maint for some non-urgent
>     maintenance, just to check it works:
>
>     http://anonscm.debian.org/cgit/collab-maint/tidy.git/commit/?id=9aa28147ef9bb83e9f89d4683ab6890656acd03b
>
>
> It works.
> Now you only need me to upload a new version to Debian.
>
> Bye
>
> -- 
>  Dr. Ludovic Rousseau

; eof - ref: tidy-199-debian-build.txt

**Comment by AdamMajer** [comment]
> tidy-html5 is now in the New queue for acceptance into Debian:
> https://ftp-master.debian.org/new.html

Why not update current tidy? Why have new package?

Also, your binary package already exists in Sid, which means this
cannot be accepted. If you wish to use libtidy-dev, then that has to be
via current tidy package, not new one.

**Comment by danielhjames** [comment]
Hi Adam, this is an update of the current tidy package. The reason that the source package name changed is because it changed upstream, so it has to go into Debian's New queue. Also, the name of the libtidy package changed because the shared object filename now has a 5.x suffix, currently /usr/lib/libtidy.so.5.2.0. In the libtidy5 debian/control file we have...

Replaces: libtidy-0.99-0, libtidy0

**Comment by AdamMajer** [comment]
On Thu, 09 Jun 2016 03:06:48 -0700
Daniel James <notifications@github.com> wrote:

> Hi Adam, this is an update of the current tidy package. The reason
> that the source package name changed is because it changed upstream,
> so it has to go into Debian's New queue. Also, the name of the

It still would end up in New because you have different soname, so new
binaries. With package name conflict (libtidy-dev), I'm not sure how
this is going to go through the NEW queue.

I don't see request to remove old tidy.

New upstream is fine, but package is continuing. This is not a rewrite.
So I think that it should stay with the old package.


Also, tidy needs compatibility headers since they were renamed. So
currently stuff building with old tidy doesn't build with new tidy.
I'll provide a pull request for that soon.

> libtidy package changed because the shared object filename now has a
> 5.x suffix, currently /usr/lib/libtidy.so.5.2.0. In the libtidy5
> debian/control file we have...
> 
> Replaces: libtidy-0.99-0, libtidy0

That is wrong.

Your libtidy5 should not be replacing libtidy0. It should co-exist.
They have different sonames.

Also, that README.source is from old CVS? Shouldn't exist there (even
if you just update old package)

PS. I didn't look at the Debian package, just looking at what is
displayed in the New queue.

**Comment by danielhjames** [comment]
Hi Adam, thanks for the offer of help, do you use collab-maint?

I removed README.source as you are right, it is from the old package. Please see the last commit on http://anonscm.debian.org/cgit/collab-maint/tidy.git/

libtidy-0.99-0 had a Conflicts: on libtidy0 and I don't think libytidy0 has been in Debian since the year 2005 (according to the changelog) so I guess there is not much chance of libtidy5 and libtidy0 co-existing. Supposing we had libtidy5 co-existing with the also very old libtidy-0.99-0 (from the year 2009), wouldn't that mean having two versions of the same library, but only one supported upstream?

Also, I recall the libtidy-dev package provides a symlink for the library, wouldn't that conflict?

Cheers!

Daniel

**Comment by AdamMajer** [comment]
> Hi Adam, thanks for the offer of help, do you use collab-maint?

Yes, I do have access to collab-maint, but not from here. I can look at
the package this weekend (maybe?), but definitely this month.

FYI, currently tidy is in process of getting updated at SUSE. It's just
going through integration testing. I will send you some patches Soon :D


> libtidy-0.99-0 had a Conflicts: on libtidy0 and I don't think
> libytidy0 has been in Debian since the year 2005 (according to the
> changelog) so I guess there is not much chance of libtidy5 and
> libtidy0 co-existing. Supposing we had libtidy5 co-existing with the
> also very old libtidy-0.99-0 (from the year 2009), wouldn't that mean
> having two versions of the same library, but only one supported
> upstream?
> 
> Also, I recall the libtidy-dev package provides a symlink for the
> library, wouldn't that conflict?


No, devel provides symlink to the package it depends on, so something
like,

  libtidy.so -> libtidy.so.5

hence no problems having libtidy-0.99-0 and libtidy5 installed at same
time. They should provide different files.

Sometimes users have very old software that they can't
rebuild for whatever reason that uses old library. Hence why Conflicts:
for lib* packages are generally bad.

**Comment by geoffmcl** [comment]
@AdamMajer, @danielhjames, thanks for your comments... it is very good to read... we are certainly interested in `Publish tidy-html5 to a Debian repo`... some comments on what I read...

> Why not update current tidy? Why have new package?

As a tidy maintainer, **absolutely** agree.

````
 libtidy.so -> libtidy.so.5
````
 
Adding this link is exactly the upgrade of tidy that is required, requested, here - across every distribution... 

I have not asked my friends, the original SF maintainers, exactly why that last release 2009, was named: 0.99, but when the baton was passed on, to us, HTACG, we chose the first release name to be Tidy 5.0.0... but no API change! ... lots and lots of history in that...

Now, in building the Debian package, somewhere along the line I might have thought changing the base name would be ok for a Debian release... but fully agree, if it is possible, install and do the above link update... all is done...

Also agreed... no delete of the last... if an app has the direct link to `libtidy-0.99-0.so` then it will still run... but not sure when, how, ... to delete those???

The sample console app, `tidy`, as opposed to `libtidy`, is meant to always fully replace the old, and chooses to be linked to the matching static library... this should be a 100% overwrite...

Then any current app, linked to the generic `libtidy.so` will immediately benefits from the improved stability of the library... that is, an `upgrade` only...

So where does this go next?

Do we, as Tidy, wait for the **new** Debian name approval? I am sort of ok with that, if this gets tidy into distribution, after a much too long delay... 6-7 plus years...

Or, are there some simple debian build steps which will **keep** the preferred single name of **tidy**... ie no **new** approval is required...

Any help, ideas, you can provide would be **much** appreciated... thanks for the comments, and to @danielhjames for big efforts to get this moving... on a very important issue to us... getting the tidy update into distribution...

**Comment by AdamMajer** [comment]
On Sat, 11 Jun 2016 17:07:07 -0700 Geoff McLane
<notifications@github.com> wrote:

> I have not asked my friends, the original SF maintainers, exactly why
> that last release 2009, was named: 0.99, but when the baton was
> passed on, to us, HTACG, we chose the first release name to be Tidy
> 5.0.0... but no API change! ... lots and lots of history in that...

Good, because OpenSUSE has tidy5 as new tidy. Uploaded it last week. So
everything that currently builds with 0.99, is rebuilt with 5.

   https://build.opensuse.org/package/show/openSUSE:Factory/tidy


The only thing is, that you do have an ABI change hence you would have
had to bump the soname anyway. Now, let's hope you do not change the
ABI for a while!

  http://stackoverflow.com/questions/3784389/difference-between-api-and-abi

For example, when you added new enums, that is ABI change since you've
kept them alphabetical, which caused all the folloup enums to be
renumbered. Hence software is no longer compatible if linked with older
version.

ABI change require soname to be changed because software has to be
recompiled against new version of library to continue to function.

Anyway, this is probably old news to you.


> Now, in building the Debian package, somewhere along the line I might
> have thought changing the base name would be ok for a Debian
> release... but fully agree, if it is possible, install and do the
> above link update... all is done...
> 
> Also agreed... no delete of the last... if an app has the direct link
> to `libtidy-0.99-0.so` then it will still run... but not sure when,
> how, ... to delete those???

It just means user can install libtidy-0.99-0.so from archive
concurrently with the new tidy and everyone is happy.

When base tidy is updated, then this automatically triggers rebuilt
with new tidy (because of new soname). And old libpackage is
automatically dropped as it no longer builds from source.


> The sample console app, `tidy`, as opposed to `libtidy`, is meant to
> always fully replace the old, and chooses to be linked to the
> matching static library... this should be a 100% overwrite...

That is fine. The binary can change to have new features and all that.


> So where does this go next?
> 
> Do we, as Tidy, wait for the **new** Debian name approval? I am sort
> of ok with that, if this gets tidy into distribution, after a much
> too long delay... 6-7 plus years...
> 
> Or, are there some simple debian build steps which will **keep** the
> preferred single name of **tidy**... ie no **new** approval is
> required...
> 
> Any help, ideas, you can provide would be **much** appreciated...
> thanks for the comments, and to @danielhjames for big efforts to get
> this moving... on a very important issue to us... getting the tidy
> update into distribution...


Have you contacted current Debian tidy maintainer?

- Adam

**Comment by danielhjames** [comment]
Hi @AdamMajer, hi @geoffmcl, the official Debian tidy maintainer has not been active with this package for some years, which is why I offered to help prepare this new set of packages.

The symlink:
`libtidy.so -> libtidy.so.5`
is provided only in the new libtidy-dev package, for people building their own apps against Debian's package of libtidy5. This is because regular Debian packages should get rebuilt against the libtidy5 package, against the symlink libtidy.so.5

This symlink points to the actual installed library, which is libtidy.so.5.2.0 for this particular release.

The next step is that when the new package gets checked in Debian's NEW queue, it will either be accepted, or we will fix it up until it is accepted. This can take a while, but new uploads should be quicker after that.

Cheers!

Daniel

**Comment by AdamMajer** [comment]
Well, I've just contacted the Debian maintainer and he said he'll like to keep maintaining tidy and has updated the package to tidy5. He just can't upload it because his GPG key was removed (long story, but Debian had lots of GPG keys removed in the 1k to 2+k RSA keylength transition). I've told him I can upload his package on the weekend. And then Debian will have tidy5 too :+1:

**Comment by danielhjames** [comment]
Hi Adam, that's a good result, thanks. Will collab-maint be used in future?

**Comment by LudovicRousseau** [comment]
Hi @AdamMajer, I have not tried to contact the tidy maintainer Jason Thomas. His latest tidy upload was in Dec 2009. I guess his PGP key has been removed long after that date.

tidy looked abandoned. I am sorry if I made a mistake.

I am not sure it is a good idea to upload now a new version of tidy5. I would wait until the NEW package is handled.
Jason could join the effort and work on http://anonscm.debian.org/cgit/collab-maint/tidy.git/
I am happy to sponsor a new version from him (until he gets a new key in the keyring).

**Comment by AdamMajer** [comment]
On Tue, 14 Jun 2016 04:54:36 -0700
Ludovic Rousseau <notifications@github.com> wrote:

> Hi @AdamMajer, I have not tried to contact the tidy maintainer Jason
> Thomas. His latest tidy upload was in Dec 2009. I guess his PGP key
> has been removed long after that date.

Tidy didn't have upstream for a while too. There was little to upload.
But Jason is quite responsive via email. I've directed him to this
thread on GitHub. Hopefully you two can agree and co-maintain this
package in Debian.

But just to re-iterate,

  1. you need compat headers to keep current software compiling with
  new tidy
  2. tidy binary cannot be statically linked in Debian
  3. distributing documentation for tidy is also a good idea

> tidy looked abandoned. I am sorry if I made a mistake.

Always a good idea to email the current maintainer. It probably would
make tidy update much quicker :D

**Comment by danielhjames** [comment]
Hi @AdamMajer, we have been aware of https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=655200 since at least 2013. I emailed Jason via this bug report in March 2015 offering help, and he was emailed again by Geoff in January 2016, with no response. As a volunteer, I do appreciate that time is not always available to respond, so that's not a criticism.

Your assistance with compat headers would be very welcome, please take a look at http://anonscm.debian.org/cgit/collab-maint/tidy.git/

In my version of the package, the tidy binary is dynamically linked to libtidy.so.5 but the static version is also included for users that need it.

I dropped the tidy-doc package as the upstream source no longer seems to build any docs other than the man page, although there are some Markdown files in the README directory of the upstream source which could potentially be included in a new tidy-doc package. The man page was included in the new tidy package, of course.

**Comment by AdamMajer** [comment]
On Wed, 15 Jun 2016 02:25:25 -0700
Daniel James <notifications@github.com> wrote:

> Your assistance with compat headers would be very welcome, please
> take a look at http://anonscm.debian.org/cgit/collab-maint/tidy.git/

There is a pull request that adds these to tidy. Just include that
patch and install headers to /usr/include/tidy not /usr/include (like
old package) and it will work.

  https://github.com/htacg/tidy-html5/pull/420

> I dropped the tidy-doc package as the upstream source no longer seems
> to build any docs other than the man page, although there are some
> Markdown files in the README directory of the upstream source which
> could potentially be included in a new tidy-doc package. The man page
> was included in the new tidy package, of course.  

You have to basically merge subdirectory of tidy api in there as well,

   https://github.com/htacg/html-tidy.org.api

specifically, the `tidy-html5-doxygen` directory. Then you can build API
with Doxygen again via `build_docs.sh` - that may need to be slightly
modified for Debian too.

Personally, I think it was a mistake to move documentation generation
out of tidy source code and into documentation repository.

**Comment by danielhjames** [comment]
Hi @AdamMajer, thanks for the patch! I'll wait to hear if Jason is pushing his package update, or is willing to work with collab-maint, before pushing further changes. Thanks also for the explanation about what happened to the docs.

**Comment by LudovicRousseau** [comment]
tidy5 has been accepted in Debian with one comment:
"Please clarify the University of Toronto copyrights."

**Comment by danielhjames** [comment]
Thanks @LudovicRousseau I hope that the upstream developers could explain further about the copyright.

We have one serious bug https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=827716 which I somehow overlooked. I am away from my development machine this week but could fix it after that, it's a one-liner.

Also there are some bug tickets against the old package which could be tested and closed if someone would like to take a look at them: https://bugs.debian.org/cgi-bin/pkgreport.cgi?archive=0;ordering=normal;repeatmerged=0;src=tidy-html5

**Comment by jasonethomas** [comment]
Hi all, I am the missing Debian Developer, I've been busy for the last few years, working, getting married having kids. But things are getting less busy now and I'd like to continue maintaining tidy. I've already packages the current version and shared it with @AdamMajer, the link to my diff file is below.

I'll take a look at your packaging and see if I missed anything. My package is already lintian clean. We need to look at package names and versions.

https://www.dropbox.com/s/32lzjd8fqd8fo97/tidy_5.2.0-1.diff.gz?dl=0

**Comment by LudovicRousseau** [comment]
Hello @jasonethomas. Welcome back.

I think I/we made (a) mistake(s) with the upload of tidy. See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=828097 
I don't think we have something to do to help the library migration now.

**Comment by danielhjames** [comment]
Hi @jasonethomas good to see you on here! I would strongly recommend that you take a look at https://anonscm.debian.org/cgit/collab-maint/tidy.git/ as a lot of work has been done there already.

@LudovicRousseau there are of course some bugs flushed out by the new upload but the fixes seem straightforward. We can help with the library migration by fixing https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=827891 which I am working on today.

**Comment by danielhjames** [comment]
Hi @LudovicRousseau I have pushed a bunch of fixes to collab-maint today which fix the serious bugs on my test system. Please roll a 1:5.2.0-2 package when you are ready.

**Comment by LudovicRousseau** [comment]
@jasonethomas do you want to review+upload the new tidy version?
What is your plan regarding tidy packaging?

**Comment by LudovicRousseau** [comment]
Ondřej Surý already uploaded a new version of the package to fix  #827716 and #827891.
See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=827716

@danielhjames can you integrate the changes from 1:5.2.0-1.1 in the collab-maint project?

**Comment by LudovicRousseau** [comment]
Ondřej created a NEW git repository at http://anonscm.debian.org/cgit/collab-maint/tidy-html5.git/ :-(

We need to add the git repository in ``debian/control`` to avoid the same problem next time.
```
--- /tmp/FJjith_control 2016-06-28 21:29:00.951677084 +0200
+++ debian/control  2016-06-28 21:23:05.593448475 +0200
@@ -4,6 +4,8 @@ Priority: optional
 Maintainer: Daniel James <daniel@64studio.com>
 Build-Depends: debhelper (>= 9), libtool, xsltproc, dh-autoreconf, cmake
 Standards-Version: 3.9.8
+Vcs-Git: git://anonscm.debian.org/collab-maint/tidy.git
+Vcs-Browser: https://anonscm.debian.org/git/collab-maint/tidy.git
 Homepage: http://www.html-tidy.org/
 
 Package: tidy
```

I have not made the change to not add more complexity to the merge of Ondřej changes.

**Comment by danielhjames** [comment]
Hi @LudovicRousseau that seems like a reasonable solution since the git repo name now matches the source package. It's a pity that no-one emailed me before setting up a duplicate repo, but the important thing is that the new version of tidy is now in Debian and several people wish to help maintain it.

**Comment by jasonethomas** [comment]
Hi @danielhjames I just committed a couple of changes, to clean up and fix a bug.

**Comment by danielhjames** [comment]
Thanks @jasonethomas ! I had wanted to use the version of the man page built from the source, but could not figure out the path to it.

Other Debian Developers have set up a separate collab-maint project at http://anonscm.debian.org/cgit/collab-maint/tidy-html5.git/ which I'm also using now, so I will sync your changes there. Then to avoid confusion I think we should take the original project down.

Would you like to be listed as the Maintainer: in debian/control again?

**Comment by danielhjames** [comment]
Hi @jasonethomas I have prepared a 1:5.2.0-2 release in http://anonscm.debian.org/cgit/collab-maint/tidy-html5.git and changed the maintainer name/email back to yours in debian/control and debian/changelog. I'm happy to help with packaging via this collab-maint repo in future, should you need it.

**Comment by jasonethomas** [comment]
Hi @danieljames I believe a bunch of debian package use a collaborative
type address for the maintainer, I'd be happy to do the same and have them
go to anyone who wants in.  I really appreciate having all your help.

# grep Maintainer /var/lib/dpkg/available | grep Team | sort -u
# grep Maintainer /var/lib/dpkg/available | grep Maintainers | sort -u



It might also be nice to have a "Debian.CREDITS" or similiar for
recognition of those that help package tidy.

Couple of other things:
 - Do we want to look at including the docs again, or even packaging
separately, which from memory it use to be done this way.
 - Do we want to include these suggested by @adammajer,
https://github.com/htacg/tidy-html5/pull/420,
https://github.com/htacg/tidy-html5/pull/421


What do you all think?

**Comment by danielhjames** [comment]
Hi @jasonethomas I think it's better if an official Debian Developer is listed as Maintainer, as I'm unable to release updates without sponsorship. I can still contribute (like others) via collab-maint.

As for credits for packaging, one way to do this is to list maintainers in the debian/copyright file for Files: debian/*

The docs were moved to a separate git repo upstream, therefore if we wish to reinstate the tidy-doc package we might need a separate source package for it. This might be a good opportunity to rename it, as there is a name clash with a different project: http://savannah.nongnu.org/projects/tidydoc/

https://github.com/htacg/tidy-html5/pull/420 was already included in the package as a patch: http://anonscm.debian.org/cgit/collab-maint/tidy-html5.git/commit/?id=fa10ee7c30474ce103ccb23d7c327509dc121cea

I don't think https://github.com/htacg/tidy-html5/pull/421 is so relevant for packaging because we currently build tidy with the shared library anyway (I tested the /usr/bin/tidy binary to make sure), and we only provide the static library for special use cases.

In general, as upstream is very responsive, I would like to suggest all known fixes go there, and that we only patch while awaiting an upstream release. Otherwise we have the situation of long-term patches where Debian's tidy is diverging from the upstream release, which can make QA more difficult.

Cheers!

Daniel

**Comment by danielhjames** [comment]
Hi @geoffmcl I think this ticket could be closed now, we have a new official Debian package of 5.2.0 with lots of improvements from different people: http://metadata.ftp-master.debian.org/changelogs//main/t/tidy-html5/tidy-html5_5.2.0-2_changelog

Thanks to @jasonethomas, @AdamMajer, @LudovicRousseau, Steve Langasek, Pino Toscano, Mattia Rizzolo, Gianfranco Costamagna and Ondřej Surý!

**Comment by AdamMajer** [comment]
On 07/07/2016 11:34 AM, Daniel James wrote:
> Hi @jasonethomas <https://github.com/jasonethomas> I think it's better
> if an official Debian Developer is listed as Maintainer, as I'm unable
> to release updates without sponsorship. I can still contribute (like
> others) via collab-maint.

There is an Uploaders entry for more than one person.

https://www.debian.org/doc/debian-policy/ch-controlfields.html#s-f-Uploaders

Typically for group maintenance, you have a common mailing address, like 
a mailing list, for Maintainer: and maintainers for the package listed 
are listed in the Uploaders: field.

- Adam

**Comment by geoffmcl** [comment]
@mcandre, @AdamMajer, @LudovicRousseau, @jasonethomas, as @danielhjames points out, we try to deal with issues promptly, so if I have missed something, please point it out to me... open/re-open an [issue](https://github.com/htacg/tidy-html5/issues)... thanks...

But yes, it seems `Publish tidy-html5 to a Debian repo` has been achieved... a big **thanks to all**... so closing this here...

**Comment by zanona** [comment]
Any suggestions on how to upgrade if my system has the 2009 version?

```bash
sudo apt-get remove tidy
sudo apt-cache autoclean
sudo apt-get install tidy
```
still gives me the same outdated version :/

**Comment by LudovicRousseau** [comment]
You should upgrade your system to Debian stretch or Ubuntu 18.04LTS
https://packages.debian.org/search?keywords=tidy
https://packages.ubuntu.com/search?keywords=tidy

**Comment by zanona** [comment]
@LudovicRousseau thanks, I will try that instead.
