### ISSUE TITLE
Publish tidy-html5 to a yum repo

### ISSUE THREAD

**Issue by mcandre** [htacg/tidy-html5#355]

**Comment by balthisar** [comment]
@mcandre, can you provide a little help here? I see that we're available in [Fedora](https://apps.fedoraproject.org/packages/tidy), so presumably this request is satisfied?

Otherwise, is there a _particular_ YUM repository we should be looking into?

**Comment by geoffmcl** [comment]
@balthisar thanks for that [Fedora](https://apps.fedoraproject.org/packages/tidy) link. So nice to see it is up-to-date with release 5.4.0... thanks to @rdieter, and others, for that...

And then another I found [rpm=tidy](https://rpms.remirepo.net/rpmphp/zoom.php?rpm=tidy), which has our [html-tidy.org](http://www.html-tidy.org/) url, rather than the old sourceforge on the Fedora site...

In reading around a little, it seems **yum** is used for Fedora, CentOS, and Red Hat, but you can get very disappointed googling around with say `RHEL Tidy`, in that you stumble across **lots** of sites still showing the **ancient** `2009` release...

Anyway, @mcandre, as @balthisar asks, is there anything else we should be doing here? Or can this be closed? 

Of course understanding that this **publishing** will always be an ongoing battle, but one where we, as Tidy, can do little more directly than publish our releases... Thanks...

**Comment by balthisar** [comment]
Given lack of feedback, I'll close this. @mcandre, if you find your way back, we'll be happy to reopen this.
