### ISSUE TITLE
Publish tidy-html5 to Chocolatey

### ISSUE THREAD

**Issue by mcandre** [htacg/tidy-html5#357]

**Comment by geoffmcl** [comment]
@mcandre well I searched [Chocolatey](https://chocolatey.org/) for HTML Tidy, but it does not seem to exist! And maybe it should not exist there?

While I can see Chocolatey helping some user install `packages` like git, cmake, ImageMagick, MinGW, etc, etc... that is packages that have multiple dependent DLL's, and the install needs to be added to your existing PATH, I really can not see Chocolatey use for installing a single, standalone tidy.exe binary, which can be downloaded and copied to any folder in your PATH, or to a new folder added to your PATH...

Even if you wanted to develop an app using libtidy.dll (shared), or libtidys.lib (static), and thus need access to tidy's headers then again we are just talking about 5 or 6 files, which would be better copied to your project, rather than `installing` tidy somewhere...

You will note I no longer include a Windows NSIS nor MSI installer in our published [binaries](http://binaries.html-tidy.org/), as this is really of no use, and would probably cause confusion... What they installed was unreachable without further manual setup...

OTOH I have published a small repo [tidy-test](https://github.com/geoffmcl/tidy-test) which contains a `FindTidy.cmake` module, and some sample apps, which does link with such an `installed` tidy... as an example to dvelopers of how this can easily be done... And simularly a WIP [Tidy GUI2](https://github.com/geoffmcl/tidy-gui2) as another example...

Thus I do not see any benefit in `publishing` tidy to Chocolatey... but am open to comments...

So unless there is a use case, and a user who wants to do this, I am closing this for now... but thanks for the thought...
