### ISSUE TITLE
Cygwin and tidy5

### ISSUE THREAD

**Issue by jamesla** [htacg/tidy-html5#362]
Is tidy5 compatbile with Cygwin? Are there any installation instructions?

**Comment by balthisar** [comment]
@jamesla, you will require Cmake to build it, and there's no reason it shouldn't compile. Instructions are in the readme. If it _doesn't_ work, please let us know!

Of course the [binaries][http://binaries.html-tidy.org] will run on Windows with Cygwin. There's no installer; you simply put it where ever you want to on your %PATH% or $PATH.

**Comment by geoffmcl** [comment]
@jamesla just for **fun** I installed cygwin 2.873 (32-bit) in an old Windows XP box I have... which took ages for the default install...

Openned a Cygwin terminal, and cloned tidy into my `$HOME/projects/tidy-html5`... then changed directory to `tidy-html5/build/cmake` and ran `$ cmake ../.. -G "Unix Makefile"`... I needed to specifically add the `generator` since by default cmake found and wanted to use my installed MSVC8!

But this quickly showed me that I also needed to also install the **Devel** category to get gcc, et al, and noted that this also included cmake, and git, and **LOTS** of other things... again another long long install... and consumed many giga bytes of disk space... and some warning about usb0...

And you have to be careful some of the tools like `make.exe`, ... are not already in your PATH... as these may be used instead of the cygwin installed `/usr/local/bin:/usr/bin` tool set... causing very unusual errors...

But then the cmake succeeded in generating a `Makefile`, and I could run `$ make`, and tidy.exe got built... as well as tidy1.xsl, ..., a tidy.1 man page, libtidy.dll.a, and a strange cygtidy-5.dll??? etc...

Be aware the `tidy.exe` built will not run in other than the cygwin terminal, unless you make special provisions for finding the "embedded in everything built by cygwin" **cygwin1.dll**... one of the big reasons I do not like Cygwin... adds this proprietary DLL to everything... who know what it does???

And that dependency influences where you can install tidy.exe and run it... I did not try it, but in the cygwin terminal a `$ make install`  looks like it would copy the exe to `/usr/local/bin`, as in linux, unless you give cmake another install directory... and the headers to `/usr/local/include`... libs... etc...

But yes, a tidy build seems `compatible` with a cygwin build... advise if you have problems...

**Comment by geoffmcl** [comment]
As no further comments for two weeks, closing this for now...

Feel free to reopen, or post a new issue... thanks...

**Comment by jamesla** [comment]
Ok thanks guys
