### ISSUE TITLE
 Wrong indentations if hide-endtags: yes

### ISSUE THREAD

**Issue by OlafvdSpek** [htacg/tidy-html5#390]
Input:

````
<table width="100%">
<tr>
<td>
<td colspan=4 align=center>
Gemiddelde milieubelasting grondwater (mbp/ha)
</table>
````

[desired_output.txt](https://github.com/htacg/tidy-html5/files/199602/desired_output.txt)
[actual_output.txt](https://github.com/htacg/tidy-html5/files/199603/actual_output.txt)
[input.txt](https://github.com/htacg/tidy-html5/files/199601/input.txt)

https://sourceforge.net/p/tidy/bugs/563/

Edit: Need to add backchecks to show html

**Comment by geoffmcl** [comment]
@OlafvdSpek thanks for moving it here... will get to it soonest...

**Comment by geoffmcl** [comment]
Oops, need to also add a config -

````
// config for #390 - sf563
indent: yes
indent-spaces: 4
hide-endtags: yes
````

**Comment by geoffmcl** [comment]
@OlafvdSpek wow, that was a tough search!

The problem was the indent gets reset on a conditional flush... which would only reset the indent if there was something to flush!

When you add `--hide-endtags yes`, **or** `--omit-optional-tags yes`, then in certain cases no endtag is added to the pprint buffer, so the conditional flush had nothing to flush, so thus did not reset the indent...

I feel confident in this **fix** in that, it only effects the pprint output, not the document parsing, so have backed up the milestone to 5.2, and have included it in `master`.

To get to this I had to add a **lot** of DEBUG output, but this **only** exists in the MSVC Debug build, and only if you define some extra items, so it has no effect on the Release build.

Accordingly have bumped the version to 5.1.52...

Interestingly, this fix also triggers four **regression test** differences in html output, testbase 427820, 504206, 505770, and xml 1510101! 

But carefully reviewing the html, it looks **better**, in that some previous **bad** indents are also fixed! So will get around to updating those [tests](https://github.com/htacg/tidy-html5-tests) also...

Thanks for persisting with this... it only took about **12 years** to fix ;=))

If you get a chance, please pull the latest, and test... and if fixed, close... thanks...

**Comment by geoffmcl** [comment]
@OlafvdSpek have opened an [Issue #5](https://github.com/htacg/tidy-html5-tests/issues/5) to look after the fixing of the **tests**... so from my perspective this can be closed...

**Comment by OlafvdSpek** [comment]
Thx for fixing this!
