### ISSUE TITLE
VirusTotal reports Windows releases of 5.2.0 have VEX2662.Webshell trojan

### ISSUE THREAD

**Issue by markstinson** [htacg/tidy-html5#399]
It could be a false positive, but the VirusTotal reports Windows releases of 5.2.0 have VEX2662.Webshell trojan

**Comment by balthisar** [comment]
Did you get this from the binaries website, or from Github directly?

**Comment by markstinson** [comment]
I downloaded the release binaries right here on Github ( in a nearly fresh & naked updated FIrefoxPortable) and immediately turned around & uploaded them to VirusTotal - No unzips or re-handling.

**Comment by geoffmcl** [comment]
@markstinson just checked tidy-5.2.0-win32.zip and tidy-5.2.0-win64.zip, on binaries web site, and did not find anything... but have never used VirusTotal before... maybe did something wrong...

Can you explain more...

**Comment by markstinson** [comment]
Sure. Here's how I did it.

1. go to https://github.com/htacg/tidy-html5/releases
2. download https://github.com/htacg/tidy-html5/releases/download/5.2.0/tidy-5.2.0-win64.zip and https://github.com/htacg/tidy-html5/releases/download/5.2.0/tidy-5.2.0-win32.zip
3. go to https://virustotal.com ( VirusTotal is owned by Google for around 5+ years and has been in operation for seams nearly like a decade. )
4. Select and "upload" the file. IIRC, it performs an in-browser sha256 of the file it's about to upload. If the sha256 matches a previous binary blob upload, it redirects you to the last set of results. Otherwise, it will then genuinely upload the file.

This can be done with any modern browser. I'm running with an updated FirefoxPortable edition when I made the first discovery. Since your findings are different or inconclusive, I just replicated them using my Android Phone and Firefox for Android using the steps above - to rule out my rig being infected (which it shouldn't be).

Sure enough, VirusTotal.com provided me the result set from my previous upload of the zip files last night.
* tidy-5.2.0-win64.zip = https://virustotal.com/en/file/dd9fd814cc44bc2ffa9b9e547b1a6cbb42b6be7b9358542d3ee7f6e10b676423/analysis/
* tidy-5.2.0-win32.zip = https://virustotal.com/en/file/94d653498b4f93b14f12a55ca06154e19c540c9b276e5d163f1cf84fa078f97a/analysis/

I hope this helps. Cheers, Mark S.

**Comment by geoffmcl** [comment]
@markstinson as stated, I get clean results using the direct URL -

https://www.virustotal.com/en/url/158d765841a2cda5f7b33e284daa6a7ed14a49c32e2be524928cae62b2da9253/analysis/
**and**
https://www.virustotal.com/en/url/c39fcae6f30bdba971953c4e8ab9dc28891295cf23fc72e979f37b5726998ad4/analysis/

Looks all green to me... do I miss something here..

Then if I use the file upload, of exactly the **SAME** files, I get the same VEX2662.Webshell!

When I download this **SAME** file, it compares 100% to the original I uploaded... also same files that are on https://github.com/htacg/tidy-html5/releases/download/5.2.0/tidy-5.2.0... I generated them in my Win7-PC...

And when I downloaded them again my McAfee does a scan, and it reports nothing...

Since I do **not** think either of these two files have any virus infection, so what do we do now?

Who is going to contact contact@virustotal.com and try to remove this **blot**? I think this is a **false positive**!
