### ISSUE TITLE
No output for certain XML

### ISSUE THREAD

**Issue by tewe** [htacg/tidy-html5#432]
With the short [attached file](https://github.com/htacg/tidy-html5/files/350353/sample.xml.txt) `tidy -xml sample.xml 2> /dev/null` has no output, and `tidy -m sample.xml` truncates the file to a single byte (\n).

There are warnings but no errors, and nothing that to me would explain the lack of output.

**Comment by geoffmcl** [comment]
@tewe thanks for your report...

I downloaded your `sample.xml.txt` file, but find that is a **binary** file... it commences with -

````
File [sample.xml.txt], 979 bytes.
0000:0000 1F 8B 08 00 00 00 00 00  03 00 9D 56 59 73 DB 36 ...........VYs.6
0000:0010 10 7E CF AF 40 F1 4E 41  47 3D 4D 3A 14 33 B1 E5 .~..@.NAG=M:.3..
0000:0020 34 6E 5D 4B 6D E5 76 D2  17 0F 44 AE 24 D4 20 C0 4n]Km.v...D.$. .
0000:0030 80 4B 51 EA AF EF 82 97  75 D9 75 E2 17 43 7B 7D .KQ.....u.u..C{}
0000:0040 7B 7C BB 52 F8 7E 9B 6A  B6 01 97 2B 6B C6 7C D0 {|.R.~.j...+k.|.
````

Now running `tidy` 5.3.5 on that file, with an `-xml` option, certainly only outputs **one** newline... what else do you **expect**?

Of course if you had added `-f temperr.txt`, instead of a redirection to `/dev/null` you would see some some 390 warnings...  

I remember in use-after-free in tidy-html5 5.1.25 #341, or/and perhaps in other issues, we had some discussion about maybe tidy should `abort`, with an error, if it say detects say 0x00 in the input data, and tidy has not been instructed to use some form of uni-code input, or something... seems hard to nail down a reasonable criteria for the abort...

Nothing was decided, so tidy only warns, and does its very best with the **rubbish** it may be reading...

But maybe something went wrong in the `sample` upload, and we should be talking about another file...

Please explain more...

**Comment by tewe** [comment]
The file is gzip'ed. I didn't notice because the .gz extensions was missing and my text editor decompressed it automatically. Which tidy doesn't (not that it should). Run through gunzip everything works. Sorry.

**Comment by geoffmcl** [comment]
@tewe yes, I tool should have noted the gzip magic number (1b 8f) in the dump... glad we are back on track ;=))

Thanks for closing...
