### ISSUE TITLE
Unexpected behavior with unclosed ul tag

### ISSUE THREAD

**Issue by dieselmachine** [htacg/tidy-html5#447]
I have this chunk of content:

```
<div>
 <ul>
  <li>item 1</li>
  <li>item 2</li>

  <p>paragraph</p>

  some text
</div>
```

when i run it through tidy, I end up with this:

```
<div>
  <ul>
    <li>item 1
    </li>
    <li>item 2
    </li>
    <li style="list-style: none; display: inline">
      <p>
        paragraph
      </p>some text
    </li>
  </ul>
</div>
```

What I was expecting was this:

```
<div>
  <ul>
    <li>item 1</li>
    <li>item 2</li>
  </ul>

  <p>paragraph</p>

  some text
</div>
```

According to http://w3c.github.io/html/grouping-content.html#elementdef-ul, a ul tag can only contain li tags, or script-enabled elements, so I thought perhaps it would close once it reached the first invalid element (the 'p' tag). Instead, it took every remaining element and constructed an li around them so it would work.

Is there a way that I can use tidy to get my desired result, and have it close a tag as soon as it encounters a situation where adding the node would result in invalid markup? I've looked through the configuration options, but none of them seemed suited for this purpose. Is there a way to have tidy never create new tags, and only have it close existing tags?

**Comment by geoffmcl** [comment]
@dieselmachine thanks for the issue...

Yes, initial, quick, research shows html4-- was more tolerant, in some ways, than html5++, so tidy still treats this `<ul>...</ul>` code in html4-- mode... that is with permissiveness of the contents of a `<ul>`, ul element, ul tag... it leaves other element, even text, as-is... 

Except of course, real old tidy (circa 2004), which would would add a `<li style="list-style: none">` element around the contents...

Also see issues #310, #396, #398, and maybe others...

So tidy maybe needs to change? Even without the suggested/implied additional `option`... especially, since it seems to presently result in `invalid` html, aka the W3C validator... being generated...

So is this the time, if tidy is still in html5++ mode, to end this permissiveness contents of a `<ul>`, Maybe, but need more information, specifications, understanding... to proceed...

The `Content Model` includes `Zero or more li`, that is clear, especially the `0`... which, in itself, implies other content...

But what exactly are [script-supporting-elements](http://w3c.github.io/html/dom.html#script-supporting-element)? The link only lists `<script>`, and `<template>`, but...

Such a change would certainly break the indirect support of say @hermanbergwerf #310, @rtack #396, leading to @rtack PR #398, and maybe others... 

Certainly look forward to **further** comments on this... It seems a fix to conform to html5++ would certainly break/change some current tidy behaviour...

Do we want that? Or should it really be subject to a **new** option... but then again tidy should **not** deliberately generate invalid html...

So thanks for the [grouping-content](http://w3c.github.io/html/grouping-content.html#elementdef-ul) link, maybe read differently by others... 

Let's see where this goes... thanks again for the issue...

**Comment by dieselmachine** [comment]
Script elements only contain those 2 tags. The content model is basically just making it clear that "flow control" elements (http://w3c.github.io/html/dom.html#flow-content) are not allowed as children of uls; only li tags, and script tags (which won't modify layout at all) are allowed in the ul. Text nodes are in the 'flow' category, so aren't allowed in a ul. <a> tags are flow, so are also not allowed (despite one of the linked issues showing an <a> in a <ul> and claiming it's valid markup, which it isn't).

The spec for the <ul> element is essentially the same as it was in HTML4, the only difference is that HTML5 allows 0 <li>s, while HTML4 required at least 1 LI (the DTD is here: https://www.w3.org/TR/REC-html40/sgml/dtd.html#block)

I personally think that conforming to spec would be more important than attempting to preserve templating syntax. The templating syntax seems more of a 'bonus feature', while outputting correct html seems like the main purpose of the library. I don't think added features should weaken or break the main functionality of the library.

In addition, we primarily use tidy for cleaning dynamic content submitted by users, while templates are basically static. We've never once needed to run tidy on our jinja templates, because we're in control of them, so we can do it correctly the first time. It's really just the users we're worried about. I imagine there could be a use case when allowing users to upload jinja templates, but that seems like such a bad idea security-wise that I wouldn't ever think of allowing it.

**Comment by geoffmcl** [comment]
As we are about to `release` **5.4**, and no work has been presented on this `Feature Request`, can only move it to milestone `next`, **5.5**.

As always, further comments, patches or a PR much appreciated... thanks...
