### ISSUE TITLE
Make a test suite

### ISSUE THREAD

**Issue by petdance** [htacg/tidy-html5#45]
Make a comprehensive test suite that is runnable via a simple `make test`.

**Comment by geoffmcl** [comment]
Well, we have a 'test' suite, presently runable via a batch (alltest.cmd), or a shell script (testall.sh), so with the use of cmake in develop-500 branch will certainly consider add auto-running of these... it is on my TODO list, unless you beat me to it...
Suggest an opion like -
option( RUN_TEST_SUITE "Set ON to run the test suite" OFF )
That is it defaults to OFF, since this should only be required by developers...

**Comment by geoffmcl** [comment]
Just a reminder the main development branch is now `master`, and may shortly delete the develop-500 branch, although for the moment have been trying to remember to keep them equal...

Did various trials, but found it very difficult to make the running of tests easily understandable to the average user, certain not a new user. You need a full understanding of exactly what is being tested, and this varies with each test,

Some just test for previous crashes; some need to view the original input and tidy output in a browser and visually decide; some need to re-run the output again through tidy and check for progressive change; some need the output compared to a previous `base` output; etc, etc... How can each of these be `explained`?

Would basically need a giant README listing the some 240+ tests one by one, with an explanation about each, what it tests, what to look for, etc... I have done some of this, but far from complete so not pushed. 

I also toyed with a script that generated a html iframe, loading the input with the output of each test to compare them in a browser sort of side-by-side... but again some tests have no output due to deliberate 'errors' in the input html, so again not completed and pushed...

So now feel adding a cmake RUN_TEST_SUITE option there for everyone and anyone to try would bring more questions than providing anything useful. Such tests **are** scripted, and can be **run** by a developer anytime... so seems no need for any cmake `automation`...

And some time back added a new html5 test set, and recently thanks to @lacombar this can now also be run in unix...

Due to the above, and since there have been no further comment on this since Jan 2015, am closing this...

Please feel free to re-open, or raise a new issue... thanks...
