### ISSUE TITLE
man page not installed

### ISSUE THREAD

**Issue by HaleTom** [htacg/tidy-html5#454]
On Ubuntu, `make install` gives me:

```
ravi@boxy:~/repo/tidy-html5/build/cmake(master u=)$ sudo make install
[ 49%] Built target tidy-static
[ 50%] Built target tidy
[100%] Built target tidy-share
Install the project...
-- Install configuration: ""
-- Up-to-date: /usr/local/lib/libtidys.a
-- Up-to-date: /usr/local/include/tidyplatform.h
-- Up-to-date: /usr/local/include/tidy.h
-- Up-to-date: /usr/local/include/tidyenum.h
-- Up-to-date: /usr/local/include/tidybuffio.h
-- Up-to-date: /usr/local/lib/libtidy.so.5.3.9
-- Up-to-date: /usr/local/lib/libtidy.so.5
-- Up-to-date: /usr/local/lib/libtidy.so
-- Up-to-date: /usr/local/bin/tidy
ravi@boxy:~/repo/tidy-html5/build/cmake(master u=)$
```

How do I install the `man` page?

**Comment by geoffmcl** [comment]
@HaleTom hi, it looks like to do not have `xsltproc` installed. It is needed to build the `tidy.1` man page...

When I run `sudo make install` I see -

````
pi@raspberrypi ~/Projects/tidy-html5/build/cmake $ sudo make install
[ 49%] Built target tidy-static
[ 50%] Built target tidy
Generate /home/pi/Projects/tidy-html5/build/cmake/tidy-help.xml
Generate /home/pi/Projects/tidy-html5/build/cmake/tidy-config.xml
Generate tidy.1
[ 50%] Built target man
[100%] Built target tidy-share
Install the project...
-- Install configuration: "Release"
-- Up-to-date: /usr/lib/libtidys.a
-- Up-to-date: /usr/include/tidyplatform.h
-- Up-to-date: /usr/include/tidy.h
-- Up-to-date: /usr/include/tidyenum.h
-- Up-to-date: /usr/include/tidybuffio.h
-- Up-to-date: /usr/lib/libtidy.so.5.3.9
-- Up-to-date: /usr/lib/libtidy.so.5
-- Up-to-date: /usr/lib/libtidy.so
-- Up-to-date: /usr/bin/tidy
-- Installing: /usr/share/man/man1/tidy.1
pi@raspberrypi ~/Projects/tidy-html5/build/cmake $
````

During the cmake configuration and generation stage you should have seen -

````
-- *** NOTE: xsltproc NOT FOUND! Can NOT generate man page.
-- *** You need to install xsltproc in your system.
````

Maybe these should be elevated to `warnings`? When it is installed the above two lines will be replaced with -

````
-- *** Generating man tidy.1 custom commands...
````

In Ubuntu I guess `sudo apt-get install xsltproc` should do it... advise if there is still a problem... thanks...

On another note I note you have `-- Install configuration: ""`. You need to add `-DCMAKE_BUILD_TYPE=Release` to the cmake configuration and generation step, otherwise you are getting the default partial `Debug` (I think) version, which has development `asserts`. This is not really a problem, but it is better to explicitly set `Release`. 

What this does is it adds `-DNDEBUG` to the compiler options, which removes those `asserts`. You can use `-DCMAKE_VERBOSE_MAKEFILE=ON` to be able to **see** all the compile options. Conversely, adding `-DCMAKE_BUILD_TYPE=Debug` will add `-g` to the compiler options, and all the debug symbol will be included as well.

The second thing is you are installing into `/usr/local/.`, the cmake default. In my case I run cmake with `-DCMAKE_INSTALL_PREFIX=/usr` to install tidy into the general `/usr` space, but again no problem if you prefer `/usr/local/.`... works the same in most cases...

You will note there is a `build-me.sh`, which, if used, adds the above two options to `cmake`... 

I have made a strong **TODO** note to myself to find where to beef up the build documentation, certainly adding the `xsltproc` **prerequisite** to build the man page...

Hope this helps...

**Comment by geoffmcl** [comment]
@HaleTom closed my TODO by beefing up the [README.md](https://github.com/htacg/tidy-html5/blob/master/README/README.md) - adding -
````
4. the `xsltproc` tool is required to build and install the tidy.1 man page.
````

Can you confirm this was the problem, and can this be closed... thanks...

**Comment by HaleTom** [comment]
That solved it! Thanks!
