### ISSUE TITLE
Tidy is confused by correct DOCTYPE for HTML 4 transitional

### ISSUE THREAD

**Issue by still-dreaming-1** [htacg/tidy-html5#466]
The [official](https://www.w3.org/QA/2002/04/valid-dtd-list.html) way to specify the HTML 4 transitional document type is

```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
   "http://www.w3.org/TR/html4/loose.dtd">
```

When I use that Tidy seems confused. If I understand the output correctly it seems to think that I did not specify a valid doctype and that, based on the rest of the HTML, I appear to be using HTML 4 transitional. It seems it wants me to put the value "HTML 4.01 Transitional" inside the quotation marks instead of "-//W3C//DTD HTML 4.01 Transitional//EN"

Here is the relevant output from tidy:

> Info: Doctype given is "-//W3C//DTD HTML 4.01 Transitional//EN"
> Info: Document content looks like HTML 4.01 Transitional

**Comment by still-dreaming-1** [comment]
Apparently HTML 4 transitional is no longer a valid doctype accorting to the specification: https://github.com/validator/validator/issues/408#issuecomment-260825801

**Comment by geoffmcl** [comment]
@still-dreaming-1 thank you for your comment...

I am sure current tidy, trying to support both HTML5, and all previous versions, 
has some problems...

But **not** sure what you point out here?

Yes, I suppose tidy can be **confused**, and we need to work on 
that...

The internal string for `4.01 transitional`, in W3C_Doctypes[], is -

````
  {  5, H41T, "HTML 4.01 Transitional", "-//W3C//DTD HTML 4.01 Transitional//EN", "http://www.w3.org/TR/html4/loose.dtd"                      },
````

Are you suggesting a change here?

But give us a minimal html input, what tidy outputs, and what 
you expect...  to understand the discussion... and the libtidy 
version used...

Best regards, Geoff...

**Comment by still-dreaming-1** [comment]
I'm pretty sure anything with that DOCTYPE I posted will reproduce this. I also told you what the output I see is that I thought was strange. Originally I thought this was a bug because I thought I was using a valid doctype. My follow up comment shows that I found out it actually is not a valid doctype. I think the output should report that as an error or a warning since there is no longer a valid doctype for HTML 4 transitional. I'm not sure what the prettified HTML should be since changing to a different doctype would be a pretty big change. I don't really have an opinion about that part.

**Comment by geoffmcl** [comment]
@still-dreaming-1, I guess I am still missing your point here ;=(( But maybe gain some insight from reading your other posts...

From https://github.com/validator/validator/issues/408, I liked some of your questions, and @sideshowbarker answers, which I largely agree with, so copy them here -

`<quote>`

> So basically between HTML 4 and 5, we are supposed to choose one or the other?
No, you’re just supposed to use HTML, period. The HTML language is now versionless.

> I want to understand what these options mean not just in terms of which one we are supposed to use, but how they might affect browser behavior
Browsers process HTML without regard to any version. For browsers, HTML is versionless, just as with the language itself.

> I'm guessing if I set the doctype to one of the HTML 4 values, this means the browser should work correctly with HTML 4, but it might not work at all with HTML 5 stuff. Is that right?
No, browsers don’t care if you use an HTML4 doctype or the “HTML5” one. Browsers will process the document in exactly the same way regardless.

`</quote>`

Regarding legacy doctypes, I, like perhaps many older sites, can have **MANY** legacy doctypes... at the time, now years ago, 4.01 transitional seemed the best fit for what I wanted...

And these still display correctly in most browsers, and pass the validator, like -

https://validator.w3.org/check?uri=http%3A%2F%2Fgeoffair.net%2Ftidy%2Findex.htm

That is what I expect, and likewise tidy reports no problems... and that page proudly sports a `valid 4.01`, and a `tidy` image... I hope that will remain unchanged, at least in the foreseeable future... so in what sense is 4.01 transitional invalid?

Now, if I feed that page to validator `nu' I will get the mess I expect -

https://validator.w3.org/nu/?doc=http%3A%2F%2Fgeoffair.net%2Ftidy%2Findex.htm

Today, new pages I add are usually in conformity to the later html standards, but not always... you get into a habit... note, I too try to not use html4 versus html5, but this is an easy way to talk about the quite big transition... so this is my new standard `blank5` page, which passes `nu` -

https://validator.w3.org/nu/?doc=http%3A%2F%2Fgeoffair.net%2Fblank5.htm

If I feed the above valid `index` 4.01 trans legacy page to tidy, and instruct it, by config, to treat it as a html5 doctype, while it will change the doctype, that is about all it will do! **Very bad**!

A giant **`Feature Request`** coming out of this could be that tidy either, spit out many errors and warnings, like `nu`, or better still, modify the document to suit the doctype requested... some `little` steps have been taken in this regard, but lots to do... and each should be its own issue...

But then what is the purpose of tidy? Is it just a pretty printer? Should it try to do more? It does try to handle all doctypes... And what is the general interest in such a product? Usages? There are many open questions...

Hope this helps, regards, Geoff.

**Comment by still-dreaming-1** [comment]
I guess in my opinion I see tidy as simultaneously being both a validator and pretty printer. The reason I say that is... well... those are the features it offers. It gives you warnings, errors, and info, not just pretty printed HTML. Also I see no reason not to provide both as they are related. If I am going to use a validator and it tells me about some problems and the pretty printed HTML was different from the original, I could diff the changes and consider those as suggestions for how to fix those validation problems.

The reason I bring that up is I'm saying I would like to see as many relevant validation warnings and errors as possible. Perhaps I am misunderstanding the difference between https://validator.w3.org/check?uri=http%3A%2F%2Fgeoffair.net%2Ftidy%2Findex.htm and the nu equivalent https://validator.w3.org/nu/?doc=http%3A%2F%2Fgeoffair.net%2Ftidy%2Findex.htm

I thought the nu one was just more up to date / accurate with the current specification?

So specifically here is one question we can discuss. Should any attempt use an HTML 4 transitional doctype cause tidy to display some kind of warning or error? I think it should because as far as I understand it, the use of HTML 4 transitional doctype is no longer valid. Now when I say no longer valid this is a tricky topic. Because it is no longer valid, according to @cvrebert, this means it is spec'd as "Authors MUST NOT use it". However, because it used to be valid, it is also spec'd as "Browsers MUST implement it". So at the very least, since tidy is partially an HTML validator and authors must not use this, tidy should at least show a warning when you use any doctype other than the ones shown at 
any doctype other than the ones shown at https://html.spec.whatwg.org/multipage/syntax.html#syntax

But you might be right this could be part of a larger change in direction for tidy. If it starts reporting HTML 4 only stuff as warnings, would that be a change in direction? I'm sure you know more about that than I do. I'm just saying tidy is at least partly a validator and is showing an invalid doctype as valid.

I think mainly from what I have learned from all this is that I should not try to use tidy as modern validator, I should just use https://github.com/validator/validator instead. I was evaluating both of them and I think I have my answer now.

**Comment by geoffmcl** [comment]
@still-dreaming-1, as stated, what is tidy, is an open question...

In the many, many years I have been associated with tidy, when ever someone suggested tidy was a `validator`, some core developer(s), at the time, would quickly say **no**!, citing various reasons... and now I suppose I am a core developer, I have more or less inheritied that... to varying degrees...

When I was big into expanding my web site, I used it in that way. If I ran tidy over my pages, there seemed an almost 100% chance that the page would also pass the W3C validator... but that is no longer true for html5 pages I create today... tidy fails to warn me of many problems... sad...

That is an interesting question - what is the difference between the original validator, and validator `nu`?

This, and many previous experiments with the W3C validator - https://validator.w3.org - seems to show that, if your document has a legacy doctype, then it will be handled there, but if it has a html5 doctype, it will be shunted to `nu`... which sort of seems reasonable... if you specified just `<!DOCTYPE html>`, aka versionless html, then you want the document validated according to the latest `standards`... otherwise the doctype determines what should be, and not be, there, and you should be validated **only** on that...

Maybe @sideshowbarker could help us with that, being a developer of `nu`?

In a sence, **`libtidy`** is both of those, rolled into one. Internally it has two modes - default html5, and legacy html4. When it reads the doctype you have given, it can switch modes, tables, decisions...

Now, should tidy, on reading a valid 4.01 transitional doctype, issue a warning, or error? I say absolutely not! 

If we **were** in the business of nagging users, like, on reading `ANY` legacy doctype we could say `Aw shucks, you are using an ancient legacy doctype, especially a **transitional** one! You should consider moving to a later specification!`, or something like that... for me, we already have too much `Info` of this type output, and I added a `--show-info no` option to removing this type of `nagging`...

To me, your reading of what @cvrebert said, is not quite right, or at least needs some expansion? Authors who have used this doctype, probably thousands, millions of web documents, should have no fear about browser support, at least for a very long time, and back to what @sideshowbarker said, `No, browsers don’t care if you use an HTML4 doctype or the “HTML5” one. Browsers will process the document in exactly the same way regardless.`...

And perhaps the @cvrebert emphasized `Authors MUST NOT use them.` is a little too **strict**, but in a sense right. I too would encourage new html pages, created today, should try to conform to the latest html spec.! Why not?

And it is my big lament that tidy does not do **more** in this regard... it still allows legacy features in the latest doctype... run the page through `nu` will show what tidy needs to flag, and fix... As stated, this needs `work`... I will help work on these issues, one by one... volunteers **very** welcome... thanks...

This could certainly include a warning, if given the option `--doctype html5`, and it finds the document starts with legacy doctype, issue a warning like found illegal doctype, but will correct that on output... at present tidy does this fix silently... as with quite a few others...

The W3C validator used to have a backend of **`libtidy`**, where it output the corrected, prettified document, but that check box has done nothing for years...

So, yes, the `nu` validator would also be my choice today. What I like is that it usually gives you good information about how to effect a `fix`... 

Maybe a `nu+` could effect all those changes, and output a corrected, validated, document... a java_Tidy_5... it could pass that corrected doc to **`libtidy`** to pretty print, with lots of format options... I dream...

**Comment by sideshowbarker** [comment]
> This, and many previous experiments with the W3C validator - https://validator.w3.org - seems to show that, if your document has a legacy doctype, then it will be handled there, but if it has a html5 doctype, it will be shunted to nu... which sort of seems reasonable... if you specified just <!DOCTYPE html>, aka versionless html, then you want the document validated according to the latest standards... otherwise the doctype determines what should be, and not be, there, and you should be validated only on that...

Yeah that is how https://validator.w3.org/ works. But it’s not going to work that way forever. Someday it too will change to just do what https://validator.w3.org/nu/ does and ignore the obsolete version in the doctype and just always check it against the rules in the latest HTML spec.

The W3C will still continue to provide a validator that lets you check your document against the HTML4 rules and XHTML1 rules (and even HTML 3.2 and HTML 2.0 rules…) but it will not be based on sniffing the doctype any more—instead you’ll need to opt into the by manually choosing the version you want to check against.

**Comment by geoffmcl** [comment]
As we are headed for a new 5.4 release soonest, am closing this... just do not see a question current tidy needs to address...

But feel free to re-open, or post another issue... thanks...
