### ISSUE TITLE
vertical-space newlines now 0, 1,  or  3 but not 2 anymore

### ISSUE THREAD

**Issue by jidanni** [htacg/tidy-html5#470]
We read
```
       vertical-space

              Type:    AutoBool
              Default: no
              Example: auto, y/n, yes/no, t/f, true/false, 1/0

              This option specifies if Tidy should add some extra empty lines
              for readability.

              The default is no.

              If set to auto Tidy will eliminate nearly all newline
              characters.
```
Do there please mention what happens if set to 'yes'.

And don't say "some". This is not a random number. State the hard facts.

It turns out "no" adds zero blank lines (i.e., only one newline
character) between `</p>` and the next `<p>` (etc.)

"yes" adds two blank lines (i.e., three newline characters) there.

And "auto" indeed even zaps any newline characters there.

But did you know, in the not so distant past, tidy's "no" put a
pleasant single blank line (i.e., two newline characters)
there.

But now there is no way to achieve that.

There ought to be additional choices: -1, 0, 1, 2, ... what is just
right for Mr. A might not be so for Mr. B.

1 for one vertical space (two newlines), etc.

P.S., shouldn't `</p><hr><p>` always have an equal number of newlines
between them?

By the way, you might be wondering what options I use,
```
$ cat dantidy
#!/bin/sh
# Copyright       : http://www.gnu.org/licenses/gpl.html
# Author          : http://jidanni.org/
# Last Modified On: Mon Dec  5 00:51:08 2016
# Update Count    : 28
set -eu
f=/tmp/dantidytmp
umask 0 #so root won't lock $f up
cat > $f
validate --warn --emacs $f 1>&2 #else tidy might change the doctype!
perl -C -pwe 's/[^[:ascii:]]/sprintf "\\x{%04x}",ord $&/ge' $f| #my uni2ascii(1)
tidy --doctype strict --gnu-emacs yes --indent-spaces 1 --indent auto -utf8 \
     --tidy-mark no -quiet --fix-backslash no --enclose-block-text yes \
     --vertical-space yes "$@" |
perl -C -pwe 's/\\x\{([[:xdigit:]]{4})\}/chr eval "0x$1"/eg' #my ascii2uni(1)
#(not sure if I still need all the uni2ascii stuff.)
```
HTML Tidy for Linux/x86 version 5.2.0

**Comment by geoffmcl** [comment]
@jidanni thank you for your issue...

There seems to be three parts, if I read you correctly -

 1. Improve Quick Help wording
 2. More vertical space control.
 3. Current vertical space for `<hr>` element
 
####  1, Improve Quick Help wording

Yes, this **documentation** is always an issue, and suggested changes are **very** welcome...

Specifically on http://api.html-tidy.org/tidy/quickref_5.2.0.html#vertical-space

> Do there please mention what happens if set to 'yes'.

Well, the wording, `This option specifies ...`, used on many, **many** of the options, to me, already sort of says `If you set this option`, so it tells the `y, yes, t, true, 1`... but open to suggestions...

> And don't say "some". This is not a random number. State the hard facts.

Well I used `some` because at that stage I do not know the hard facts ;=() And still don't...

To back up a bit, and search through the development of this option, there seemed a sort of consensus that tidy output too much vertical space, so this `Bool` vertical-space option was developed... it defaulted to `no` to satisfy those wanting to reduce the vertical space, and the `yes` became known as `classic` tidy mode internally, hopefully to put back all the previous vertical spaces back... but in the octopus the pretty-print module has become, I am not so sure this is true... hence my `some`!!!

Would really appreciate it if someone could better document this... between what elements will a `yes` add, or **not** add, vertical space... As you will see in the code, this is not an easy task to decide...

Then another user brought up a `compact` tidy option, where most, if not all, vertical space will not be printed/output... There was thought about this being a separate option, but eventually got tacked onto vertical-space, changing it to an `AutoBool` - 3 states - no, yes, auto, and the `auto` removes the newlines... maybe not ideal, but that's where we are now...

So you are correct in your current summary -

 - no = use less vertical space
 - yes = tidy classic mode with extra vertical space
 - auto = use no vertical space - compact mode

And it is agreed more definition of what vertical spaces are effected, by `no` and `yes` would be good...
 
But, as I say, always open to improving the docs... How do you think it should be worded? Exactly?

####  2. More vertical space control

> There ought to be additional choices: -1, 0, 1, 2, ... what is just...

This is a good `Feature Request`, for pretty printing... and we may have had something like it before...

One point. At present tidy does not support `-1`, ie negative integers... there have been some other occasions where I **wish** it did... just need to improve the parser for these `integer` options probably... but **not** yet done...

If you, or others, start to look at this, you will need some time to get into the pretty printer... how it builds up the output string in an internal buffer, and only at certain points, flush it to the real output, adding a new line, and potentially adding indent, etc... quite interesting to try to follow... and then support an option level for newlines... which you started to spec out...

Or indeed, write a **new** `pprint2.c` module, offering a better approach...

As always, I will help where I can...

####  3. Current vertical space for `<hr>` element

> P.S., shouldn't `</p><hr><p>` always have an equal number of newlines between them?

Now you give a specific sample, and a question. This I have expanded to `input5\in_470.html` for testing...

```html
<!DOCTYPE html>
<html>
<head>
<title>Issue #470</title>
<meta charset="utf-8">
</head>
<body>
<p>Para 1</p><hr><p>Para 2</p>
</body>
</html>
```

This is certainly one example of where `classic` tidy, ie `--vertical-space yes` will have extra blank lines around the `<hr>`... it appears some people like it that way... so, I would answer your question with `no`, these particular elements do change, depending on this option... but others do not...

But as you point out, maybe there should be **better** case-by-case, element-by-element control... additional choices... more user flexibility... look forward to it... thanks...

**Comment by balthisar** [comment]
Let's move further discussion of this to #486 (I will also rename that thread), and I'll close this, because they are really quite related in terms of a fix/refactoring.

**Comment by geoffmcl** [comment]
Agree with the above, and I guess @balthisar just missed hitting the close button...

There are so many issues related to the message output, and I think @balthisar will address these in `next` 5.5...
