### ISSUE TITLE
Mention what '--'  within comments gets changed to

### ISSUE THREAD

**Issue by jidanni** [htacg/tidy-html5#476]
When mentioning tidy discovered a  `--` within a comment,
also mention that it changed it to `==`, else the user looks and looks and
doesn't find it. Who knows, you might have changed it to `@@` but if you
don't say what you changed it to, 1. the user thinks there is a 50%
chance that you changed it, but isn't sure. 2. the user cannot guess
what you changed it to.

Yes mention it in the runtime warnings, and also on the man page.

**Comment by balthisar** [comment]
@geoffmcl, this is an interesting one. Can you shed some light?

This is an easy fix, but I'm not sure what's going on here. If `fix-bad-comments` is `yes` (the default), then `--` becomes `==` and `---` becomes `===`, but if set to `no`, `--` becomes `-=` and `---` becomes `--=`. 

Is Tidy behaving properly here? Is the intention when `no` not to touch the bad comments? Even when `no`, it still prints a double-hyphen followed by an equals sign.

**Comment by balthisar** [comment]
Some more: given the source:

~~~
<!-- This comment - this one, here - has some embedded hyphens that
     Tidy will change to equals signs = -->
<!-- This comment -- this one, here -- has some embedded double hyphens that
     Tidy will change to double equals signs == -->
<!-- This comment --- this one, here --- has some embedded triple hyphens that
     Tidy will change to triple equals signs === -->
~~~

And `fix-bad-comments no` :

~~~
<!-- This comment - this one, here - has some embedded hyphens that
     Tidy will change to equals signs = -->
<!-- This comment -= this one, here -= has some embedded double hyphens that
     Tidy will change to double equals signs == -->
<!-- This comment --= this one, here --= has some embedded triple hyphens that
     Tidy will change to triple equals signs === -->
~~~

With `fix-bad-comments yes` it works as we would expect:

~~~
<!-- This comment - this one, here - has some embedded hyphens that
     Tidy will change to equals signs = -->
<!-- This comment == this one, here == has some embedded double hyphens that
     Tidy will change to double equals signs == -->
<!-- This comment === this one, here === has some embedded triple hyphens that
     Tidy will change to triple equals signs === -->
~~~

With`no`, Tidy _is_ trying to fix bad comments just enough that no invalid output is occurring, rather than prettying-up the output as with `no`. However it's failing in the case of greater than two hyphens, so I think I've converted this feature request into a bug report.

Moving forward, I see two options here:

- I could ensure that two hyphens are never printed, so that `---` becomes `-==`, etc., but then the fact is, we're _always_ preserving one of the hyphens, which seems kind of silly.
- In order to simplify things, I suggest we simply eliminate `fix-bad-comments`, and _always_ simply fix the bad comments as if it were `yes`; and, of course, indicate in output (per the feature request) that this is happening.

Any thoughts?

**Comment by geoffmcl** [comment]
@balthisar **OOPS**, sorry, I looked into this a little and prepared a reply back at 2016-12-24, but somehow **forgot** to post it. So first is my original comment from then, which also mentions the weirdness I found, that you also mention -

2016-12-24: @jidanni yes, this is a strange action that I have never explored before...

In reading around this seems a concession only for `ColdFusion` users, but maybe there is a wider reason, that is applies generally... I can not seem to find anything specific about 2 or more adjacent hyphens in comment in W3C docs... Perhaps you or other could point me to some documentation on this... thanks...

I agree, like several other warnings tidy issues, it makes no mention that it made a change, a fix, in this case 2 or more adjacent hyphens all to `=`. I guess the tidy creators want to really keep warning strings very short... Perhaps that is **not** so necessary these days...

In further experimentation I found that in using `--fix-bad-comments no` I found 2 things which feel buggy -

 1. will still issue the warning! Hmmm.
 2. will still convert the last `-` to an `=`! Which seems weird?

If I specifically turn the option **off** should tidy still issue a warning? Somehow I feel **no**, but if kept like this, then we would have to sort of have two warning types: one advising `changed to =`, and the other not. And the continued conversion of the last, even when `off` seems very strange. I would expect my `no` to cause tidy do nothing.

But that aside, in this simple case perhaps this warning could be changed to -

```
line 9 column 19 - Warning: 2 or more adjacent hyphens within comment, changed to equal signs.
```

Or something else? Ideas... thanks...

It does seem to already mention this change on the man page, although as usual the actual wording could be improved. Ideas welcome... thanks...

Forward to 2017-09-24: So you can see I also thought it **buggy**... certainly not what I expected... and proposed some ideas on a **fixes**... 

And thinking about it more now, do not exactly agree with your two options... moving forward...

Agree, perhaps this option has outlived it usefulness... I can not imagine any modern parser getting messed up over two, or more adjacent `-` in a comment field... so maybe it should **now** default to `no`? And tidy does **nothing**, and **no** warning...

And if the user sets `yes`, the issue an `Info:` on any change tidy makes, not a **warning**...

But would not remove it...

It seems we do agree, this should be changed... Just exactly how is the question... What do you propose after my additional comments, old and new? 

And thanks for bring this up again... Do not know why I missed posting, except it was Christmas!

**Comment by balthisar** [comment]
Okay, a few more notes while researching this. ColdFusion (which is still a current application) uses `<!--- --->` for comments, and the only way to ensure that Tidy does not interfere with them is to ensure that `fix-bad-comments` is `no`; so strike the idea about eliminating `fix-bad-comments`.

However we still have an issue: when `yes`, ColdFusion comments won't work, and when `no`, bad comments still slip through (i.e., Tidy generates bad code).

However... double hyphens are only bad when HTML supports SGML, and it appears that HTML comments are no longer required to be SGML comments, **for all versions of HTML**.

**Comment by geoffmcl** [comment]
@balthisar oops again, seems we cross posted at about the same time ;=))

Maybe we agree -

 - Default to `no`, and tidy does **nothing**. No fix or warning
 - User sets `yes`, if they have say ColdFusion problem, and tidy fixes and advises by `Info:` of change
 
Agreed?

**Comment by balthisar** [comment]
Continuing on, it looks like the [working group](https://html.spec.whatwg.org/#comment) is dropping the requirement for SGML compatibility for comments, i.e., we don't have to touch consecutive hyphens for HTML. However the [old-style validator](https://validator.w3.org/) still balks at the hyphens, but the [nu validator](https://validator.w3.org/nu/) gives all of the extra hyphens a pass, with a warning that they're not valid in XHTML (and by extension, we can assume XML).

Since we support XHTML as well as XML, we still have to behave differently.

@geoffmcl, yup, looks like we're active at the same time. I'm not sure if the `no` behavior is correct, either, because it still changes the trailing hyphen to an equals sign, i.e., it's trying to make a fix, but isn't successful if there are three hyphens in  row.

**Comment by balthisar** [comment]
@geoffmcl, still cross-posting...

> Default to no, and tidy does nothing. No fix or warning

I agree to this, but it's still broken, and I'd want to fix this, i.e., ensure that Tidy really does nothing, because right now it's doing something.

If set to `yes`, this breaks ColdFusion, and I'm okay with that. Can we agree that given this input, we should get the following output for each case?

## Input
~~~
<!-- This comment - this one, here - has some embedded hyphens that
     Tidy will change to equals signs = -->
<!-- This comment -- this one, here -- has some embedded double hyphens that
     Tidy will change to double equals signs == -->
<!-- This comment --- this one, here --- has some embedded triple hyphens that
     Tidy will change to triple equals signs === -->
<!--- Cold Fusion uses this syntax for comments. --->
~~~

# `no` (touches nothing)
~~~
<!-- This comment - this one, here - has some embedded hyphens that
     Tidy will change to equals signs = -->
<!-- This comment -- this one, here -- has some embedded double hyphens that
     Tidy will change to double equals signs == -->
<!-- This comment --- this one, here --- has some embedded triple hyphens that
     Tidy will change to triple equals signs === -->
<!--- Cold Fusion uses this syntax for comments. --->
~~~

This example touches nothing, and I agree no warning for HTML. But what about XML or XHTML? These are error conditions preventing validation. I think we should issue at least a warning (probably error) for these.


# `yes` (breaks ColdFusion)
~~~
<!-- This comment - this one, here - has some embedded hyphens that
     Tidy will change to equals signs = -->
<!-- This comment == this one, here == has some embedded double hyphens that
     Tidy will change to double equals signs == -->
<!-- This comment === this one, here === has some embedded triple hyphens that
     Tidy will change to triple equals signs === -->
<!--= Cold Fusion uses this syntax for comments. =-->
~~~

For XHTML and XML, `yes` would mean no change, since we're fixing things. We'd issue TidyInfo for each of these changes.

**Comment by geoffmcl** [comment]
@balthisar yes, still crossposting...

When I suggested the default change to `no`, that includes a code **fix** to really do **nothing**... certainly **not** as now...

Although maybe that default is **changed** on legacy mode detection, see `AdjustTags`, and `ResetTags`, if the legacy validator still burps...

And if the option is set `yes`, either by user or legacy mode, or maybe by setting XHTML?, then we fix, and `warning`, or `Info:`, spelling out the change...

But do not understand exactly why you say `yes` **breaks** CodeFusion. I thought **yes** was to provide a fix for ColdFusion, even if this requires some adjustment of the current code...

And agree, it seems an XHTML should be slightly different again... but maybe not...

Will end crosspost, since off for dinner ;=))

**Comment by balthisar** [comment]
> But do not understand exactly why you say yes breaks CodeFusion. I thought yes was to provide a fix for ColdFusion

Yeah, I was confused by this, too. But `yes` turns ColdFusion comments into standard comments, and leaves them broken in ColdFusion. ColdFusion users will put source code to Tidy, then back to ColdFusion, so this fix breaks their comments in CF. CF on its own will never output a CF comment, because that would be broken; they're already stripped away for final use. I can't imagine that the intention was to make a CF source document ready for the web, because it would contain all of CF's code. It'd be like outputting a .php document without processing it via PHP first.

Enjoy dinner! I'll work on this.

**Comment by geoffmcl** [comment]
@balthisar wow, thanks for PR #615...

I think this is a great change for current HTML5 documents, in that `tidy` does nothing, by default... as I think it should... thanks...

But for legacy documents, it also does **nothing**, except issue a warning - see say  [in_476-1.html](https://github.com/geoffmcl/tidy-test/blob/master/test/input5/in_476-1.html)

```
line 11 column 19 - Warning: detected adjacent hyphens within the comment; consider fix-bad-comments
line 12 column 24 - Warning: detected adjacent hyphens within the comment; consider fix-bad-comments
```

Thus tidy's output will **not** pass the W3C legacy validator... 

Principal: Where possible tidy should output fully valid HTML, and not just almost tell me what else I could do... that is, **not** output **invalid** html, in **any** circumstances... and if tidy is **not** going to fix the problem, or can't decide, then should flag an **error** and **not** output anything, unless **forced**...

Do we all agree with that **principal**?

So one way to fix that would be the following patch -

```diff
diff --git a/src/lexer.c b/src/lexer.c
index 6a6775e..4d1b7a6 100755
--- a/src/lexer.c
+++ b/src/lexer.c
@@ -2613,7 +2613,7 @@ static Node* GetTokenFromStream( TidyDocImpl* doc, GetTokenMode mode )
     Bool isempty = no;
     AttVal *attributes = NULL;
     Node *node;
-    Bool fixComments = cfgBool(doc, TidyFixComments);
+    Bool fixComments = cfgBool(doc, TidyFixComments) || !(TY_(HTMLVersion)(doc) & HT50);
 
     /* Lexer->token must be set on return. Nullify it for safety. */
     lexer->token = NULL;
```

But there are probably other ways to achieve the same, or and even with this there is **more** to be done, since, while we now get a fix of a legacy document, we return to the original reason for this issue - namely a **silent** change/fix...

Also thanks for the additional input on ColdFusion and SGML... 

I note the legacy validator seem to only error on the trailing `--->`, with a rather weird message - processing [in_476-3.html](https://github.com/geoffmcl/tidy-test/blob/master/test/input5/in_476-3.html), a legacy document with a CF comment - 

```
Line 10, Column 20: invalid comment declaration: found name character outside comment but inside comment declaration
<!--- CF comment --->
```

Remove that single character, and it passes, which make me wonder why tidy ever attacked the `<---` as well... and did not try to get into why `<!-- a -- b -->` is an error, in legacy docs -

```
Line 10, Column 11: invalid comment declaration: found name start character outside comment but inside comment declaration
<!-- a -- b -->
```

And also did **not** get into why the warning from `nu`, with [in_476.html](https://github.com/geoffmcl/tidy-test/blob/master/test/input5/in_476.html) -

```
Warning: The document is not mappable to XML 1.0 due to two consecutive hyphens in a comment.
At line 9, column 21
Comment with -- end -->
```

So left the XHTML/XML possible issues until a later time... although I think some have been covered, like `-asxhtml` seemed to do the fix... but not fully tested, explored...

But what about the above patch, to either **fix** a legacy document, with a `warning` **or** `Info:` message, or bomb out with an `error` message? Thanks...

And a minor quibble - I have adopted the idea to add `Issue #XXX` to all new comments, in the code... I feel this gives new developer a quick way to look back to a possible **why this change**... to read some of the discussion, and perhaps understand more of the reason...

You have certainly commented well your changes, but misses that additional clue of where to look in `issues`... What do you think...

Sorry for the **very** short working day today, so this will be my only comment... be back soonest...

**Comment by balthisar** [comment]
@geoffmcl, the thing I don't like about the proposed patch is that it _forces_ the fix for non-HTML5 documents. Thus it would break, say, ColdFusion for HTML4 or XHTML users, with no workaround, i.e., there's no option for `no, and I really mean it`.

However! It would be trivial to make the option an enum without breaking config files: `auto`, `no`, and `yes`, where `auto` acts like `no` for HTML5, and acts like `yes` for everything else.

**Comment by balthisar** [comment]
I've updated the PR with the new `auto` option, which is now the default and behaves appropriately acting as `no` for HTML5 documents, and `yes` for everything else. 

This broken one existing test case; see the commit notes on that separate PR over in the test repository.

Incidentally this fixes a TidyAutoState bug that's been in the source for a while! Luckily no test cases were affected by the fix.

**Comment by balthisar** [comment]
Continuing...

> Principal: Where possible tidy should output fully valid HTML, and not just almost tell me what else I could do... that is, not output invalid html, in any circumstances... and if tidy is not going to fix the problem, or can't decide, then should flag an error and not output anything, unless forced...

> Do we all agree with that principal?

Yup, which is why I considered leaving the default as `yes`; I think the `auto` I just added is a better solution.

> which make me wonder why tidy ever attacked the `<---` as well... and did not try to get into why `<!-- a -- b -->` is an error, in legacy docs -

For the `<!---` case, I just added this as part of the fix, per the specification: 

> with the additional restriction that the text must not start with a single U+003E GREATER-THAN SIGN character (>), **nor start with a U+002D HYPHEN-MINUS character (-)**

And the second case causes issues because

> nor contain two consecutive U+002D HYPHEN-MINUS characters (--)

We could have changed *just* the correct number of hyphens to bring us into compliance, but it looks like Tidy has always changed all of them as it looks more pretty.

The warning from the **nu** validator is saying that the double hyphen is okay in HTML, but it's not mappable to XML because it doesn't comply with the SGML comment format.

>  I have adopted the idea to add Issue #XXX to all new comments, in the code...

I can follow suit. Some of my PR's are major infrastructure where it wouldn't be practical, but for something on this scale, I'll remember to do that.

**Comment by jidanni** [comment]
Yes, the worst thing is if tidy fixed something for me with just a
warning if any, buried way down among other warnings.

**Comment by balthisar** [comment]
@jidanni, thanks for checking back in, and sorry this is taking so long, but we've got it almost ironed out. With the new setting, if the PR is accepted, Tidy will report an Info: message each time a change it made, but if this is too noisy, you can set `show-info` to `no`, and the change will still be made.

Note that because of the large possibilities, Tidy won't say "---" becomes "===", because each of these strings can be infinite length. Instead, it will simply indicate that adjacent hyphens were changed to equals signs.

**Comment by geoffmcl** [comment]
@balthisar unfortunately another very short `tidy` working day, but this seems the **perfect** use of `auto`...

To me `auto` sort of means tidy should do the **right thing**, baring user intervention... although I know some options where that is **not** exactly `true`... perhaps most notably `--vertical-space auto`, but probably others...

And in a quick pull, build and regression testing, the changes become very **minimal**, which again to me is a very **good thing**... and 100% maintains configuration options, which is why it was also oddly chosen in `vertical-space`...

Yes, I understand the **nu** warning, but still wonder why it thinks it should warn me about mapping to **XML 1.0** when validating my **HTML**, that's all... no biggie...

Glad you agree on adding the `Issue #XXX` in certain code fix cases... and on the principal that tidy should strive to **not** output known **invalid-for-doctype** html, where possible...

Will try to find time soonest to cycle back to `tidy`... thanks...

**Comment by balthisar** [comment]
Okay, it's active in next.

**Comment by geoffmcl** [comment]
@balthisar done review... but note it is now **after the fact**, just minutes ago...

Checked out branch `issue_476`, pulled and built tidy-5.5.43.I476, and re-run the regression tests. First with the tests `next` branch. Seems we get differences in just 4 cases...

 - 1266647 - txt and html - now [709](https://sourceforge.net/p/tidy/bugs/709/) 
 - 676156  - txt and html - now [316](https://sourceforge.net/p/tidy/bugs/316/)
 - 678268  - txt only - now [319](https://sourceforge.net/p/tidy/bugs/319/)
 - 688746  - txt and html - now [333](https://sourceforge.net/p/tidy/bugs/333/)
 
Seems each of these cases dealt with some early problems with utf-8 encoding... that particular issue remains solved, but each case had a comment containing consecutive `-`, which previously tidy would change to `=` signs...

In one case, 678268, it `identifies` itself as `xhtml`, and tidy does the substitution, and the only difference in the txt message output changes the message content -

```
-line 3 column 17 - Warning: adjacent hyphens within comment
+line 3 column 17 - Info: tidy replaced adjacent "-" with "="
```

In the other 3 cases, the document does not `identify` itself as a **legacy** document, so current tidy will stay in html5 mode and correctly **not** make the change... so there is a difference in the `html` output. But I find the change acceptable...

And of course, the previous `warning` of the type below is dropped -

```
-line 1 column 5 - Warning: adjacent hyphens within comment
```

Again, after this careful review I find **all** differences **acceptable**, and thus the `testbase-expects` should be **updated**...

Then checking out the tests `issue_476` branch, and it seems **all** these differences have been addressed...

Accordingly, fully agree with merge PR #615 here, and [22](https://github.com/htacg/tidy-html5-tests/pull/22) there in tests, and adjust respective versions...

Will be out for a little, but when back will re-check the results...

Thanks @balthisar for this great effort...

**Comment by geoffmcl** [comment]
@balthisar have now re-tested `next`, 5.5.46, after merge, here and in `tests`, in Windows, and get a full **pass**... as expected...

Will try to catch up soonest with the new PR's... but a quick read of them all, without actual testing, and all look **good** to me...

Great job... thanks...
