### ISSUE TITLE
NppTidy2 quickref.html

### ISSUE THREAD

**Issue by ganego** [htacg/tidy-html5#481]
I'm sorry I write this here, but your repo for NppTidy2 has no bugtracker.

Your readme there states:
> Ideally add quickref.html which should be in the tidy-html5\documentation folder to the doc folder to Notepad++\plugins directory too, so you will have the correct documentation, and the "Show Config Help" option will show the documentation that applies to your version (rather than simply the latest on the web).

So if I understand this correctly I should put quickref.html to: `npp\plugins\doc\tidy-html5\documentation\quickref.html`.
But this will not work it will try to open github and even fail retrieving this url `https://w3c.github.io/tidy-html5/quickref.html`

Now I had a look at the old tidy2 plugin and the path for the help was: `npp\plugins\doc\tidy2\quickref.html` - if I put it there it works fine.

So the readme needs an update. I added a pull request with a fixed version in your NppTidy2 repo.
This leaves the default URL when the file was not found to be fixed.

EDIT: Another thing, the old configs have those lines:

> new-inline-tags: cfif, cfelse, math, mroot, 
  mrow, mi, mn, mo, msqrt, mfrac, msubsup, munderover,
  munder, mover, mmultiscripts, msup, msub, mtext,
  mprescripts, mtable, mtr, mtd, mth
> new-blocklevel-tags: cfoutput, cfquery
> new-empty-tags: cfelse

yours do not; are they still necessary?

**Comment by geoffmcl** [comment]
@ganego yes, seems I forgot to enable Issues there... now done...

Not sure what you ask about the `old` configs... the example you show seems to be where someone added some proprietary tags... and maybe some that tidy 5.3.14 now does support... not sure...

Anyway have merged your https://github.com/geoffmcl/NppTidy2/pull/1 ... thanks for this doc change...

But since at the moment this relates only to https://github.com/geoffmcl/NppTidy2 am closing this here...
