### ISSUE TITLE
Why does tidy format the '<' and '>' numeric operator?

### ISSUE THREAD

**Issue by elD1eg0** [htacg/tidy-html5#485]
When I use the operator "greater than" (>) or "less than" (<), it will replaced automatically by \&gt; and \&lt;
How can I solve this?

**Comment by balthisar** [comment]
Could you provide some sample HTML for context?

**Comment by elD1eg0** [comment]
<form class="full-height-container"
        flex=""
        id="patient-plan-form"
        layout="column"
        layout-fill=""
        name="planForm"
        ng-cloak=""
        ng-show="$ctrl.arePlansLoaded"
        novalidate=""
        rxms-patient-focus-me="{{($ctrl.isUpdateView && $ctrl.numOfActivePlans == 0)}}"
        tabindex="{{(!$ctrl.isUpdateView || $ctrl.patientContext ==2) && $ctrl.numOfActivePlans `&gt;` 1 ? 0 : -1}}">

**Comment by elD1eg0** [comment]
@balthisar  here below a part of my code

 ```
<form class="full-height-container"
        flex=""
        id="patient-plan-form"
        layout="column"
        layout-fill=""
        name="planForm"
        ng-cloak=""
        ng-show="$ctrl.arePlansLoaded"
        novalidate=""
        rxms-patient-focus-me="{{($ctrl.isUpdateView && $ctrl.numOfActivePlans == 0)}}"
        tabindex="{{(!$ctrl.isUpdateView || $ctrl.patientContext ==2) && $ctrl.numOfActivePlans &gt; 1 ? 0 : -1}}">
```

**Comment by balthisar** [comment]
I'll have a look...

**Comment by vinnydu** [comment]
Are there any news about it ?

**Comment by geoffmcl** [comment]
20200923: @elD1eg0 thanks for the issue, a little late to the party... but not sure I understand what the problem is?

In text, it is normal for `>` to be replaced with entity `&gt;`... and like `&&` to `&amp;&amp;`... etc...

And in `Tidy`, HTML code lines like -

```
<form class="..."
    rxms-patient-focus-me="{{($ctrl.isUpdateView && $ctrl.numOfActivePlans == 0)}}"
   tabindex="{{(!$ctrl.isUpdateView || $ctrl.patientContext ==2) && $ctrl.numOfActivePlans > 1 ? 0 : -1}}">
</form>
```

The attributes values are treated as normal text, and some replacements are done... How can tidy **not** do this?

Found a simple description - http://www.w3schools.com/html/html_entities.asp -  now while the `w3schools` is not the `W3C`, in this instance they appear to be correct... correct me if I am wrong...

Seek more definitive W3C RECS references... thanks...

Can you explain more... maybe there is a fixable issue here... or an `option`...

Look forward to further feedback, comments, code, patches, PR, ... thanks...

**Comment by geoffmcl** [comment]
20201111: @elD1eg0 there has been no further feedback, clarification, comments, in **YEARS**, so no option but to **close** this... do not know exactly what you want tidy to do here...

And that is despite the issue having about 19 emoji's, at this time... probably the most of any issue in `tidy` ;=))

In simple **text**, which the **value** of an attribute is, that following the `=` sign, usually encased in quotes, `tidy` **MUST** help in replacing `<` and `>`, and certain other chars, with **entities**. No other choice... read the docs referenced, and others... search "W3C use of `<` and `>`" for more...

Please feel free to re-open, or file a new issue, clearly explaining what you see the problem is... thanks..
