### ISSUE TITLE
Format <name> values of -xml-config in the same way as those of -xml-help

### ISSUE THREAD

**Issue by eric-brechemier** [htacg/tidy-html5#491]
In `tidy-help.xml`, the output of `tidy -xml-help`, the `<name>` values include the initial dash and the format of the expected value:

```
<name>-config &lt;%s&gt;</name>
```

while currently in `tidy-config.xml`, the output of `tidy -xml-config`, only the name of the option is included in `<name>` values:

```
<name>indent-spaces</name>
```

In order to be consistent with command-line options, the `<name>` values of configuration options should start with two dashes and be followed with the format of the value, for example:

```
<name>--indent-spaces &lt;%s&gt;</name>
```

**Comment by eric-brechemier** [comment]
I am not actually sure about the usefulness of the value format, which is always `%s` even for integer values. The name of the type may actually be more useful; I opened a separate issue for that: https://github.com/htacg/tidy-html5/issues/492

**Comment by geoffmcl** [comment]
Sorry., did not mean to do that... just clocked on the wrong button...

**Comment by geoffmcl** [comment]
@eric-brechemier as indicate in researching #492, the `-xml-help` and `-xml-config` are generated from different tables, which contain different levels of information about an option...

The `-xml-help` option is generated from a table local to `tidy.c`, namely `cmdopt_defs`, which, as the name implies, only lists all the single dash command line options supported by the console app. And that app `converts` those command line options, and passes the appropriate option into the library...

The `-xml-config` on the other hand is generated from the internal to libTidy `option_defs` table, which are all the config options supported by tidy. They can be used on the command line as double dash items, or placed in a config file.

As you know, and helped change, it is the combination of these two type of options, and two types of xml output, that are combined together by `xsltproc` to produce the tidy man page... Formally, there were two `OPTIONS` sections, now correctly only one... all the single dash, command line only, followed by all the double dash options, which can also be placed in a config file...

So I would have to ask **why** would you want the `<name>` values of `-xml-config` to be as those of `-xml-help`? What do we gain? What does it add? How would it be used?

Maybe I misunderstand something here... or got something wrong... please explain... thanks...

**Comment by eric-brechemier** [comment]
@geoffmcl Thank you for your analysis. The goal of the change is only to make the format more consistent. The same `<name` element, with the same purpose, has a different format for command-line and configuration options.

This is not a big deal, so feel free to close this issue if it is too much trouble to change.

**Comment by balthisar** [comment]
@eric-brechemier, conceptually they are different.

Strings generated by `-xml-help` are necessarily CLI switches, and CLI switches _always_ take a leading hyphen (although on Windows, I’d argue that they should accept a forward slash as well). CLI switches are part of the HTML Tidy console application, and not part of LibTidy.

Strings generated by `-xml-config` are _not_ CLI switches; they’re configuration options used by LibTidy internally. These can be specified in a configuration file, and/or can be set by name when writing your own programs linked to LibTidy. Their names don’t include the double hyphen. _However_ the double hyphen _is_ a signal to the console program that a configuration option is being specified on the command line.

So, there’s not really command line arguments, although they can be used as command line arguments.

For the man page (which looks awesome, by the way) or CLI help, showing the double hyphen is appropriate, but the `-xml-config` output can be used by LibTidy users, for example, to generate their own documentation where the double hyphen makes no sense, because their LibTidy-using program isn’t a CLI program.

It’s not too much of a bother to make the change; it would be rather easy, but conceptually they’re not the same, so I will close this.

**Comment by eric-brechemier** [comment]
@balthisar Thank you for the context.

> It’s not too much of a bother to make the change; it would be rather easy, but conceptually they’re not the same, so I will close this.

That makes sense.
