### ISSUE TITLE
Do not include options 'Used internally' in -xml-config output

### ISSUE THREAD

**Issue by eric-brechemier** [htacg/tidy-html5#494]
The option `gnu-emacs-file` should be removed from the output of `tidy -xml-config`. It is described as:

```
<description>Used internally. </description>
```

**Comment by geoffmcl** [comment]
@eric-brechemier thanks for raising this issue... 

I **too** would prefer this internal only option excluded from the [api](http://api.html-tidy.org/tidy/quickref_5.4.0.html#gnu-emacs-file) documentation...

One quick, crude, **fix** would be in the `ForEachOption` function in `tidy.c`. This then only effects `tidy.c` and does not involve the library...

```diff
diff --git a/console/tidy.c b/console/tidy.c
index 58d8ac3..6214f5a 100644
--- a/console/tidy.c
+++ b/console/tidy.c
@@ -755,6 +755,8 @@ static void ForEachOption( TidyDoc tdoc, OptionFunc OptionPrint )
         OptionDesc d;
 
         GetOption( tdoc, topt, &d );
+        if (strcmp(d.name, "gnu-emacs-file") == 0)
+            continue;
         (*OptionPrint)( tdoc, topt, &d );
     }
 }
```

This is because the `topt` is an **opaque** structure in `tidy.c`, and thus we can not just do a compare for its enumeraed value, `TidyEmacsFile`.

We could get the enumerated value using the lib function `tidyOptGetId( topt )`, but that feels worse than the above brute `strcmp()`...

Alternatively, a more general solution would be to modify `tidyOptIsReadOnly(topt)`... At present it converts the opaque structure to a `TidyOptionImpl* option`, and only checks that the option `parser` is NULL, so presently excludes `doctype-mode`, `TidyDoctypeMode`, another quasi option that is only used internally...

That patch would look like this -

```diff
diff --git a/src/tidylib.c b/src/tidylib.c
index f0457a0..f3d8b83 100755
--- a/src/tidylib.c
+++ b/src/tidylib.c
@@ -381,8 +381,10 @@ Bool TIDY_CALL          tidyOptGetDefaultBool( TidyOption topt )
 Bool TIDY_CALL          tidyOptIsReadOnly( TidyOption topt )
 {
     const TidyOptionImpl* option = tidyOptionToImpl( topt );
-    if ( option  )
-        return ( option->parser == NULL );
+    if (option) 
+    {
+        return ((option->parser == NULL) || (option->id == TidyEmacsFile));
+    }
     return yes;
 }
```

Of course, another idea would be to **not** store such used internally only strings in this `options` table, but then we would need to create another storage area, and provide get/set services... seems a much bigger job...

Seek comments, or other ideas which way to hop on this... thanks...

**Comment by balthisar** [comment]
Actually I have an open PR that surfaces `gnu-emacs-file` as a first class configuration option. Why anyone would want to use it is up to them, but in theory you can now specify it in your config, and there's a proper description for it.

It's a fairly large PR #504 and so some review is appreciated before I merge it.

**Comment by balthisar** [comment]
As this is merged, I'll close this issue. _However_ this was simply an expedient fix. Maybe we should open a new issue to expand the `_tidy_option` struct to include an internal flag. This would really only _hide_ the option, though, meaning that it would be a so-called "undocumented API," but maybe it's better than what we have now.

**Comment by geoffmcl** [comment]
@balthisar I do not think your merge really closes this... but maybe... but...

Why are you making a `Used internally.` value a **first class configuration option**? You yourself question why anyone would want to use it! Why would you want to replace the `input file name` with some other name? For what use case? That just does **not** make sense!

> simply an expedient fix ... but maybe it's better than what we have now.

Well all that we had was that it shows up in the tidy man page, but was clearly marked **Used internally.**. And I provided two simple solutions for that! Yes, it is only _hiding_ an option that was never meant to be part of the API.

We do have a **flag** to hide such options from the API, and we already `hide` one other, namely `--doctype-mode enum`.  You will see in #312 and later in #472, I even made sure tidy will not **crash** if passed this option... even if someone finds, and uses it... Are you going to suggest we also make this a **real** API option too?

Unfortunately, that particular method for hiding it can not be used for this `--gnu-emacs-file file` option, and I would certainly **not** suggest we just have yet another flag for such **hiding**, just for these, presently, two entries, especially since the code - `return ((option->parser == NULL) || (option->id == TidyEmacsFile));` - will do the same.

So I do **not** think of it yet as **fixed**! While the current description is relatively clear, I think it should make it clearer that this option alone will **do nothing**!... **And** supplying a file name will over-rule, destroy, break, the present sensible automatic action of Tidy to use the **input** file name... for use by GNU Emacs...

But would really prefer that we just _hide_ it! Already sugested in https://github.com/htacg/tidy-html5/pull/473#issuecomment-268329059

Again I would respectfully seek further comments, or other ideas which way to hop on this... thanks...

**Comment by balthisar** [comment]
Actually, I'm going to remove it from the configuration entirely, and append it to #507. I'll replace it as a configuration option with an accessor function. It will still be publicly available for API users, but no longer available as a configuration option.

Although I don't like the current fix, it was _morally_ the right thing to do, as the console application uses the config option directly, and we shouldn't have "secret" API's.

**Comment by balthisar** [comment]
And... done and pushed to `next`. I'll leave this open pending comment, but feel free to close.
