### ISSUE TITLE
Tidy Incorrectly discards TABLE start tag when in TABLE

### ISSUE THREAD

**Issue by ehlertjd** [htacg/tidy-html5#498]
Given the example html:

    <table>
    <table bgcolor=beige>
    <tbody>
      <tr>
        <td>TEST</td>
      </tr>
    </tbody>
    </table>

Tidy produces the following:

    <!DOCTYPE html>
    <html>
    <head>
    <meta name="generator" content=
    "HTML Tidy for HTML5 for Mac OS X version 5.2.0">
    <title></title>
    </head>
    <body>
    <table>
    <tbody>
    <tr>
    <td>TEST</td>
    </tr>
    </tbody>
    </table>
    </body>
    </html>

According to the [HTML5 spec](https://www.w3.org/TR/html5/syntax.html#parsing-main-intable) and this [fiddle](https://jsfiddle.net/kh9x77yx/) the parser should close the first table element, then re-process the second table element.

Expected result:

    <!DOCTYPE html>
    <html>
    <head>
    <meta name="generator" content=
    "HTML Tidy for HTML5 for Mac OS X version 5.2.0">
    <title></title>
    </head>
    <body>
    <table>
    </table>
    <table bgcolor="beige">
    <tbody>
    <tr>
    <td>TEST</td>
    </tr>
    </tbody>
    </table>
    </body>
    </html>

**Comment by geoffmcl** [comment]
@ehlertjd thank you for your issue...

Yes, given your sample html, I can confirm even that latest version 5.3.20 still unconditionally **discards** the second `<table ...>` reference...

And also agree with your assessment that browsers will probably just ignore the first entry, and for sure apply the background color on the second, like you showed in `fiddle`...

And in the general **aim** of tidy to produce html that will be browser rendered per the original, discarding the second, especially since it has an attribute, is a **bug**...

Further note that changing the order of the table entries will cause browsers to render the table in default style, again showing browsers may in fact be doing what you suggest, namely to close the first table, and render the second...

Also tidy's warning about a `missing <tr>`, then a later a second warning of `trimming empty <tr>` seems wrong...

The code change to just close the first table is quite trivial, but still trying to read and digest the W3R spec... help in that appreciated...

Meantime have pushed a **fix** to branch `issue-498`...

Would be appreciated if you, and others, can `checkout` this branch, and test... thanks...

**Comment by ehlertjd** [comment]
@geoffmcl Thanks for the update, your analysis and code change makes sense. I grabbed the issue-498 branch and ran it through a few more test cases around tables and it worked as I expected. I have not had a chance to run it against a larger data set however.

As far as the W3 spec goes, all I really got from that is: If there's an open table, treat it as if you had seen a close element, then reprocess the open token (which it looks like your code change does). I'm not sure how one could get into the "IN TABLE" insertion mode without having a table element on the stack of open elements, so I'm afraid I'm of no further help there.

**Comment by geoffmcl** [comment]
@ehlertjd thanks for testing the `issue-498` branch... I too have done some more testing and it still **looks** good...

As you may know, we are headed for a **new** release 5.4 very soon, and I was hoping to include this... but still reading and re-reading that W3C spec... still might, especially if we get some more testers read, test and agree... thanks...

**Comment by geoffmcl** [comment]
This felt so right, have now merged it, and closed this issue... thanks...
