### ISSUE TITLE
JTidy needs update

### ISSUE THREAD

**Issue by HassanAmmori** [htacg/tidy-html5#533]
I know this is not technically an issue, but since you have revived this awesome project, is it possible for you to also update Java port of tidy? It hasn't been updated in 7 years. It still works awesome, for most cases, but html5 specific tags require manual handling, which is not the easiest thing to do.

Anyway, thank you for reviving and maintaining this amazing project! Wish you all the best!

**Comment by geoffmcl** [comment]
@HassanAmmori thank you for your comment...

But exactly which JTidy are you referring to?

Searching around I found http://jtidy.sourceforge.net/ - https://sourceforge.net/projects/jtidy/ - but as you point out it seems little has happened there since about 2012... Maybe you were referring to some other site/source?

But also as you point out, a Java port of tidy is not technically as issue for here... You need to urge the JTidy maintainers to do an update...

But will leave this open for a while, in case there are further comments... thanks...

And yes, Grand-Daddy HTML Tidy is still **alive and well**, and we continue to try to **march** it forward... as best we can...

**Comment by balthisar** [comment]
Unless there are more comments in the next few days, I suggest closing this as unrelated to HTML Tidy.

**Comment by HassanAmmori** [comment]
@geoffmcl Those two are the same project :) Actually, there have been number of different maintainer of JTidy. This one has been the most active:
http://jtidy.sourceforge.net/

I have no idea why the maintainers have abandoned this project, since there is no real alternative in Java. I ended up running Tidy through command execution, but this is really inefficient way. Surely, one can do a lot with NekoHTML + JSoup, but they have been designed for different tasks, thus not everything is really doable.

Unfortunately my skills are not up to the level to write a Java port of C++ library. But you guys are doing an extremely amazing job maintaining this project. I bet a lot of people are grateful for what you are doing! I understand that you are probably not very interested in JTidy, that is perfectly understandable, but thank you anyway! You are awesome!

**Comment by geoffmcl** [comment]
@HassanAmmori thanks for confirming the JTidy project links...

Actually it seems I had checked out this projects a few years back, just to have a look...

But **nothing** has been pushed to this svn repo since Nov 2010, Rev: 1191... so it now seems **abandoned**...

As you point out this is a **complete** Java port, actually I would say **rewrite**, of the HTML Tidy C code, right down to supporting what looks like pretty close to the exact command line and configuration options as Tidy! Even copied the idea of a 'lexer' to extract tokens from the input stream... build up a DOM like node list.. pretty printing, with indenting... etc, etc, ... even adopting the same MIT license...

But since it **stopped** some 7 years ago, it has no html5 support... so that would mean now porting/rewriting all the html5 changes... a quite big task!... and like you, I am not up to the level of such a port, aside from the fact that I am not too interested in writing Java... despite all its fabulous claims...

It is much more that **JTidy needs update**! As indicated, identifying all the html5 changes in the C code, and then rewriting them in Java, would be quite a heavy job...

As @balthisar points out this is really completely **unrelated** to HTML Tidy, a C project, thus closing this... 

But thanks for the reminder of what is out there... and thanks for the compliments...

**Comment by QMG-kazala** [comment]
Someone did update JTidy! 😄 See https://github.com/jtidy/jtidy - "The new home of JTidy updated to work with HTML5 "

**Comment by geoffmcl** [comment]
@QMG-kazala thanks for the update on the `JTidy` link... 

Yes, it says `updated to work with HTML5`... so I downloaded the latest `jtidy-1.0.2.jar`... and while there may be some updates in handling HTML5... it seems somewhat incomplete... but maybe, with a new group maintaining it, it is a WIP?

Given say `<meta charset="utf-8">`, it will output a warning `<meta> lacks "content" attribute`... look like a html4 vs 5 issue...

And shows it does not like say `<!DOCTYPE html>`, will advise `Doctype given is ""`, and `Document content looks like HTML 4.01 Transitional`... 

But as I say maybe it is a **work in progress**... not trying to criticize, the effort... 

A `java -jar jtidy-1.0.2.jar -v` outputs `JTidy released on 2009-12-01`... maybe that should be `2019`... a simple typo... don't know...

As indicated, it is a `Java` **rewrite**, and completely **unrelated** to HTML Tidy, here, a C project...

**Comment by QMG-kazala** [comment]
jTidy is definitely a work in progress. No doubt about it. Html5 support means support for html5 specific tags was added, but that's it so far. 

Anyway, it seems project keeps evolving and there is a chance it won't end up like the previous one. So just wanted to let others know in case they're looking for Java version and they stumble upon this issue like I did :)

Thx @geoffmcl for giving jTidy a try. I experienced similar issues. I checked out their project and had a look around as there is hardly any documentation, but as I said, html5 support is at very early stage, so ended up reporting the issues. 🤞 

BTW, thx for good work! I used your lib in the past too :)
