### ISSUE TITLE
New libTidy for PHP planned?

### ISSUE THREAD

**Issue by Daijobou** [htacg/tidy-html5#536]
Hello. This is only a small question. **Is here a new version libTidy with HTML 5 support for PHP planned?**

command: # rpm -qa | grep tidy
plesk-php70-tidy-7.0.16-centos7.17021709.x86_64
plesk-php56-tidy-5.6.30-centos7.17012012.x86_64
plesk-php54-tidy-5.4.45-centos7.16032517.x86_64
libtidy-0.99.0-31.20091203.el7.x86_64

The library is now 8 years old. phpinfo() said: "libTidy Release 25 March 2009". 

My problem with Tidy. Code like 
`<a href=".."><div>text</div></a>`
 will be converted with tidy_repair_string() to 
`<a href=".."></a> <div>text</div>`
Since HTML 5 its allowed div-tag inside an a-tag thats now wrong and not useable for my project, because I need div-tag inside a-tag.

I must check HTML5 code coming from user input. <strike>As workaround I can set 'input-xml' => true to stop wrong convertion</strike> but I dont' know what side effect this maybe have. Thats not possible, its remove text without tags.

Can anyone help me here? :)

**Comment by geoffmcl** [comment]
@Daijobou I am afraid I do **not** know the exact answer...

I note @skynet and @sideshowbarker maybe touched on this way back at issue #26... and then @mcroiban with issue #91... then another PHP compile, from source, by @skynet in issue #190 and #235... and maybe others I missed...

It seems you need to build and install the Tidy shared library, and then compile PHP with `--with-tidy=/path/to/tidy/install`... but maybe the PHP source would also need to be updated to use the **new** tidy header names, etc... ie the glue code that joins them together...

So it seems all **doable**, from respective sources... I will try to find time to experiment... and once we have **current** modern Tidy compiled into, and working inside PHP latest, we would need to **press** the PHP maintainers to **update**!

Hope this helps... and could maybe help more if you have specific questions... thanks

**Comment by Daijobou** [comment]
Thanks for your answer.

I use plesk onyx which can handle and update multiple versions of php by self. Compile and add a own php version is not a problem, but I must it update each time for every new php5.x/7.x/7.1 release. A in-build release would be much nicer. :)

libtidy is a great library, I hope a release for HTML5 coming soon, maybe for 10. libtidy bday? :)

**Comment by geoffmcl** [comment]
@Daijobou I guess I am still missing some point here... whoa is me... sorry...

And thanks @skynet for the two +1's... that's appreciated...

**But what are you asking of HTML Tidy library?**

> a release for HTML5 coming soon, maybe for 10. libtidy bday? :)

Well, we have just recently released `5.4.0`, but still await various distros to catch onto that... we will do anything to help, encourage, help, push...

I agree, `libtidy is a great library`, and it continues to move forward... that last release addressed many problems, and the latest `next` branch, even more... and that will continue...

So, I repeat, **what can the HTML Tidy repo** do to **HELP**, especially with `plesk`?

I think the latest, at least the last release `5.4.0`, of Tidy, if not `next`, should be part of the latest `php5.x/7.x/7.1` releases, **but** what can we, as `HTML Tidy`, do to get there? Who to contact, notify, assist, push, explain, help, even yell at... ?

Any **help** appreciated... thanks...

**Comment by padraic** [comment]
You'd probably need someone to bring it up on PHP Internals mailing list and/or propose an RFC: https://wiki.php.net/rfc

You can find a list of current maintainers for the PHP extension here with contact details: https://pecl.php.net/package/tidy

**Comment by geoffmcl** [comment]
@padraic thanks for the links... the [rfc](https://wiki.php.net/rfc) certainly looks a good place to start, but maybe also directly contacting the [php-tidy](https://pecl.php.net/package/tidy) maintainers would also be good...

But first I wanted to see if I could (a) build the current PHP, and (b) then link it to Tidy, but am a little confused about the PHP source...

The last time I tried that seems a few years back with PHP version 5.6.9. That was from a tar ball. But it seems PHP has also moved on...

Now I find a GitHub repo - https://github.com/php/php-src - it seems the version jumped from 5.6 to 7.0, 7.1, and `next` 7.2, but is this v7 in any distributions yet? I think this is the source I should be using...

Checking Synaptic Package Manager in my Ubuntu 14.04 LTS only shows php 5.5.9, but this distro is now quite old, and I do need to update at some time... 

But in another machine running Ubuntu 16.04 LTS it show 7.0, so I guess I should target at least 7.0... Any thoughts, comment on this very welcome...

Then looking at the php_tidy.h, as suspected, it still includes "buffio.h" which is now named "tidybuffio.h" to avoid generic file name clashes... But since we have not really changed the API substantially, it looks like it should compile... Then looking at the other php glue code, tidy.c, again it looks like everything is still good... One of the benefits of trying to keep the HTML Tidy API consistent and stable...

So, as indicated, I will try to find time to compile PHP 7.0, making the required fixes in php_tidy.h and see where I get... would be appreciated if others also get the chance to try... 

As I say, it would be nice to approach the PHP-Tidy maintainers with something we know works... thanks...

**Comment by padraic** [comment]
@geoffmcl The best target is likely 7.2 as the next version (which I assume is master for now on the php-src repository, with 7.1 on the php-7.1 branch), but I would discuss it at minimum perhaps on the PHP Internals mailing list. Checking again, and my apologies, the PECL website lists the PHP4 extension so I would ignore that. The maintainers may vary. In reality, the tidy extension was bundled with the PHP source from PHP5 - you can find the current source here for the extension: https://github.com/php/php-src/tree/master/ext/tidy

**Comment by geoffmcl** [comment]
@padraic thanks for clarifying...

Have now cloned the `master` source, to **php-src**, in Windows, and there is no `next` branch... so at this point assume the `master` is 7.2, in that there are also `PHP-7.1.5`, `PHP-7.1.4`, etc back to `PHP-4.0` branches... but agree the best target at this time would be `master`, what ever the actual version it is...

And yes there is `php-src\ext` folder, with some 75 extensions, including **tidy**. And yes, there have been some updates to `php_tidy.h`, `tidy.c`, files  including the use of 'tidybuffio.h', if found... it seems the name of the main PHP-tidy maintainer remains as before from the PHP 4 PECL site...

However, in the PHP 7 tidy.c I can see he has a macro to `register` all HTML tags, and this list is from circa 2009 - **LOTS** of new tags were added in supporting html5... need to add some 30 plus... but really wonder **WHY** such a table would be needed in PHP tidy.c... what use is it put to...

I guess we do **need** to strike up a conversation with John Coggeshall, the author of this PHP 7 tidy.c module... or add something to one of the PHP mailing lists... or **both**...

If we could **eliminate** that table, and another about node types, then, as stated, the API to `tidy` a document rests essentially unchanged, and a rebuild of this PHP tidy extension, linking with the current shared libtidy.so.5 should work... no problem...

So at this moment this seems more like an issue to be filed with PHP, rather than anything HTML Tidy can do here...

Does anybody more interested in PHP want to take this on? As stated I would help where I can... thanks...

**Comment by balthisar** [comment]
Is there a bug in Tidy that prevents the PHP maintainers from including us? I'm not sure this should be an HTML Tidy open issue, but rather on PHP's tracker?

**Comment by da2x** [comment]
php 7.1, libtidy 5.4.0, and php-tidy in Fedora 25 work just fine. Fedora doesn’t apply any patches toeither libtidy nor php to build it. 

@Daijobou you need to update to libtidy 5.4.0. The version you have installed, 0.99, is ancient.  Contact your distribution, CentOS, and request that they update the package to the latest version. Keep in mind that CentOS has a very conservative package update policy. It’s likely to take years. You can install an updated package yourself, if you’re comfortable doing such tasks. If you want a similar distribution that ships up to date packages, consider Fedora. It has a similar software and security stack to CentOS but ships newer packages every six months.

**Comment by balthisar** [comment]
Looks like it was solved. If anyone comes back, feel free to reöpen this issue.
