### ISSUE TITLE
Forbid 'target="_blank"' without 'rel="noopener noreferrer"'

### ISSUE THREAD

**Issue by jfilter** [htacg/tidy-html5#548]
It's a security risk to use `target="_blank"` without `rel="noopener noreferrer"`. So I think it should give you a warning. 😉 

See also this rule from ESLint: https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-no-target-blank.md

**Comment by geoffmcl** [comment]
@jfilter thanks for the issue...

I am not so sure about a **security risk**, but certainly an interesting use of the `window.opener` property...

In the past I have used `target="_blank"` simply because I did not like the default behavior of replacing the current page... but these days write very little html...

At this time will just mark this with a `Technical Support` label, since I am not sure Tidy needs this `feature`... although it would not be hard to do...

I did some searching around the W3C sites, but could not find anything specific... advise if you, or others  find any **authoritative** links... thanks...

What do others think? **FUD** or **fact**? Thanks...

**Comment by AnrDaemon** [comment]
This is highly subjective request, IMO.
It MAY be a security risk, if you open a page belonging to a different domain, BUT normal browser will automatically break all connections between two windows in such case.
Adding to this, if I'm not mistaken. CSRF control headers are meant to prevent this scenario already.

**Comment by LWillms** [comment]
There are certainly cases where the behaviour against which @jfilter is warning is deliberate and wanted, in a company-internal application for example. 

It is with the real guns - not the guns do shoot people, but people use guns to shoot other people. The problem is not to own a gun, but he widespread attitude that "my neighbor is my enemy", to perceive the stranger as a threat instead of seeing a chance in her or him. 

This applies mutatis mutandis to computing, too.

**Comment by balthisar** [comment]
I recommend changing this to **Won't Fix**, but I'll leave it open for additional comment. No updates from the OP since May, and no vociferous support, and Tidy isn't a security appliance, so unless someone objects, I'll close this in a few days.

**Comment by mycatnamedweb** [comment]
Any help here please? :)

https://stackoverflow.com/questions/50884241/is-noreferrer-enough-to-secure-links
