### ISSUE TITLE
 Html 5 components support

### ISSUE THREAD

**Issue by no1xsyzy** [htacg/tidy-html5#569]
I am working with [vue.js](https://vuejs.org) and [this demo](https://jsfiddle.net/yyx990803/3p0j5sgy/) defines new tags (as components) and/or new properties. In addition, W3C has [Custom Elements specification](https://www.w3.org/TR/custom-elements).

So I want to ask if `tidy` is able to deal with custom tag name, or any method to ignore unrecognized tags/properties?

Reproducing:
Use `tidy` to check this:
```
<!-- component template -->
<script type="text/x-template" id="grid-template">
  <table>
    <thead>
      <tr>
        <th v-for="key in columns"
          @click="sortBy(key)"
          :class="{ active: sortKey == key }">
          {{ key | capitalize }}
          <span class="arrow" :class="sortOrders[key] > 0 ? 'asc' : 'dsc'">
          </span>
        </th>
      </tr>
    </thead>
    <tbody>
      <tr v-for="entry in filteredData">
        <td v-for="key in columns">
          {{entry[key]}}
        </td>
      </tr>
    </tbody>
  </table>
</script>

<!-- demo root element -->
<div id="demo">
  <form id="search">
    Search <input name="query" v-model="searchQuery">
  </form>
  <demo-grid
    :data="gridData"
    :columns="gridColumns"
    :filter-key="searchQuery">
  </demo-grid>
</div>
```

Expected:
> No warnings or errors were found.

Result:
> ...
> Tidy found 6 warnings and 1 error!

**Comment by geoffmcl** [comment]
@no1xsyzy thank you for your issue, but there are a few things I do **not** understand...

You did **not** give the version of Tidy used? The **new** option `--custom-tags yes` was only available from about 5.5.7, Mar 19, 2017... see [custom-tags](http://api.html-tidy.org/tidy/quickref_next.html#custom-tags)...

Nor did you give the configuration used?

So you say `Expected: No warnings or errors were found.`, but the sample given has **no** DOCTYPE so that is at least 1 warning, unless you add `--show-body-only yes`...

Then unless you are using a tidy later than 5.5.7, and added a config of `--custom-tags yes`, you will get an **error**, which is very clear, and explicit -

```
line 37 column 3 - Error: <demo-grid> is not recognized! Did you mean to enable the custom-tags option?
```

But even if you enable these two option, you will still get warnings about the attributes -

```
line 37 column 3 - Warning: <demo-grid> attribute name ":data" (value="gridData") is invalid
line 37 column 3 - Warning: <demo-grid> attribute name ":columns" (value="gridColumns") is invalid
line 37 column 3 - Warning: <demo-grid> attribute name ":filter-key" (value="searchQuery") is invalid
line 35 column 12 - Warning: <input> proprietary attribute "v-model"
```

I do not know any option to suppress the above warnings, but maybe I missed something... maybe other feedback would help...

Maybe we missed something, like attributes commencing with a `:` character can follow a `custom element`? Are there some reference links on that?

So if your issue `Html 5 components support` is about `custom tag/element` support, then please read #119, PR #514, maybe #225, and maybe others...

But with more information, we may be able to help more... thanks..

**Comment by no1xsyzy** [comment]
Okay, that makes sense. I just searched issues for keyword `component` but found no result. Didn't realize that `custom tag/element` is also a name for it.

**Comment by pwang2** [comment]
Just share my experience here. I was able to by pass it with some replacement hack in vim script. 
```vim
function! FormatVue()
   let winview = winsaveview()
   silent /<script>/+1,/<\/script>/-1 !eslint_d --stdin --fix --fix-to-stdout
   silent /<script>/+1,/<\/script>/-1 !prettier --stdin --single-quote
   silent /<style>/+1,/<\/style>/-1 !prettier --stdin --parser postcss
   silent /<template>/,/<\/template>/ !perl -pe 's/ :(?=(?:[^"]*"[^"]*")*[^"]*$)/v-bind:/g' -
   silent /<template>/,/<\/template>/ !perl -pe 's/ @(?=(?:[^"]*"[^"]*")*[^"]*$)/v-on:/g' -
   silent /<template>/,/<\/template>/ !bash -c "HTML_TIDY=$(dirname $(npm root))/.tidyrc tidy -"
   call winrestview(winview)
endfunction
```
I am using a self build 5.5.38 tidy with follow tidyrc. It works (most of the time)
```
output-html: 1
wrap: 100
indent: auto
indent-spaces: 2
indent-attributes: 1
wrap-attributes: 0
drop-proprietary-attributes: 0
drop-empty-elements: 0
sort-attributes: alpha
show-warnings: 0
strict-tags-attributes: 0
show-body-only: 1
tidy-mark: 1
quiet: 1
custom-tags: blocklevel
new-blocklevel-tags: g, path, rect, circle
```
