### ISSUE TITLE
Documenting releases

### ISSUE THREAD

**Issue by skynet** [htacg/tidy-html5#570]
Would be really helpful if we had a release log.

**Comment by geoffmcl** [comment]
@skynet you mean other than http://binaries.html-tidy.org/release_notes/5.4.0.html?

This of course is really just `$ git log since-a-date`, massaged a little...

It would be quite some work to extract the information, and present a neat summary of important changes, but could be done... 

Any offers? thanks...

**Comment by geoffmcl** [comment]
@skynet at least now added the [Release Notes](http://binaries.html-tidy.org/release_notes/5.4.0.html) link to [Releases](https://github.com/htacg/tidy-html5/releases)...

HTH...

**Comment by skynet** [comment]
Great!
