### ISSUE TITLE
how to drop specific tags?

### ISSUE THREAD

**Issue by truongminhlong1988** [htacg/tidy-html5#573]
Hi tidy, 
I have 1 html file which has both htm tag and <?php ?>
Can i drop php tag in tidied html file? I'm using C++ with version 5.2
Thanks you in advance

**Comment by geoffmcl** [comment]
@truongminhlong1988 I am not sure I understand your question exactly... if seems you want to drop `<?php ... ?>` tags, ie `node->type == PhpTag`, from a file...

Well the current console app, `tidy` does **not** have such an option... so that would be a `feature request` to add a **new** option... but I would question the **use case**...

But you say you are using C++... does that mean you are building an app using **`libtidy`**?

If that is the case, then **yes**, you can scan through the nodes, and **drop** any `node` you do not want to keep with [tidyDiscardElement](http://api.html-tidy.org/tidy/tidylib_api_next/group__Tree.html#gaa1157e1d6f918885ed790b558d88f7a6), before outputting the results... simple...

HTH. Please explain more if I missed the point... thanks...

**Comment by truongminhlong1988** [comment]
Thansk you for your response. 
I will try this option and inform you for the result

**Comment by balthisar** [comment]
No feedback, and not related to Tidy issue per se, so will close.
