### ISSUE TITLE
Configure to stop auto generate tag <html>

### ISSUE THREAD

**Issue by truongminhlong1988** [htacg/tidy-html5#578]
Hello there
I'm planning to write a C++ html-validating app using tidyhtml. 
I'm planning to do that by checking < html > node if they exist. 
When i called func tidyParseString(), tidy always generate <html> even though input file does not have <html>. I attached sample which is not html. Be careful, it's a virus
[SktlLKBq5JW.zip](https://github.com/htacg/tidy-html5/files/1165379/SktlLKBq5JW.zip)
My sample code are 
 ```
       tdoc = tidyCreate();                     // Initialize "document"
        ok = tidyOptSetBool(tdoc, TidyXhtmlOut, yes)
             && tidyOptSetBool(tdoc, TidyFixUri, no)
             && tidyOptSetBool(tdoc, TidyMark, no);  // Convert to XHTML
        if(ok)
            rc = tidySetErrorBuffer(tdoc, &errbuf);      // Capture diagnostics
        if(rc >= 0)
            rc = tidyParseString(tdoc, sFileContent.c_str());           // Parse the input
        if(rc >= 0)
            rc = tidySaveBuffer(tdoc, &output);          // Pretty Print
```
Is there a way to config tidy not auto-generate < html > tag? or make tidy failed to parse this file?
Thanks you

**Comment by geoffmcl** [comment]
@truongminhlong1988 thanks for your question...

Unfortunately, tidy has **no** configuration option to **stop** it adding `implicit` tags. That is what you have called `auto generated` tags. Some of these are added during `tidyParseString`, as you point out...

And potentially more could be added in `tidyCleanAndRepair`, and/or `tidyRunDiagnostics`, which you left out of your sample code... see full api [sample](http://api.html-tidy.org/tidy/tidylib_api_next/libtidy_04.html)...

Since one of the aims of **`libtidy`** is to **fix** badly formed html, we would be unlikely to add an option which would potentially generate badly formed, or incomplete, **html**... that seems against the purpose of the tool...

Wow, your sample is a **crazy**, potentially dangerous, ASP app, but we do not need that to demonstrate this addition of `implicit` tags. Run tidy on a simple html snippet like `<h1>Hello World</h1>` will do that...

But since you are planning to use the library in a C++ app, you could iterate through tidy's DOM like tree, using say this [sample](http://api.html-tidy.org/tidy/tidylib_api_next/group__Tree.html) code, and thus ignore any node you do not want... thus producing your own output...

What follows is my **DEBUG** output of the node tree, using the above html snippet, before and after `tidyCleanAndRepair` -

```
All nodes BEFORE clean and repair
Root
 StartTag html implicit
  StartTag head implicit
   StartTag title implicit
  StartTag body implicit
   StartTag h1
    Text   (11) 'Hello World'
All nodes AFTER clean and repair
Root
 DocType   PUBLIC
 StartTag html implicit
  StartTag head implicit
   StartTag meta implicit  name="generator" content="HTML Tidy for HTML5 for Windows version 5.5.31"
   StartTag title implicit
  StartTag body implicit
   StartTag h1
    Text   (11) 'Hello World'
```

See the `dbg_show_node` service... and note all `auto generated` tags are marked as **implicit**... 

Also note closing tags are **not** included in the Tidy tree... these are implied, as appropriate, by the indentation... 

So a **lot** more could be done code wise if you coded sort of an extension to the library for yourself... That is not link to the completed pre-built library, but included the library modules as part of your app... if you see what I mean...

Anyway, good luck, and HTH...

**Comment by truongminhlong1988** [comment]
Thanks you. That answers my question now. :)

**Comment by geoffmcl** [comment]
@truongminhlong1988 well the W3C [nu](https://validator.w3.org/) java validator [source](https://github.com/validator/validator) is available... so you can build and run the `nu.jar` locally...

Not exactly a linkable **library**... but could maybe be converted...

And it also has a web API... this python3 script [html5check.py](https://gist.github.com/akamch/1430166) written a few years ago... makes it easy...

There are probably others out there, but are not familiar to me... maybe others can help with this question... thanks...

**Comment by truongminhlong1988** [comment]
Thanks you a lot for your information. That is all i need. Really, thanks
you
