### ISSUE TITLE
(tech support) Blank lines?

### ISSUE THREAD

**Issue by shentino** [htacg/tidy-html5#581]
The pre html5 version, when it indented and separated block level elements like div and stuff, adjacent elements, like multiple p or li elements in series, were separated by a blank line when tidy was passed the -i option.

the html5 version however only indents them and does not leave blank lines between them.

How do I tell tidy to format like this:

<pre>
&lt;ul&gt;
  &lt;li&gt;foo&lt;/li&gt;

  &lt;li&gt;bar&lt;/li&gt;

   &lt;li&gt;baz&lt;/li&gt;
&lt;/ul&gt;
</pre>

instead of this:

<pre>
&lt;ul&gt;
  &lt;li&gt;foo&lt;/li&gt;
  &lt;li&gt;bar&lt;/li&gt;
  &lt;li&gt;baz&lt;/li&gt;
&lt;/ul&gt;
</pre>

and likewise for &lt;p&gt; and &lt;dt&gt; and &lt;dd&gt;?

**Comment by geoffmcl** [comment]
@shentino thanks for your question...

That extra line space is what is called `classic` mode, and is enabled by the option **--vertical-space yes**

Testing your sample, I get output -

```html
F:\Projects\tidy-test\test>tidy-5.5.31 -i --vertical-space yes --show-body-only yes input5\in_581.html
No warnings or errors were found.

<ul>
  <li>foo</li>


  <li>bar</li>


  <li>baz</li>
</ul>
```

Note the use of 3 back-ticks to suspend html interpretation in these issues... rather that using entities `&lt;` and `&gt;`...

Actual this looks like it added **two** newlines, which feels like a bug...

HTH.

**Comment by shentino** [comment]
I tried it on my end and it did't insert the blank lines, even with "--vertical-space=yes"

**Comment by shentino** [comment]
Weird.

If I use option "--vertical-space=yes" it ignores it, but if I use "--vertical-space yes" it puts two blank lines.

**Comment by geoffmcl** [comment]
@shentino well configuration options can only be used **one** of **two** ways -

 1. command line = preceded by two `--`, then option, plus a space, then the value
 2. in config file = option followed by colon, `:`, optional space and value
 
Note, neither method has an equal sign, `=`, and the **value** will depend on the `type` of option -

 - Boolean = value can be `y/n`, `yes/no`, `t/f`, `true/false`, `1/0`
 - AutoBool = value can be a `boolean` value, or `auto`
 - String = value will be a string
 - Enum = value will be one of an enumerated string
 
Can not immediately find where this is spelled out in the tidy [docs](http://api.html-tidy.org/), but it is clearly stated in the unix `man` file, because there is another type of command line option with a single dash, `-`, like say `-i`, which is the same as `--indent auto`, or `indent: auto` in a config file...

And you have to be **careful** with the use of double quotes. Adding `"--vertical-space yes"` will probably be ignored, because the double quotes would combine them into one option, when it should be `--option <space> value`, if you see what I mean...
 
So ok, you have learned `--vertical-space yes` works, **but** it presently adds **two** new lines, and as I mentioned that feels like a **bug**... that so called `classic` mode should only add one newline, in certain places, to preserve the prior tidy5 output...

I will try to get around to adding an issue for this, if you do **not** beat me to it... thanks...

But we have to document and verify that this `classic` mode, that is `--vertical-space yes`, or `vertical-space: yes` in a config file, also works on the `<p>` element, and maybe some others... maybe there are other subtle `pretty print` bugs here... thanks...

**Comment by geoffmcl** [comment]
@shentino thank you for this issue... as you suggest, it has been around for a while... 

Probably even since the `vertical-space` option was expanded from a simple boolean type, to an autoboolean type, and `PCondFlushLineSmart( doc, indent );` and `TY_(PFlushLineSmart)( doc, indent );` were introduced... see commit f6979787d150080e98e8e4b457fda9ec9439ec95, circa Jul 13, 2015...

Note that `--vertical-space auto` is a **special** case where nearly **all** newlines are **removed** from the output... see #231, but started in #228, and several other cross-referenced issues...

These need to be read, reviewed to appreciate this vertical space issue...

But `--vertical-space yes` is also mixed up with the **indent** option...

Given a simple input:

```html
<ul>
  <li>foo</li>
  <li>bar</li>
  <li>baz</li>
</ul>
```

With a config of `--show-body-only yes --show-info no --vertical-space yes` I get an output of -

```html
F:\Projects\tidy-html5\build\win64>tidy5 --show-body-only yes --show-info no --vertical-space yes F:\Projects\tidy-test\test\input5\in_581.html
No warnings or errors were found.

<ul>
<li>foo</li>

<li>bar</li>

<li>baz</li>
</ul>
```

Which is perfect. A single newline is added...

Now I add `-i` indent and get -

```html
F:\Projects\tidy-html5\build\win64>tidy5 -i --show-body-only yes --show-info no --vertical-space yes F:\Projects\tidy-test\test\input5\in_581.html
No warnings or errors were found.

<ul>
  <li>foo</li>


  <li>bar</li>


  <li>baz</li>
</ul>
```

So, in this case, it is the additional interaction with the `--indent auto` option that seems to add an additional newline...

That might be a clue to look for where this **extra** newline is added...

We need to also test `<p>`, `<dt>`, `<dd>`, ... and any other **elements** effected by this...

Appreciate any comment, patches or PR on this... thanks...

**Comment by geoffmcl** [comment]
@shentino discussion moved to #582, so closing this...
