### ISSUE TITLE
(tech support) Is there a system default config file?

### ISSUE THREAD

**Issue by shentino** [htacg/tidy-html5#584]
Is there a system wide location for a default config file?

Something like /etc/tidy.conf or something like that?

**Comment by geoffmcl** [comment]
@shentino thanks for your question...

The short answer if **NO**, there is **no** default config file...

But one can be set with the environment variable `HTML_TIDY`...

The relevant code in `console/tidy.c` is -

```
    if ( (cfgfil = getenv("HTML_TIDY")) != NULL )
    {
        status = tidyLoadConfig( tdoc, cfgfil );
        if ( status != 0 ) {
            fprintf(errout, tidyLocalizedString( TC_MAIN_ERROR_LOAD_CONFIG ), cfgfil, status);
            fprintf(errout, "\n");
        }
    }
```

And if you compile console `tidy` from source, then a **default** config file **can** be compiled into the app, through either `TIDY_CONFIG_FILE`, through the code -

```
#ifdef TIDY_CONFIG_FILE
    if ( tidyFileExists( tdoc, TIDY_CONFIG_FILE) )
    {
        status = tidyLoadConfig( tdoc, TIDY_CONFIG_FILE );
        if ( status != 0 ) {
            fprintf(errout, tidyLocalizedString( TC_MAIN_ERROR_LOAD_CONFIG ), TIDY_CONFIG_FILE, status);
            fprintf(errout, "\n");
        }
    }
#endif /* TIDY_CONFIG_FILE */
```

or through `TIDY_USER_CONFIG_FILE` -

```
#ifdef TIDY_USER_CONFIG_FILE
    if ( (cfgfil = getenv("HTML_TIDY")) != NULL )
    {
        // as above
    }
    else if ( tidyFileExists( tdoc, TIDY_USER_CONFIG_FILE) )
    {
        status = tidyLoadConfig( tdoc, TIDY_USER_CONFIG_FILE );
        if ( status != 0 ) {
            fprintf(errout, tidyLocalizedString( TC_MAIN_ERROR_LOAD_CONFIG ), TIDY_USER_CONFIG_FILE, status);
            fprintf(errout, "\n");
        }
    }
#endif /* TIDY_USER_CONFIG_FILE */
```

And note the **order** -

 1. TIDY_CONFIG_FILE
 2. Env HTML_TIDY, **or**
 3. TIDY_USER_CONFIG_FILE
 
And note the command line can also load a `-config <file>`, and the **last** config loaded prevails...

HTH.

**Comment by shentino** [comment]
I would like to convert this issue into a feature request:

* Add /etc/tidy.conf as a default value for TIDY_CONFIG_FILE
* Add $HOME/.tidyrc as the default value for TIDY_USER_CONFIG_FILE

The HTML_TIDY thing is getting added to my env vars right now

**Comment by geoffmcl** [comment]
@shentino ok, have added `Feature Request`, but not sure how much traction it will have...

First, any person that builds tidy from source can already build such a **beast** for themselves, just by setting `TIDY_CONFIG_FILE` **and** `TIDY_USER_CONFIG_FILE` during the compile... that is add -

```
$ cd build/cmake
$ cmake ../.. -DTIDY_CONFIG_FILE=/etc/tidy.conf [more options]
$ make
```

and bingo, it is done...

But also note, at present, setting `HTML_TIDY` in the environment will override any configured `TIDY_USER_CONFIG_FILE`... but that could be changed by removing the appropriate `else` in the code...

The second thing would be to decide what to do for the Windows build. Windows does not have a commonly accepted configuration folder like `/etc/`, and does **not** have a `$HOME` environment variable...

In modern Windows systems, while it is disputed by some, `$HOME` is generally accepted to be `%USERPROFILE%`, or a combination of `%HOMEDRIVE%%HOMEPATH%`, which will normally be `C:\Users\<user>\`... but have seen other projects also use `%APPDATA%`, ie `C:\Users\<user>\AppData\Roaming`... or `%LOCALAPPDATA%`, ie `C:\Users\<user>\AppData\Local`...

And a `global` thing like `/etc/` is probably `%ProgramData%`, or `%ALLUSERSPROFILE%`, usually `C:\ProgamData`, usually in a project name subdirectory...

But asside from this **choice** in Windows, where there is **no** strong established tradition for this, I have found this type of `built-in` config and/or rc file can be very **confusing** later... 

That is someone sets up a `/etc/tidy.conf` and/or a `$HOME/.tidyrc`, and over time **forgets** that they are effecting **every** run of tidy... leading to testing **confusion**... have seen this many times in other projects over the years... it is very hard to keep such silent behaviour **modifiers** in mind...

So you can see in general, I am not 100% for this feature, especially since it can already be done for your **own** build, and we do have the **enviroment** variable `HTML_TIDY`, but would be willing to listen to what others want...

Look forward to further feedback on this... thanks...

OT: Just a heads up - I will shortly be on vacation, without full computer access, until the middle of September...

**Comment by shentino** [comment]
In the case of $HOME, I'm sure that a platform-detecting #ifdef would work around that issue.

And in my opinion, something very obviously named /etc/tidy.conf is very clear on its purpose and hardly silent.  If enabled as the default config file for html tidy, 

Quite frankly to be honest, when I was looking for how to configure tidy myself, I went *looking* for /etc/tidyrc or /etc/tidy.conf before I even bothered reading the manpage for tidy.  That's mostly because stuffing config files with default options into a file in /etc is a very common convention in unix systems.

There is almost zero chance of confusion if one is familiar with unix conventions.  Someone having an issue because they forgot about this file would IMHO be guilty of PEBCAK and need a dose of RTFM.

It's possible, true, that this sort of convention only applies in unix and doesn't make much sense in windows.

**Comment by balthisar** [comment]
@shentino, it would be a simple fix to roll this out for Unixes by default, although as @geoffmcl pointed out, you can build it yourself with a `-DTIDY_CONFIG_FILE`, but I think this wouldn't address your real issue: this doesn't address the lack of a default `/etc/tidy.conf` file.

What would you want to see in such a file? The default is blank. I suppose we could provide a config file with every option commented out, but I'd have no idea how to package this for any of the Unixes besides macOS, and I wouldn't want to overwrite existing files during an `apt-get install` or whatnot. Controlling this in CMake if you build it yourself, though, should be fairly easy.

Also, as build this `tidy.conf` would only apply to console tidy; LibTidy doesn't check for this file itself, and so LibTidy-using applications wouldn't normally pick up these settings.

**Comment by shentino** [comment]
I'm not asking for a default config file to actually be created, by the way.

Only asking that tidy be changed to *look* for one.  There's a difference.

You don't need to do any packaging for the actual file, just set a default location for tidy to look.

Probably something as simple as a default definition

```
#ifdef ON_LINUX
#define TIDY_CONFIG_FILE "/etc/tidy.conf"
#endif
```

That's really all you guys would need to do to implement this.  We don't actually need the config file itself.  Naturally tidy should run with or without it.

Naturally if we add this as a default config location, you'd probably also want to update tidy's manpage to mention the file

**Comment by balthisar** [comment]
> Probably something as simple as a default definition

But that's already implemented! Look at `CMakeLists.txt`:

~~~
if (TIDY_CONFIG_FILE)
    add_definitions( -DTIDY_CONFIG_FILE="${TIDY_CONFIG_FILE}" )
endif ()
if (TIDY_USER_CONFIG_FILE)
    add_definitions( -DTIDY_USER_CONFIG_FILE="${TIDY_USER_CONFIG_FILE}" )
endif ()
~~~

For example:

```
cmake ../.. -DTIDY_CONFIG_FILE="/etc/tidy.conf"
```

Or:

```
cmake ../.. -DTIDY_USER_CONFIG_FILE="~/.tidyrc"
```

You're right: if this is enabled, the man page should reflect this. I'll see if there's a way to add this to the dox build phase based on one of these values being set.

I'm not sure what more you're asking for. Do you simply want to avoid typing the extra -D flag?

**Comment by shentino** [comment]
Yes, I'm asking for it to be made a default at this level by you guys, so that us downstream users and developers won't have to mess with it.

**Comment by balthisar** [comment]
Got it. I don't have a problem with that. Windows users probably won't care. Let's keep this open a bit to see if there's any reason any *nix users would complain. Given that default installations currently _don't_ build it out of the box, I can't imagine a scenario where some pre-existing files would suddenly cause unexpected issues.

**Comment by shentino** [comment]
That is indeed my point.  Obviously actually including a config file would change the packaging, but just specifying its default location would be much cleaner.

That said, a sensible prewritten tidy.conf would be a good idea in the future IMHO

**Comment by geoffmcl** [comment]
Accidentally posted my comment to #603, but is related, so will leave the mistake as is...

**Comment by balthisar** [comment]
`next` addresses this now, and Unix systems will support runtime config files directly by default, so I will close this. I'll leave #603 open, though, which discusses documentation.

**Comment by balthisar** [comment]
@shentino, although this issue is already closed, I'll add some more comments.

By default on Unix-like systems, tidy will now look in /etc/ and ~/ for some rc files. Because you're not building your own, though, you'll have to wait for a distro to pick it up (we don't control the distros), or for us to provide a binary (the next release is IIRC Nov. 23d).

No sample rc files will be provided, but I added new `-export-config` and `-export-default-config` that can be piped anywhere on your system for use as an rc file. If someone who is a CMake packaging expert wants to take advantage of these to provide default config files during install, I'll leave that to them, and happily accept a PR.

Because it's obvious that we poorly communicate how HTML_TIDY and all of these rc files are added, I've also added `-help-env` that clarifies things, and prints out current values, if any, for the env variable and the expected rc files.

Finally, man will reflect whether or not rc support is included, as well as rc file paths.

I hope you can build it and give it a try.

**Comment by shentino** [comment]
Getting it upstream (here) was a good first step.  From what I know distros don't tend to like tampering with the packages they distribute to their users unless needed to fix a bug (and usually they prefer to push upstream like here to have teh original developers fix them).  A new update will probably migrate downstream from you guys eventually once a release is made.

I've already pulled from master and plan to test it and use it locally if I get around to it.  I may also submit a request on my distro's bugzilla to ask them to pull your updates to their own repo.

You have my thanks for adding this feature, and I'm hoping that many more users will also find use for this feature.
