### ISSUE TITLE
Fuzz testing tidy-html5

### ISSUE THREAD

**Issue by mthorpe7** [htacg/tidy-html5#591]
I've been fuzz testing tidy with AFL recently, and come across a plethora of crashes/hangs (mostly revolving around invalid UTF8). I intend to fix these crashes, but I suspect each fix will be a different code change.

How would you like these fixes to be upstreamed? A single PR with a single commit, a single PR with many commits or many PRs with single commits?

**Comment by mthorpe7** [comment]
sample crash:

```
$ cat out/fuzzer03/crashes/id:000052,sig:11,src:000642,op:havoc,rep:2
<html xmlns:o="urn:schemas-minrosoft-com:office:office"X<?ody><table><img class="" /></table></body></html>
$ ./tidy-html5/tidy --force-output yes --show-warnings yes --tidy-mark no --word-2000 yes out/fuzzer03/crashes/id:000052,sig:11,src:000642,op:havoc,rep:2
line 1 column 1 - Warning: missing <!DOCTYPE> declaration
line 2 column 1 - Warning: inserting missing 'title' element
line 1 column 1 - Warning: <html> proprietary attribute "xmlns:o"
line 1 column 1 - Warning: <html> proprietary attribute "x"
[1]    41695 segmentation fault  ./tidy-html5/tidy --force-output yes --show-warnings yes --tidy-mark no  yes
```

**Comment by balthisar** [comment]
Thanks for taking this on, @mthorpe7!

> How would you like these fixes to be upstreamed? A single PR with a single commit, a single PR with many commits or many PRs with single commits?

It would be best to tie commits to specific, fixed test cases. If you have one large test case, then a single commit might be okay, but it depends on how "invasive" the fixes become. A single PR is okay, and commits that each resolve a specific issue are appreciated. If you prefer separate PR's, then that's fine, too.

@geoffmcl generally likes smaller PR's, and although he's on holiday now, he's generally _much_ more consistent in attending PR's than I am (I often disappear for months at a time due to other commitments).

**Comment by geoffmcl** [comment]
@mthorpe7 thanks for reporting, and as @balthisar says, PR's are **very welcome**...

Certainly, just trying your simple sample with the `--word-2000 yes` option does indeed segfault...

```html
<html xmlns:o="urn:schemas-minrosoft-com:office:office"X<?ody><table><img class="" /></table></body></html>
```

That particular problem can be avoided with the small patch -

```diff
diff --git a/src/clean.c b/src/clean.c
index 707e4d9..fc5ca31 100644
--- a/src/clean.c
+++ b/src/clean.c
@@ -1902,7 +1902,8 @@ void TY_(CleanWord2000)( TidyDocImpl* doc, Node *node)
             attval = node->attributes;
             while ( attval ) {
                 next_attr = attval->next;
-                if ( strcmp(attval->attribute, "xmlns") != 0 )
+                /* Issue #591 - take care of a NULL attribute */
+                if ( !attval->attribute || ( strcmp(attval->attribute, "xmlns") != 0 ))
                     TY_(ReportAttrError)(doc, node, attval, PROPRIETARY_ATTRIBUTE);
                 attval = next_attr;
             }
```

And also please checkout the patch proposed in #588. This was certainly one case where invalid utf-8 could cause a problem, hopefully fixed by that patch...

As @balthisar mentioned, I am still on vacation until mid Sept, so do not have time now, but look forward to your efforts to make tidy **crash/hang** free... thanks...

**Comment by geoffmcl** [comment]
Has anyone had a chance to test my suggested patch for at least the one `word-2000` issue? thanks...

And @mthorpe7 you suggest a **a plethora of crashes/hangs**... can you enumerate, give specific examples... thanks

**Comment by balthisar** [comment]
Added #622 with @geoffmcl's patch, which works nicely.

**Comment by balthisar** [comment]
Merged. @mthorpe7, since no support is required for your original request, I will close this. Certainly you are free to submit any type of PR's, and those will open new message threads as they happen. Thanks!
