### ISSUE TITLE
Memory leak parsing "<a><div><a href=1>"

### ISSUE THREAD

**Issue by ralfjunker** [htacg/tidy-html5#597]
Parsing this HTML with default options:

```html
<a><div><a href=1>
```

results in a memory leak.

The problem happens because https://github.com/htacg/tidy-html5/blob/a79458a0ef24b0082603caf4b2e56b542cd6a31c/src/parser.c#L1362-L1365 prevents the tag from being unset / freed.

Similar code is in https://github.com/htacg/tidy-html5/blob/a79458a0ef24b0082603caf4b2e56b542cd6a31c/src/parser.c#L1922-L1933 takes care to free the tag if it is not unset.

A similar else clause should probably be added above.

**Comment by geoffmcl** [comment]
@ralfjunker thank you for the issue... it caused me to turn **on** some memory diagnostics that I have not run for a **long** time, and indeed do find **several** `memory leaks`...

I had to further enhance my memory diagnostics to track them down... that I am in the process of doing...

But the particular case you point to does **not** seem to be one of them? 

First, the `parser.c[1362-1365]` lines are correct... the process of `TY_(UngetToken)( doc );` is **not** trying to discard and free a node. It pushed the `node` onto the lexer stack, by `doc->lexer->pushed = yes;`, and allows tidy to continue processing the current `token`, and that pushed node will be recovered, and dealt with on the next `GetToken(doc)`... Read the top of `lexer.h` for a bit of an explanation of this...

As you further point to `parser.c[1922-1933]`, that shows a case of a switch between using `UngetToken`, which will be later used, and `FreeNode` which completely destroys/frees the node...

So while I am not sure the code you point to is the problem, I am **sure** there appears to be some 16 memory leaks - from my additional memory diagnostic output, massaged with perl script, `shwtidymem.pl`, to give a **summary**, which is -

```
Remains 16 in HASH
# :cnt: address          size
 1: 74: 0000020AF9707860 136
 2:122: 0000020AF97087A0 136
 3: 36: 0000020AF9707FD0 2
 4: 13: 0000020AF970C750 136
 5: 97: 0000020AF9706DC0 136
 6: 38: 0000020AF9708050 2
 7:105: 0000020AF9706E90 136
 8: 49: 0000020AF9707540 136
 9: 41: 0000020AF9707470 136
10:115: 0000020AF97086D0 136
11: 39: 0000020AF97073F0 56
12: 24: 0000020AF97071C0 136
13: 37: 0000020AF9709AA0 5
14: 66: 0000020AF9707790 136
15: 35: 0000020AF9707340 104
16: 57: 0000020AF9707610 136
```

This seems to agree with the Windows CRTDBG module output -

```
Detected memory leaks!
Dumping objects ->
{427} normal block at 0x0000020AF97087A0, 136 bytes long.
 Data: <  p             > C0 16 70 F9 0A 02 00 00 00 00 00 00 00 00 00 00 
{420} normal block at 0x0000020AF97086D0, 136 bytes long.
 Data: <  p             > C0 16 70 F9 0A 02 00 00 00 00 00 00 00 00 00 00 
{408} normal block at 0x0000020AF9706E90, 136 bytes long.
 Data: <  p             > C0 16 70 F9 0A 02 00 00 00 00 00 00 00 00 00 00 
{400} normal block at 0x0000020AF9706DC0, 136 bytes long.
 Data: <  p             > C0 16 70 F9 0A 02 00 00 00 00 00 00 00 00 00 00 
{377} normal block at 0x0000020AF9707860, 136 bytes long.
 Data: <  p       p     > C0 16 70 F9 0A 02 00 00 F0 C5 70 F9 0A 02 00 00 
{369} normal block at 0x0000020AF9707790, 136 bytes long.
 Data: <  p      rp     > C0 16 70 F9 0A 02 00 00 90 72 70 F9 0A 02 00 00 
{360} normal block at 0x0000020AF9707610, 136 bytes long.
 Data: <  p     `pp     > C0 16 70 F9 0A 02 00 00 60 70 70 F9 0A 02 00 00 
{352} normal block at 0x0000020AF9707540, 136 bytes long.
 Data: <  p       p     > C0 16 70 F9 0A 02 00 00 F0 C5 70 F9 0A 02 00 00 
{344} normal block at 0x0000020AF9707470, 136 bytes long.
 Data: <  p      rp     > C0 16 70 F9 0A 02 00 00 90 72 70 F9 0A 02 00 00 
{342} normal block at 0x0000020AF97073F0, 56 bytes long.
 Data: <         i      > 00 00 00 00 00 00 00 00 10 69 9F 85 F6 7F 00 00 
{341} normal block at 0x0000020AF9708050, 2 bytes long.
 Data: <1 > 31 00 
{340} normal block at 0x0000020AF9709AA0, 5 bytes long.
 Data: <href > 68 72 65 66 00 
{339} normal block at 0x0000020AF9707FD0, 2 bytes long.
 Data: <a > 61 00 
{338} normal block at 0x0000020AF9707340, 104 bytes long.
 Data: <                > 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
{327} normal block at 0x0000020AF97071C0, 136 bytes long.
 Data: <  p      qp     > C0 16 70 F9 0A 02 00 00 10 71 70 F9 0A 02 00 00 
{316} normal block at 0x0000020AF970C750, 136 bytes long.
 Data: <  p             > C0 16 70 F9 0A 02 00 00 00 00 00 00 00 00 00 00 
Object dump complete.
The program '[0x2B54] tidyd.exe' has exited with code 1 (0x1).
```

This is of course using your sample snippet of html, with the default configuration...

As stated needed to enhance my **old** memory diag code, and add a WIN32 `crtdbg.h` and enable it, all added as `options` to `CMakeLists.txt`, and have done this in the new `memory-test` branch... this will soon be merged to `next`, since it is **only** diagnostics, which is **not** compiled into the release... 

And offers the possibility for at least enabling some of it in a `unix` build... any thought on that welcome... and/or other `unix` utilities for that...

Now to identify the **actual** memory leak locations, and **fix** them... at present they seem to be in the message reporting system, but not sure yet... any help appreciated... thanks...

**Comment by geoffmcl** [comment]
@ralfjunker you were **spot on**... thanks...

At that point in the code, if we are not storing the **node** with `UngetToken`, then we **must** use  `FreeNode` to discard and free the node, and added a warning about the `discard`...

There was also a problem in the `message/report` system, in that while `tidyMessageRelease` released all the components of a message structure, it failed to release the allocated 136 byte structure as well... just a one line fix.

Have pushed these two fixes to the `memory-test` branch. Would be much appreciated if people could checkout this branch and test more thoroughly, and report... thanks...

And @balthisar, maybe you could check my one line fix in `tidyMessageRelease`... thanks...

Will continue testing, but feel these **memory leaks** have now been **plugged**... appreciate futher testing and comments... thanks...

**Comment by geoffmcl** [comment]
The `memory-test` branch now merged to `next`, per #599, and deleted... bumped version to 5.5.40...

@ralfjunker hope you get a chance to pull and test `next` 5.5.40, and hopefully this can be closed... thanks...

**Comment by balthisar** [comment]
Closing due to merge...

**Comment by ralfjunker** [comment]
I can confirm that [55d287bc9d566dd0cf0cfe9633af88bca7c20d5c] fixes the leak. Many thanks!

Is there a test for this fix already? I could not find any.
