### ISSUE TITLE
Improve man page to reflect Unix config files

### ISSUE THREAD

**Issue by balthisar** [htacg/tidy-html5#603]
Per #584, if `-DTIDY_CONFIG_FILE` or `-DTIDY_USER_CONFIG_FILE` are used, the generated man page should reflect this.

I will look into what XSL tweaks are needed for implementation.

**Comment by geoffmcl** [comment]
@shentino, @balthisar, given the strong tradition of these two files, I have no objection to defaults being added to CMakeLists.txt, just for `unix`, and perhaps `macOS`... 

But avoiding such **defaults** for `WIN32`, or at least `MSVC`, although such users should still be able to define their own, using cmake `-D...` option, as now...

The code in tidy.c already checks for their existance, so I would further suggest **no** such files, either containing `nothing`, or `all` possible options, commented out, be added to the distribution. 

I do see adding perhaps a sample `tidy.conf`, and/or a `.tidyrc` to the repo source, but as indicated do **not** see it necessary that these files be added to the **install**, and thus **distribution**... but since this would be `unix` **only** also do not see a problem...

But these samples, if they contain a list of options, would then need to be updated as each **new** option is added, or changed... additional, albeit minimal, admin...

The docs could explain that while tidy will **look** for such defaults, in unix, will not complain if none are found...

Also note the present tidy.c coded order -

 1. TIDY_CONFIG_FILE
 2. Environment `HTML_TIDY` **OR**
 3. TIDY_USER_CONFIG_FILE
 4. command line `-config <file>`
 
Note the present **OR** between 2 and 3... not that there needs to be any change here... but the docs changes, additions, covered in #603, should make this clear...

I personally use environment `HTML_TIDY` in Windows a **lot**, so would certainly `burp` if this is broken...

But go for it... look forward to a PR for review... thanks...

**Comment by geoffmcl** [comment]
Oops, meant to post this the #584, but seems ok here...

**Comment by balthisar** [comment]
Just back here to remind myself _not_ to provide a default file for this, but I will add a new console function to generate a `tidy.conf.default` file upon demand. It won't require tracking new/deleted options because the API can be polled automatically.

**Comment by shentino** [comment]
Agreed.

And though I believe that providing a default config file will itself be with merit, it is a separate enhancement and should not be combined with this issue, it should be listed as a separate issue that depends on the other one.

**Comment by balthisar** [comment]
@shentino, really, it becomes a packaging issue. If you know how to work with CPack, then you're certainly welcome to issue a PR against our CMakeLists.txt, once I've added the generator to console.c.

I package macOS without CPack, so I can ensure there's a default config there.

**Comment by shentino** [comment]
My concern is more about not having two separate modifications combined into the same issue.

**Comment by balthisar** [comment]
#623 addresses this, and other related documentation issues, too.

**Comment by balthisar** [comment]
Man page work is live, so I will close this.

**Comment by shentino** [comment]
Thank for adding this feature :)
