### ISSUE TITLE
Minify HTML

### ISSUE THREAD

**Issue by sharpaper** [htacg/tidy-html5#628]
Is there any option to "minify" the HTML output?

**Comment by balthisar** [comment]
There's nothing specific for minifying HTML in tidy, although a combination of `vertical-space: auto`, `wrap: 0` and `indent: 0` will get you close to what you want. If you're using UTF8, then take a look at all of the entities options to make sure that Tidy's not converting things to entities.

Tidy isn't a Javascript interpreter, so it won't do anything to minify that.

**Comment by sharpaper** [comment]
> Tidy isn't a Javascript interpreter, so it won't do anything to minify that.

I wasn't thinking of javascript, but about removing all unnecessary characters from a HTML file (eg. white spaces between tags, comments, etc.).

**Comment by balthisar** [comment]
Oh, yup, consider `hide-comments: yes` in addition to the list above.

**Comment by geoffmcl** [comment]
@sharpaper, as @balthisar suggested, `vertical-space: auto` is the only type of `minify` we have...

And you might try adding `omit-optional-tags: yes` to the list...

Let us know whether this does what you want... thanks...

**Comment by sharpaper** [comment]
@geoffmcl It seems to work fine, thank you. I think it would be nice to have a single option `-minify` to group all these options in a single command. Something like `-minify is the equivalent of -option1 + -option2 + -option3`.

**Comment by balthisar** [comment]
@sharpaper, did you mean to re-open this, perhaps as a feature request?

I would hesitate to recommend a new option that automatically enables all of the other options because it would lead to inconsistency if the other options are used. If I `minify` and it enables `option-1`, then I also use `option-1: no`, then what's the correct behavior? Is the order we specify the option important? If set `option-1: no`, and then `minify`, do I honor the `no` or overwrite it?

Do you know about configuration files? You can invoke tidy with the `-config <file>` argument, and specify a file with all of your desired options, e.g., `tidy -config minify.config ~/html/myfile.html`, thus saving you the trouble of using all of the options individually.

**Comment by sharpaper** [comment]
@balthisar yes I closed the issue because I could solve my problem, but then I reopened it because I thought `-minify` would be a nice addition.

Personally I don't think this should cause much trouble. I think you are already dealing with these types of inconsistency, such as if users specify `--hide-comments yes --hide-comments no` in sequence. How do you deal with this case? I assume the last one is the one that will be used. You could just use `-minify` as a short-hand for `--option1 --option2 ...`, and override any option depending if it's specified before or after. This is also the behavior of other *nix tools as well.

**Comment by sharpaper** [comment]
Alternatively, if you don't want to add an additional command line option, you could at least add a section in the manual to describe how to minify a file. Since "minifying" seems like a rather useful/common application, you could add a section like this:

    MINIFY
        If you want to minify a file, use the options option1: yes, option2: no, etc...

**Comment by balthisar** [comment]
`You could just use -minify as a short-hand for --option1 --option2`

That's a good point. `-minify` as a CLI option rather than a LibTidy option, and there's precedent for that. It's something I think we might consider. Pinging @geoffmcl...

**Comment by geoffmcl** [comment]
Ambivalent...

So marking it as a Feature Request, and moving out the milestone...

**Comment by geoffmcl** [comment]
20201206: @sharpaper, as @balthisar suggested, I started out trying to construct a minify.conf file, but was not wholly satisfied... it so much depends on the **content** of the input html file... but here is what I got -

```
# minify config sample
vertical-space: auto
indent: 0 
wrap: 0
hide-comments: yes
omit-optional-tags: yes

# and possibly - depends on document?
bare: yes
clean: yes
drop-empty-elements: yes
drop-empty-paragraphs: yes
merge-divs: yes
merge-spans: yes

# IIF MS Word document
# word-2000: yes

# More??? Others??? Maybe even -
# show-body-only: yes
```

Of course, taking the meaning of `minify`, as applied to say javascript, then the `vertical-space: auto` is the most important option, since it removes **most** newline characters...

And given that it so much depends on the input document, I would hesitate adding just a tidy command line option, like `-minify`, as suggested... exactly what should it do?

I also hesitate adding to the docs, at the cost of bloating the `help` text, even if an appropriate place, and wording could be worked out, agreed... other than perhaps a brief link to **this** issue/discussion...

Anyway, given that there has been no further feedback here in over 3 years, am closing this, removing the `Feature Request` until something can be worked out, and dropping the milestone...

But, as always, look forward to further feedback... thanks...
