### ISSUE TITLE
Should tidySystemLocale be a libtidy api?

### ISSUE THREAD

**Issue by geoffmcl** [htacg/tidy-html5#639]
Should tidySystemLocale be a libtidy api?

This question came up in a different context, #637, and now openning the issue here, separately.

There have been some previous comments -

@geoffmcl wrote Oct 27, 2017 [comment 1](https://github.com/htacg/tidy-html5/pull/637#issuecomment-339973095)

But your discovery of one case of a malloc, and changing it to TidyAlloc, certainly raises some questions!

As far as I can see it is not used in the library, and is passing the allocated memory out of the library for the user app to free. It guards, and warns in its comments, that it can be null, while TidyAlloc will abort if it fails... quite different behaviour...

This raises the question what is this API doing in a HTML parsing library at all... but will raise that as a separate issue soonest... if/when I get the chance...

@jokester wrote Oct 28, 2017 [comment 2](https://github.com/htacg/tidy-html5/pull/637#issuecomment-340137285)

Oops, I misunderstood what `tidySystemLocale` really does. Its comment says `result: The buffer to use to return the string.` while in the code `result` passed in is ignored. Also I don't get the latter half: `Returns NULL on failure.` seems more likely to be part of `@return`.

If we consider the first half comment to be truth, not allocating memory here seems more consistent to me (`tidy.c` need to allocate it instead).

@geoffmcl wrote Oct 27, 2017 [comment 3](https://github.com/htacg/tidy-html5/pull/637#issuecomment-340182838)

Me **too!**, given its `confusing` comments, and that it only does `setlocal(...)`! Why is it in **libtidy** at all? If `tidy.c` needs to do this, and I am **not** sure it does, then it should do it **all**... It certainly does **not** seem required in Windows...

I would think that a user of a particular language would already have the console setup as desired, i.e. `stdout/stderr`, or could set it up differently, outside `tidy`, if need be... so maybe this API can be removed... 

This is the jist of the separate issue I was going to raise, but maybe can be dealt with here...

Maybe @balthisar will comment when he gets a chance, since I think he introduced this code as part of localization... part of commit 53f2a2da2, and maybe others...

@balthisar wrote Oct 28, 2017 [comment 4](https://github.com/htacg/tidy-html5/pull/637#issuecomment-340182838)

@jokester, @geoffmcl, that function signature is a monstrosity of bad design decisions, and perhaps its functionality should be moved to the console application.

As for the signature, we should supply a buffer and size from the console:

`void TY_(tidySystemLocale)(tmbstr buf, uint bufsize)`

This breaks current API, though, but since no one uses it except the console application, I'd say bite the bullet, pull the trigger, and make the change.

Now the question as to _why_ this exists:

- Tidy does some sorting internally, e.g., eventually using `TY_(tmbstrcmp)`. This is probably a good thing, because it avoids any locale-related sorting that a standard library might introduce.
- When I added localization, I did _not_ want to affect how Tidy sorts things (i.e., there was no audit on standard library sorting versus the use of Tidy's own sorting). The "safe" thing was to ensure that Tidy internally, always used the "C" locale despite the user locale, in order to work predictably.
- TY_(tidySystemLocale) therefore checks the user's locale without affecting the executable's locale, i.e., the console (and therefore the library) will always run with the C locale. This doesn't apply to LibTidy users, though, because LibTidy will run in its executable's locale.

Of course, Tidy needs to know the user's locale in order to set the language automatically.

As to whether or not we need to preserve the C locale in console Tidy... maybe not! But it was the "conservative" (safe) choice at the time.

I, @geoffmcl, will reply as a new comment... but certainly seek further feedback from others... thanks...

**Comment by jokester** [comment]
The change in #637 is based on my incorrect understanding, so personally a big +1 to make it better. I can think of a few issues around the current code:

1. `tidySystemLocale` is somehow risky: The comment says `without affecting the C locale` while I believe it *temporally* affects. User should be concerned of this, esp. in server or multithreaded environment.
2. inconsistencies of comment and actual code: the API is ignoring using `result` passed in as the comment says.
3. (now) caller is burdened to correctly `TidyFree` with global `TidyAllocator`.

If we are to preserve the existence of the API, I propose to mention the risk, and have the caller allocate memory. [this diff](https://github.com/htacg/tidy-html5/compare/next...jokester:fix-locale-memory-allocation) shows a possible fix.

**Comment by balthisar** [comment]
@geoffmcl, @jokester, you guys are misunderstanding what `setlocale` does and doesn't do:

## What `setlocale` does
- It doesn't configure a user's environment or do anything at all to affect the user's environment. Like @geoffmcl, says, the user already has that setup.
- It's used to _get_ access to the user's environment:
  - C programs are required to start in the C locale.
  - `setlocale` is how you sniff out the user's environment _and)...
  - `setlocale` is _also_ how you configure standard library behavior _for the executable_ (it does _not_ change the user's environment). There's no library function `getlocale`
  - No warning is needed, because `setlocale` is not affecting anything on a user's system, and Tidy is not itself multithreaded.
- Tidy has always used the C locale (Tidy predates a lot of modern efforts at being multilingual).
- Yet to set the user's language automatically, we need to use `setlocale` to sniff it out.

## How Tidy uses it
Here's how `TY_(tidySystemLocale)` works. It's documentation is perfectly fine if you understand how `setlocale` works, which is the issue here.

- `setlocale( LC_ALL, "" );` — this configures the standard library to inherit the user's environment. If we were using standard library sorting routines, for example, they would now sort by the correct means for a particular language. It may or may not return a string indicating the user's locale.
-`temp = setlocale( LC_ALL, NULL);` — definitely returns a string indicating the now set locale. This is why we know to set French if you're in French environment.
- `setlocale( LC_ALL, "C" );` — Restores the standard library behavior _for the executable_ (not OS) back to the C locale for the reasons stated above.

Are we square on how `setlocale` works now, and how it does _not_ affect the user's environment, and how it only affects the runtime environment?

## Tidy's stdlib use
That last point should be a bit unclear. What is Tidy using in the standard library that's internationalization sensitive? Is it even necessary to force Tidy to use the C locale as it's always done? Can we simply set the runtime locale to the user's locale?

I think the answer is _yes_. Tidy is using its own sorting comparitors, and nothing from the standard library. It's only sorting English strings at that (attributes), any they're not affected by different locale sorting mechanisms (which we're not using anyway). If we _were_ to offer internationalized sorting, then abandoning the C locale would indeed be the _right_ thing to do. Unless anyone finds a reason to object, then I suggest _we abandon the C locale_.

## Library rationalization
If we're not abandoning the C locale, then this functionality (but not necessarily this function) definitely belongs in LibTidy, because we need to offer a service to set Tidy's language _without_ affecting the C locale. However this function:
- Doesn't so that; you still have to set Tidy's language after sussing out the locale.
- Has a sloppy signature that, while convenient, is confusing.

## Suggestion
Delete the Library routine completely, and do this in tidy.c:

~~~
    tidySetLanguage( setlocale( LC_ALL, NULL ) )
~~~

This, of course, will set the executable to use the environment's locale, as well as configure Tidy to use that locale's language. This all assumes, of course, that we're not concerned with Tidy not using C locale.

Now I know I could have written the PR in about 25% of the time it took to write this explanation, but I think a correct understanding of what was being accomplished and what `setlocale` _does_ is an important learning exercise.

I think that we should follow the suggestion, and let Tidy run in the environment's locale. Alternatively, @jokester's diff does improve the function signature while preserving the C locale, except, the warnings are completely inappropriate and thread safety is not compromised at all.

**Comment by balthisar** [comment]
#640 created.

**Comment by jokester** [comment]
@balthisar Thanks for your thorough explanation (and patience), I missed some important bits in `man setlocale` and other locale related background 😓.

**Comment by geoffmcl** [comment]
@balthisar,

> Delete the Library routine completely, and do this in tidy.c:

Agree with this, thanks for the PR #640, **except** the `do this in tidy.c`!

Can this **auto** selection of the language, based on `setlocale(LC_ALL, NULL)`, be done in say `tidyCreate()`?

A writer of an app to use `libtidy`, like console `tidy.c` is, should **not** be burdened with `remembering` this extra step/api call...

And that would avoid having to add it to our simple [Sample Program](http://api.html-tidy.org/tidy/tidylib_api_next/libtidy_04.html)...

That would not stop application writers using the `tidySetLanguage( <lang> )` to set other than that selected by such an `auto` process, should they really want output in some other available language...

I have just done some crude, quick tests with my [sample2](https://github.com/geoffmcl/tidy-test/blob/master/src/sample2.c) app, and was great to read the messages in say french, or a little chinese... 

Of course, as always the console output looks `strange`, but when written to a file, and loaded in a sensible editor, saw the correct stuff... As I have now read in several places, the Windows console has almost no support of utf-8, unless you do some quite drastic changes... certainly **not** as simple as changing the codepage as some suggest... but that is another subject...

Just an idea to try to keep the use of `libtidy` as simple as possible...

**Comment by balthisar** [comment]
> Can this auto selection of the language, based on setlocale(LC_ALL, NULL), be done in say tidyCreate()?

That would have been nice, but the language is set in the global `tidyLanguages` structure, and the localized strings don't depend on a `TidyDoc` instance to provide context. This allows LibTidy to respond to string requests without the need to create a `TidyDoc`. This is probably better in the long run, because a lot of the console application strings are part of LibTidy, so are really strings that are global in context and not tied to a document instance.

**Comment by geoffmcl** [comment]
@balthisar yes, I am aware there **are** some purely `get string` api functions that do **not** depend on a `tidyDoc`...

But look at the console `tidy.c`, and our `sample code`, and my **several** tests in my `tidy-test` repo, the very first thing done is `tidyCreate`, whether it is needed or not... this is how we ask people to run the library... **get a `tidyDoc`**... 

And as in `tidy.c` if just outputing some strings, like `-help...`, in its many forms, will release that `tdoc` before exit...

If some user chooses to ignore that startup, and only use some pure `strings` api, then they would get the default language, unless they specfically set `tidySetLanguage( <something> )`, which to me seems ok... but this seems very unlikely `libtidy` be used that way...

And even one `Remarks` in the api docs, on one of the pure string functions makes it clear - "These are provided for documentation generation purposes, and probably aren't of much use to the average LibTidy implementor."

The main point is I do **not** want to add an extra **burden** on the **average** `libtidy` use! Force people to `remember` this extra step/api call! **Make** them add it to their app, if other than english is their `locale`...

It should be **automated** within the library. And as indicated, a user can choose to override that and directly use `tidySetLanguage`, but normally should **not** have to be concerned about this...

I still **vote** for removing `tidySetLanguage` from `tidy.c`...

**Comment by balthisar** [comment]
We could do it in `tidyCreate()`, and I'm not going to get into a war over it, but it concerns me because LibTidy clients aren't likely going to expect it. Say, someone running PHP-Tidy in French, and I'm _not_ certain that PHP gives anyone the option to change the language in their API. On the other hand, they need to grow with the times, and someone running French _should_ expect to see French results. Usually _you're_ the one averse to change!

Semantically I don't really like it, because all of the language strings are really library-level strings, and so set language becomes a library-level kind of setting. Tying it to the document really means I should be able to change the language on a TidyDoc level, meaning that as an API user I could tell one instance to be French, another instance to be Chinese, etc., but it doesn't really work that way. It _could_ work that way. Maybe it _should_ work that way? It would mean a lot of API changes to preserve the semantics of a document-level function, though.

The original Tidy writers did several things to preserve semantics where not needed. `tidyGetOption()` is defined as `TidyOption tidyGetOption( TidyDoc ARG_UNUSED(tdoc), TidyOptionId optId )` in order to preserve the semantics that an opaque `TidyOption` instance is actually bound to a particular `TidyDoc`, whereas when you poke into things, it's not related at all.

I suppose I could overcome my sincere belief in proper semantics with a very carefully worded indication in the documentation indicating that `tidyCreate()` both creates a document instance as well as _initializes the library for use_, including initial setup of locale (and other things that might accumulate over the years).

**Comment by balthisar** [comment]
I was actually throwing together a quickie update to the PR for this, but now we get undefined behavior when setting the language in `tidyDocCreate` because even if using `tidySetLanguage` as an API user, that choice is overridden next time we create a TidyDocument, which resets it to the locale language every time.

I'll need a bit more time, rather than a quickie fix.

**Comment by balthisar** [comment]
Okay, dirty fix is quickie fix. Have a look at the updated PR.

**Comment by geoffmcl** [comment]
@balthisar sorry, but I only just noted you did **not** do exactly what you **suggested** in the above comment, in the PR, namely -

```
    tidySetLanguage( setlocale( LC_ALL, NULL ) );
```

My reading of `$ man setlocal` this does **exactly** what we want -

```
    If locale is NULL, the current locale is only queried, not modified.
```

Why in the PR are you using `""`, which does indicate **modification** can occur, but maybe not important... somehow still prefer the `NULL`... maybe this is what you meant, but somehow typed `""` thinking they are the same...

I would imagine say a french PHP-tidy user would be upset if tidy messages stayed in english, unless the  `PHP<-->LibTidy` **glue** code, which does `tidyCreate`, was changed to include a `tidySetLanguage`... and the same for **all** `LibTidy` clients... 

You're right, I am **against** change that causes **each and every** client to add something which can equally be done in the library `tidyCreate()` function...

As to adding `Bool manually_set;` to the structure, I do not feel this is **necessary**, but have **no**  problem with it... and the additional functions to manage it... seems messy overkill, but no prob...

I would think that a `libtidy` user who wants to set a language other than the `locale` would have no problem repeating the `tidySetLanguage`, should they also have the **need** to create another `TidyDoc`... already an unusual, special case...

And also have no problem with the `tidyCreate` doxygen comment change to satisfy your `semantic` sensibilities ;=)) 

I might even add something like - "`tidyCreate` should be the **first** call, before **any** other api calls, whether they use the `tdoc`, or **not**" - or **not**... I have always considered it implied **initialize**, but nothing wrong with explicitly adding, stating it...

Are we good to go? thanks...

**Comment by balthisar** [comment]
@geoffmcl, I think we're good to go. Only read on if you want to!

 I'm using `""` instead of `NULL` precisely to ensure that the execution environment locale is set during `tidyCreate`; there's not really any sense in querying it only, unless we wanted to ensure that the stdlib stays in C locale. Since we're not really using any internationalization from the C locale (sorting, calanders, etc.), we might as well set LC_ALL, and if we ever implement something locale-related, we need to honor it. One possibility I'm not worried about right now might be if that standards start allowing non-ASCII attribute names; users might then want non-C sorting.

The defense flag is absolutely required. If the environment is French, `tidyCreate` will set French. The library user (say, running tests in the default English locale but using a French environment) sets `tidySetLanguage`, and then next time he uses `tidyCreate` his preference would be wiped out!

Comparing the user's environment again as a guard (rather than an internal flag) is fragile because the user's environment can conceivably change. Yes, it's an edge case, but this hardens against it.

**Comment by geoffmcl** [comment]
@balthisar oops, seems I should have tested more before speaking...

In Windows `setlocale( LC_ALL, NULL )` just returns `C`, which is **not** what we want...

`setlocale( LC_ALL, "" )` returns `English_United States.1252`, which is what we want...

So, at least in Windows, `""` is what is needed... sorry for the mix up...

Not against your `defense flag`, but still question the **reasoning**, and **need**, but **not** important...

Let's get it done... thanks...

**Comment by balthisar** [comment]
@geoffmcl, yup, that's a confusing topic. `NULL` is the only case where something isn't _set_. C programs per specification _always_ start with the C locale, which is why your test returns C. This is the execution locale that Tidy uses today, right now, whether we set a language or not. That will change with this PR, though.

When using `""`, you are doing two things: 
- Setting the execution environment to use the user environment's current locale.
- _And_ returning what that user environment is currently configured to.

Now if you really want to confuse things, LC_ALL might not be the best choice. Users _can_ (but don't often) use LC_ALL, but it's perfectly possible to mix and match. I prefer LC_TIME and LC_MEASUREMENT set to `en_GB.UTF-8` so that I get sensible ordering of dates and sensible units of measurement.

I'll merge that, and close this. Thanks.
