### ISSUE TITLE
Tidy 5.6.0 -> bug with pre tag

### ISSUE THREAD

**Issue by ogolovanov** [htacg/tidy-html5#690]
Hello.

Input: `"<html><body><pre>Результат</pre></body></html>"`
Config: `array('input-encoding' => 'utf8', 'output-encoding' => 'utf8');`

Result after clean-repair:
`...`
`<pre>? езультат</pre>`
`...`

It seems tidy does not like cyrillic letter "Р" in pre tag ...
If i replace it with another letter -> result will be ok. ( sorry, but thats not funny ).
If i remove "input-encoding" and "output-encoding" option -> result also will be ok ( sorry, but thats not funny too, because those options have 'utf8' as default value )

**Comment by ogolovanov** [comment]
Also, question please.

Why there is no ".deb" package for tidy 5.6.0?
Thanks.

**Comment by geoffmcl** [comment]
@ogolovanov I have **big** trouble with utf-8 in my windows machine... but was able to test in linux... and I do not see any problem...

The input file has the hex sequence `D0 A0 D0 B5 D0 B7 D1 83 D0 BB D1 8C D1 82 D0 B0 D1 82`, which is valid utf-8...

After running it though `tidy` the ouput remains exactly `D0 A0 D0 B5 D0 B7 D1 83 D0 BB D1 8C D1 82 D0 B0 D1 82`... no change...

Nothing is changed if I add `--input-encoding utf8 --output-encoding utf8`, since these are the defaults... so can not duplicate the problem... 

Of course I was testing with the latest `5.7.3` tidy, but there have been **no** encoding, decoding changes inbetween..

And regrettably, we do not add a `*.deb` packages any more, since 2016. It is usually easy for unix/linux users to build and install from the git source... sorry...

And sorry unable to **duplicate** the problem, so can do **nothing** at this time... maybe if you explain more, other samples, etc... thanks...

**Comment by geoffmcl** [comment]
@ogolovanov as stated **unable to duplicate**, and no further feedback in over a month... closing this...

Please feel free to re-open, or file a **new** issue... thank...
