### ISSUE TITLE
How to ignore specific warnings

### ISSUE THREAD

**Issue by displayadrian** [htacg/tidy-html5#699]
I've read the documentation and trawled through forum posts but I still can't figure this out.

Is there an easy way to configure tidy to ignore specific warnings when used along with SublimeLinter?

Previously this could be done using SublimeLinter's ignore_match function but that has been removed in a recent update.

Thanks

**Comment by geoffmcl** [comment]
@displayadrian glad you asked this question. It gives me a chance to describe some **new** options, introduced from version `5.6.0`... I know nothing about `SublimeLinter`, but in this case I do not think it is needed...

See [mute-id](http://api.html-tidy.org/tidy/quickref_next.html#mute-id). This takes a comma, `,`, separated list of `IDs` to `mute`...

Use `--mute yes` to show the `IDs` to add to the comma separated list...

Example: Input of just "Hello world" and just using `-q --mute yes` by default you will get, excluding the `html` -

```
line 1 column 1 - Warning: missing <!DOCTYPE> declaration (MISSING_DOCTYPE)
line 1 column 1 - Warning: plain text isn't allowed in <head> elements (TAG_NOT_ALLOWED_IN)
line 1 column 1 - Warning: inserting implicit <body> (INSERTING_TAG)
line 1 column 1 - Warning: inserting missing 'title' element (MISSING_TITLE_ELEMENT)
```

Then running tidy with `-q --mute "MISSING_DOCTYPE,TAG_NOT_ALLOWED_IN,INSERTING_TAG,MISSING_TITLE_ELEMENT"` on the same input you will get **nothing** but the html...

Remove the `-q` will show you several `Config:` and `Info:` type messages, showing what will be `muted`...

```
Config: messages of type "MISSING_DOCTYPE" will not be output
Config: messages of type "TAG_NOT_ALLOWED_IN" will not be output
Config: messages of type "INSERTING_TAG" will not be output
Config: messages of type "MISSING_TITLE_ELEMENT" will not be output
line 1 column 1 - Info: <head> previously mentioned
Info: Document content looks like HTML5
Tidy found 4 warnings and 0 errors!
 then the html, 
 plus the usual "About HTML Tidy: ..." info messages...
```

Hope this answers your question... thanks...

**Comment by displayadrian** [comment]
Thanks for the response. What I'm hoping to do is permanently suppress false positives which are highlighted throughout our documents.

Tracking codes in URLs is a good example of this:

![image 2018-03-19 at 5 58 46 pm](https://user-images.githubusercontent.com/32849679/37613296-906a8782-2b9f-11e8-8f07-432b25ee317b.png)

SublimeLinter's user preferences lets us pass command line options to tidy. Do you think we could use the mute/mute-id functions to suppress these particular phrases?

**Comment by geoffmcl** [comment]
@displayadrian as indicated, know nothing about `SublimeLinter` so can not answer that... only you can try...

But this now seems to be a repeat of #691, #310, and maybe several others...

As stated there, and now again, `tidy` is primarily for `[x]html`, and can **not** be expected to do a good job on `templates` which are not yet valid `html`... sorry...

Tidy, more or less by accident, can get past some `template` structures, where they conform close enough to **html**, but it can not ignore what it sees as an invalid URI in a href... you can use `--fix-uri no` to tell it to leave it alone, but it **has** to warn that it is **not** yet valid...

And simularly `entities`. Tidy recently had many new valid `entities` added, now over 2000, and again due to the nature and purpose of `tidy` it has to warn about others found not in the list... These can **not** just be ignored...

So we seem to come back to the **purpose** of `tidy`!

Unless I am really misunderstanding something here, you seem to be asking tidy to be something it is clearly **not**...

Have provided some way tidy can be configured. Within the constraints given advise what more tidy should do... thanks...

**Comment by ler762** [comment]
@geoffmcl it would be nice if --mute also muted the explanation

for example: --mute MISSING_ATTRIBUTE
would also suppress the
  The table summary attribute should be used to describe
paragraph at the end.

$ tidy -indent --tidy-mark no --mute MISSING_ATTRIBUTE tidy-stc.html
Config: messages of type "MISSING_ATTRIBUTE" will not be output
Info: Doctype given is "-//W3C//DTD HTML 4.01 Transitional//EN"
Info: Document content looks like HTML 4.01 Strict
Tidy found 1 warning and 0 errors!

The table summary attribute should be used to describe
the table structure. It is very helpful for people using
non-visual browsers. The scope and headers attributes for
table cells are useful for specifying which headers apply
to each table cell, enabling non-visual browsers to provide
a meaningful context for each cell.

For further advice on how to make your pages accessible
  <.. snip ..>

**Comment by geoffmcl** [comment]
@ler762 seems I missed this comment...

Well we already have `-q`, `-e`, and `--show-info no`, as already described... what more can I add...

@displayadrian, since this seems a repeat of others, and feel question asked and answered, closing this... thanks...

**Comment by wsfulton** [comment]
Small, but important correction to https://github.com/htacg/tidy-html5/issues/699#issuecomment-374298143,

> Use `--mute yes` to show the `IDs` to add to the comma separated list...
> 
> Example: Input of just "Hello world" and just using `-q --mute yes` by default you will get, excluding the `html` -

Should be:
> Use `--mute-id yes` to show the `IDs` to add to the comma separated list...
> 
> Example: Input of just "Hello world" and just using `-q --mute-d yes` by default you will get, excluding the `html` -
