### ISSUE TITLE
Breaks microseconds after call tidy_repair_string

### ISSUE THREAD

**Issue by alexeygon** [htacg/tidy-html5#771]
Problem: after call tidy_repair_string function, there is no microseconds in DateTime.
Code to reproduce:
```
$dateTime = new \DateTime('2014-04-11T22:20:45.571Z');
$microseconds = $dateTime->format('u');
echo $microseconds . PHP_EOL;

tidy_repair_string('some string...');

$dateTime = new \DateTime('2014-04-11T22:20:45.571Z');
$microseconds = $dateTime->format('u');
echo $microseconds . PHP_EOL;
```

Actual: 
```
571000
000000
```

Expected:
```
571000
571000
```

Versions:
```
PHP Version => 7.1.23-4+ubuntu18.04.1+deb.sury.org+1
tidy

Tidy support => enabled
libTidy Version => 5.6.0
libTidy Release => 2017/11/25
Extension Version => 7.1.23-4+ubuntu18.04.1+deb.sury.org+1 ($Id: c6d6b80d55c5d351deaa745c3c540971e5583c24 $)

Directive => Local Value => Master Value
tidy.clean_output => no value => no value
tidy.default_config => no value => no value
```

**Comment by geoffmcl** [comment]
@alexeygon thanks for the issue... 

But at this moment this looks more like a PHP implementation problem, rather than anything to do with `libtidy`...

Yes, the `tidy_repair_string('some string...');` code will run `libtidy`... 

But how can this effect the PHP `DateTime` function?

Maybe with more information, feedback, comments,... this will become clear... thanks...

**Comment by balthisar** [comment]
PHP issue, so closing.
