### ISSUE TITLE
Trailing backspace removed

### ISSUE THREAD

**Issue by petko** [htacg/tidy-html5#856]
Why are trailing spaces like the following removed by TidyHtml?

```
<body>
<p>text </p>
</body>
```

The trailing space after text will be removed. If it is replaced with `&nbsp;` it will be preserved.

What config option determines that and is it possible to leave the spaces intact?

**Comment by geoffmcl** [comment]
@petko thank you for your issue... 

But I do **not** understand quite, exactly, what you are asking... maybe I don't understand... explain...

Part of `Tidy` is in the name... tidy equals, in DOM/like text nodes... are trimmed of trailing spaces... and indeed leading, other spaces... there are exceptions...

Is there an option to **preserve** this space... in some xhtml cases, yes, to some extent... but otherwise **NO**... 

It is important that such spaces do not change the browser rendering of the paragraph...

So one is forced to ask, why do you want this `space` preserved in the output... what is the **use** case?

In testing, considering, have expanded your sample, to my  [in_856.html](https://github.com/geoffmcl/tidy-test/blob/master/test/input5/in_856.html), to included other `<p>` cases, where trailing/leading/interword **spaces** are `removed`, where required, to conform to a browser rendering of this sample... but **not** touched, removed in other cases, like the `<pre>` block, ...

But maybe I do not understand your issue... please elaborate... thanks...

**Comment by petko** [comment]
I am migrating some texts, which are used in WYSIWYG text editor. In the old version of the software they are stored as RTF files and in the new - as HTML (after cleaning the produced files using HTMLTidy). Such texts sometimes contain leading or trailing whitespace, which are deliberately put there by the user.

So when they are imported in the new software, they no longer are the same texts, they are missing that whitespace.

**Comment by geoffmcl** [comment]
@petko thanks for the further feedback...

Ok, you changed the version of your text editor, but I still do not understand what you want `tidy` to do... or **not** do... and, just out of curiosity, what editor is that... what os?

**All** version of `tidy` remove unused 'spacey' characters... from html... where allowed, possible... as part of the `cleaning` process... has done that since its creation... 

There is little chance of adding an option to prevent that... even if fully defined...

More to the point, what would be the `use` case for such an option... what are its full `specs`... etc...

> Such texts sometimes contain leading or trailing whitespace, which are deliberately put there by the user.

Assume by `user` here, you mean the creator of the html code... why would they **deliberately** do that?... and want it kept? ... seems unreasonable...

Hmmm, as you point out, if it is replaced with `&nbsp;` it will be preserved... a html user/generator/editor knows, or should know, that... so does `tidy`...

Still do not understand your issue... please elaborate... thanks...

**Comment by petko** [comment]
My initial confusion comes from the fact that https://validator.w3.org with the Clean HTML option enabled does not remove these spaces. But probably they used an older/alternative version of Tidy HTML.

As for `&nbsp;` being preserved, while a pure space is not, I admit that I don't know the reason behind this. Until now I've had the impression the single space and `&nbsp;` are equivalent, but probably I am wrong.

I will just replace spaces with `&nbsp;` in that case..

**Comment by geoffmcl** [comment]
@petko, seems no actual issue for tidy identified... that I can see... and no new comments in over a year...

So am closing this... 

Please add further feedback, if I am wrong... or open a new issue... thanks...
