### ISSUE TITLE
HTML Tidy website does not render propertly when using HTTPS

### ISSUE THREAD

**Issue by ericpruitt** [htacg/tidy-html5#867]
The HTTPS version of the [HTML Tidy](https://www.html-tidy.org/) website fails to render for me on Firefox and Chromium:

```
$ firefox-esr --version
Mozilla Firefox 68.5.0esr
$ chromium --version
Chromium 79.0.3945.130 built on Debian 10.2, running on Debian 10.3
```
![tidy-website](https://user-images.githubusercontent.com/481184/75099049-ff3bdc80-5571-11ea-86b8-87e9bcf167d4.png)

Google, at least in my results, links to the HTTPS version of the site by default, so the broken site may be receiving a fair amount of traffic from.

**Comment by ler762** [comment]
On 2/22/20, Eric Pruitt <notifications@github.com> wrote:
> The HTTPS version of the [HTML Tidy](https://www.html-tidy.org/) website
> fails to render for me on Firefox and Chromium:

The site needs to fix the stylesheet references:
<link rel="stylesheet"
href="http://www.html-tidy.org/assets/stylesheets/base.css">
<link rel="stylesheet"
href="http://www.html-tidy.org/assets/stylesheets/site.css">

FF work-around:
Click on the tracker icon (to the left of the URL bar)
Notice that under Connection it says
Firefox has blocked parts of this page that are not secure
Click on the right arrow
Click on Disable protection for now

**Comment by geoffmcl** [comment]
@ericpruitt, @ler762, sorry for the long delay...

I just tested **both** the http:// and https:// for www.html-tidy.org, in Windows 10, using Chrome, and MS Edge, and in linux using Firefox, and while I do see some minor rendering difference between browser, **ALL** seemed to, in general, correctly render the site...

The main difference being the rendering of the centered circled images on the separator lines - Chrome and Edge have no image, just a sort of grayed circle, while Firefox shows a Heart, Book, Building, etc... but no real difference between unsecured/http, and secured/https links...

Has this somehow been fixed? Can this issue be closed?

**Comment by ericpruitt** [comment]
Yeah, it looks like it's been fixed. I just checked again on Chromium and Firefox, and the site renders correctly on both.

**Comment by balthisar** [comment]
Sorry. I fixed it some time ago, and didn't close the issue. Thanks for having reported it.

**Comment by geoffmcl** [comment]
@ericpruitt thanks for re-testing and closing this issue...

@balthisar thanks for fixing the https default, back in June, 2020...

There remains a few minor issues with the https://www.html-tidy.org...

   1. In some browsers, in some OSes, the centered circles, on the dividing line, fails to show an image!
   2. The reported security issues reported by Github... https://github.com/htacg/html-tidy.org, and on others...
   3. I can no longer do `jekyll build`, on a local updated clone of the site...
   
The first, `1.`, is hard to exactly pin down, like if fails in Chrome in one windows 10 machine, but works ok in another windows 10 machine, with the same verion of chrome! BAH!! 

In my Ubuntu linux, it can fail on a local load of `$ firefox index.html` to review the site...

I will try to insert an image here, but if note there is copy at http://geoffair.com/tmp/div-blank.jpg
![div-blank](https://user-images.githubusercontent.com/1333435/93637126-58c79500-f9f5-11ea-8b66-1169cb81172a.jpg)

But as stated, it is quite a minor browser rendering problem, so no biggie ;=))

The second, `2.`, seems to occur now and then, on the html-tidy.org, and several other of our sites... and in the past you have done multiple commits for this...

Can you again do your magic... or explain to me how to effect this... Or perhaps **DISABLE** the `dependabot` checking even... 

But it is just an annoying `nag`, so I suppose can mostly be ignored...

On the third, `3.`, it has been many years since I tried a local site build, back in 2015 in fact, and I guess my Ubuntu 18.04.5 LTS may need some `gem/ruby/jekyll` updates, or something...

There are 2 `jekyll` scripts in my system -

   * /usr/local/bin/jekyll
   * /usr/bin/jekyll
   
Since my `$PATH` includes the first, before the second, it reports - `/usr/bin/env: 'ruby1.9.1': No such file or directory`, since it starts with `#!/usr/bin/env ruby1.9.1`...

I tried several apt installs, like jekyll, ruby, gem, ... etc to see if that fixes the prob., but still **NO GO**!!!

And running `$ /usr/bin/jekyll build` throws out many errors lines, which end with `(Bundler::GemNotFound)` ???

It is not important that I be able to update the repo, and review the build locally... but it is nice to have, before you push a change...

Any assistance on getting this to build would be appreciated... thanks...
