### ISSUE TITLE
Tidy 5.6.0 mangled html / php code.

### ISSUE THREAD

**Issue by somebadhat** [htacg/tidy-html5#872]
WINDOWS 10 64-BIT. 

HTML Tidy for Windows version 5.6.0 TURNED: 

`<img src="start-menu<?php echo date("mdy")?>.jpg" width="1248" height="1663" border="0" alt="StartMenuSCREENSHOT WILL BE HERE TOMORROW">`

INTO: 

`<img src="start-menu%3C?php%20echo%20date(">.jpg" width="1248"
height="1663" border="0" alt="StartMenuSCREENSHOT WILL BE HERE
TOMORROW"&gt;`

USING THIS COMMAND: 

tidy "21.php"> 22.php

I do not understand your documentation: 

`you are advised to make the start tag explicit and to use PHP, ASP, or JSTE code for just the attributes`

Should I alter the command, alter the code, or not use tidy?

Somebadhat

**Comment by michaelsmoody** [comment]
I'm curious, if you slightly change this to:

`<img src="<?php echo 'start-menu' + date('mdy') + '.jpg' ?>" width="1248" height="1663" border="0" alt="StartMenuSCREENSHOT WILL BE HERE TOMORROW">`

Does it work more cleanly for you?

**Comment by geoffmcl** [comment]
@somebadhat, well even my browser trips on your src URI/HREF...

The href `src="blah..."` can not contain `date("")`, ie inverted comma repeated in quoted string...

So the second suggested by @michaelsmoody does ok, because he changed that to `date('mdy')`...

But in either case Tidy treats the `src="xxx"` as a URI, and does its best to convert it, and does badly, in the double double quotes case...

If this is a *.php source, then it should first run through the servers php, to get the text, of the URI... removing `<!php ... ?>` element...

HTML Tidy is **NOT** the tool to run on `php` source. Maybe you have already worked this out, since there has been no further feedback, replies...

So closing this, since there appears to be no Tidy problem exposed... maybe I am wrong...

Feel free to te-open, with some new information, or open a new issue... thank...
