### ISSUE TITLE
Tidy gets confused with u tags and underline styles

### ISSUE THREAD

**Issue by dmoylan** [htacg/tidy-html5#890]
I have a document I'm trying to clean with these settings in Tidy 5.6:

[
                'clean' => true,                                      
                'add-meta-charset' => true,
                'join-styles' => true,
                'coerce-endtags' => true
            ]

After cleanup extra sections of the document are being affected by a text-decoration: underline style that was converted from u tags.  The decoration is getting applied to parent nodes.  I'm attaching a gzipped version since I can't attach an HTML file.

[a13-9784_1ex4d2.htm.gz](https://github.com/htacg/tidy-html5/files/5110767/a13-9784_1ex4d2.htm.gz)

**Comment by geoffmcl** [comment]
@dmoylan, sorry, can not find where Tidy `gets confused`...

First, I had to add `new-blocklevel-tags: document, type, sequence, description, filename, text` to your config, to even get Tidy to write an output doc... still get `Tidy found 222 warnings and 0 errors!`... and the last 2 in your config are the defaults, I think, so no need to add those... always use the minimum in config...

In your 260K doc, seems the first `underline` sample is `<U>Exhibit&nbsp;A</U>`, which Tidy outputs as `<span class="c20">Exhibit&nbsp;A</span>`, and given there is `span.c20 {text-decoration: underline}`, do not see any confusion here???

The next, is `<U><FONT style="FONT-SIZE: 10pt" size=2>Certain Terms Defined in this Indenture</FONT></U>`, is output as `<span class="c22">Certain Terms Defined in this Indenture</span>`,and given `span.c22 {FONT-SIZE: 10pt; font-size: 80%; text-decoration: underline}`, do **not** see any problems here...

I am afraid I do not have the time to meticulously search this doc, over 1200 lines, for possible errors, especially where the "The decoration is getting applied to parent nodes.". 

There might be some, if so please point them out, by extracting the paragraph, and create a small sample, where the problem is repeated... is repeatable... thanks...

Need to exactly track down, and identify the problem, to make this other than a discussion...

Look forward to further feedback, discussion, samples, patches, PR, etc, on this... thanks...
