### ISSUE TITLE
Tidy can't deal with <中文> XML tags

### ISSUE THREAD

**Issue by jidanni** [htacg/tidy-html5#913]
`<?xml version="1.0" encoding="UTF-8" standalone="no"?><Lands><國有><土地標示部><縣市>臺中市</縣市><鄉鎮市區`…
causes
`$ tidy -xml #5.6`
to say
> Tidy found 0 warnings and 34089 errors! Not all warnings/errors were shown.

Despite it being [allowed](https://www.w3.org/International/questions/qa-non-eng-tags).

**Comment by geoffmcl** [comment]
@jidanni thank you for your issue...

Can you please give a small, complete, valid xml **sample** file, for testing, understanding, exploring, etc...

And to avoid any copy/paste issues, please **zip** the sample file, and attach the **zip** to this issue - just drag and drop it into your comment...

The first step is to have a solid, repeatable sample... to even begin to look into this... thanks...

**Comment by jidanni** [comment]
[b_1646.xml.gz](https://github.com/htacg/tidy-html5/files/5605300/b_1646.xml.gz)

**Comment by geoffmcl** [comment]
@jidanni thank you for adding a valid xml sample... 

But for future reference that sample could have been reduced to just a few lines... with just one multi-byte Unicode tag, like `<縣市>anything</縣市>`... that would really assists the debugging effort...

In debugging I now think this is related to issue #878 ...

Since tidy **incorrectly** encodes a multi-byte Unicode **start** tag, into the lexer, and copied into the node, the tag later can **not** be match to the correctly encoded same multi-byte **closing** tag, with catastrophic, cascading, errors thereafter...

I am so sure this is the issue here, I am closing this, until #878 is solved... any help in that appreciated...

But for sure will re-open this, if it turns out not to be the case... thanks...

**Comment by jidanni** [comment]
> But for future reference that sample could have been reduced

Oh I thought you wanted a real life one.
