### ISSUE TITLE
tidy says this misplaced </dl> is OK

### ISSUE THREAD

**Issue by jidanni** [htacg/tidy-html5#917]
tidy says this misplaced `</dl>` is OK,

[BAD.txt](https://github.com/htacg/tidy-html5/files/5743273/BAD.txt)

OK, I fixed it on my own....

[GOOD.txt](https://github.com/htacg/tidy-html5/files/5743275/GOOD.txt)

(Yes, you could say it was junk after the `</dl>`, but from my point of view, it was a misplaced `</dl>`)

I had to change .html to .txt to upload them to GitHub.

HTML Tidy for Linux version 5.6.0

**Comment by geoffmcl** [comment]
@jidanni, glad you found, and fixed the missing/misplaced `</dd></dl>` manually...

But there is nothing `tidy` could do about this issue... since just about anything can be placed in the last open `<dd>` tag...

Of course, loading the `BAD.txt` in a browser makes it visually obvious, in that all the tags following the last open `<dd>` tag are indented...

But as stated, `tidy` can not `guess` when it should have been closed... 

So, closing this...

PS: You can also `zip` a sample file, rather than renaming it, to include it in an issue...

**Comment by jidanni** [comment]
Just looking at the bottom of the file, three lines,
```
 </dd>
</body>
</html>
```
one can see it is invalid HTML.
Tidy letting invalid HTML sail through, is setting a dangerous precedent!
Sure, we want our documents to be tidy.
But before starting to tidy things, first check if the thing is valid HTML. Please.
E.g., perltidy would not barge ahead and attempt to tidy perl that had syntax errors in it.

**Comment by geoffmcl** [comment]
@jidanni, well, if you are talking about the `BAD.txt`, in the one I downloaded, there appears to be **no** problem in the last 3 lines - a hex dump shows -

```
0000:06e0 2D 3E 3C 2F 70 3E 0A 20  3C 2F 64 64 3E 0A 3C 2F -></p>. </dd>.</
0000:06fe 62 6F 64 79 3E 0A 3C 2F  68 74 6D 6C 3E 0A       body>.</html>.
Completed [BAD.txt] = 1790 Bytes.  Sat Feb 13 14:53:50 2021
```

It **ends** with a `0x0A` linefeed!

And even if there was some `text` after the closing `</html>` tag, `tidy` would probably just move it up to inside the `<body>`... as will some browsers...

Perhaps the **big** difference between other code `linters`, and `tidy`, is that, as you should know, `tidy` does not out rightly stop at the first detected HTML code error, but makes every attempt to try to **fix it**, which, as we both know, can lead to **wrong** fixes, since it can not know the author's intention... and sometimes does this `silently`... i.e. without a warning or error output...

As indicated, at this time, this issue does **not** expose anything `tidy` should do differently... so remains closed...

**Comment by jidanni** [comment]
I am saying a closing DD tag, with no following closing DL tag, means that...
it's just like some kid running around without any parents looking after it.
DD's only live inside DL's. Without a closing DL tag, the whole thing is
in nuclear meltdown and tidy should sound an alarm. Clearly tidy is
asleep here.
