### ISSUE TITLE
How to disable error limit?

### ISSUE THREAD

**Issue by geeljire** [htacg/tidy-html5#93]
I noticed that tidy returns about 14 errors/warnings at a time. If there are more, it just ignores the rest. How can you remove this limit?

**Comment by geoffmcl** [comment]
As you may know the current development is in the develop-500 branch -
$ git checkout develop-500
and issue can only be tested against this branch at present...

Have you tried the config option -
--show-errors 10000
or more if required ;=))

I guess it would be nice to perhaps have say a --show-errors -1 to disable this count check... 
does our config 'integer' parser correctly decode -1? DRAT, no, it checks for digits, 
and squawks about a '-' sign... well the comment on the ParseInt(...) is /* unsigned integers */
so that is expected...

So will have to think more about 'disabling', but meantime a LARGE integer should 
work... Hope you get the time to pull the latest, and advise...

**Comment by geoffmcl** [comment]
@geeljire, @balthisar, constructed a test with 26 errors, and by default only the first 6 are shown.

However, adding `--show_errors 10000` and all 26 are shown, so this achieves what is requested.

It is no longer necessary to checkout develop-500 branch. All the latest is now in the default master branch as we head for a 5.0.0 release...

I'll close this issue, but feel free to re-open, or open a new issue on any other problem. Thanks for reporting...
