### ISSUE TITLE
Outdated warnings

### ISSUE THREAD

**Issue by da2x** [htacg/tidy-html5#938]
The following warnings are outdated as all of these attributes are specified in the current version of HTML5.

* `<a>` proprietary attribute "[referrerpolicy](https://html.spec.whatwg.org/multipage/links.html#attr-hyperlink-referrerpolicy)"
* `<iframe>` proprietary attribute "[allow](https://html.spec.whatwg.org/multipage/iframe-embed-object.html#attr-iframe-allow)"
* `<iframe>` proprietary attribute "[loading](https://html.spec.whatwg.org/multipage/iframe-embed-object.html#attr-iframe-loading)"
* `<img>` proprietary attribute "[decoding](https://html.spec.whatwg.org/multipage/embedded-content.html#attr-img-decoding)"
* `<img>` proprietary attribute "[loading](https://html.spec.whatwg.org/multipage/embedded-content.html#attr-img-loading)"
* `<source>` proprietary attribute "[sizes](https://html.spec.whatwg.org/multipage/embedded-content.html#attr-source-sizes)"
* `<video>` proprietary attribute "[muted](https://html.spec.whatwg.org/multipage/media.html#attr-media-muted)"
* `<video>` proprietary attribute "[playsinline](https://html.spec.whatwg.org/multipage/media.html#attr-video-playsinline)"

**Comment by geoffmcl** [comment]
@da2x, thank you for the issue, and research...

When you say, `outdated`, sadly, that may well be **true**... can you give **W3C** ref link(s) for each... thanks...

Like, for the first, `referrerpolicy`, current `libTidy` does **not** have this attribute listed, see [Known HTML attributes](https://github.com/htacg/tidy-html5/blob/next/include/tidyenum.h#L1003), and the corresponding  [attribute_defs](https://github.com/htacg/tidy-html5/blob/next/src/attrs.c#L106) array, however I found the **W3C** [referrer-policy](https://www.w3.org/TR/referrer-policy/) link, and it seems this attribute should be supported on the `a, area, img, iframe, or link` elements, with an enumerated set of values, since at least 2017...

So would be relatively easy to **ADD** support... note the `warning` that the enum, and table **must** be in the **same** order... just add new items to the enum and array ends... see [ATTRIBUTES.md](https://github.com/da2x/tidy-html5/blob/next/README/ATTRIBUTES.md) for more details, but forget any **alphabetic**, or other, ordering, groupings... note, this `md` should be fixed, someday...

And, at this time, seems optional whether an `attrIsXXXX(av)` macro is added to `attrs.h`, but open about this...

Need the research, links, conclusions, ... for **each** case... and maybe a `use` sample, for testing... thanks...

Look forward to further feedback, comments, links, patches, PR, etc, etc... thanks...

**Comment by da2x** [comment]
I updated the above list with links to the relevant sections for each attribute in the current spec.

**Comment by geoffmcl** [comment]
@da2x, thanks for the updated list, with `whatwg` links... did not check all, but those inspected looked **good**... and it seems in most cases, `libTidy` does **not** presently have these attributes listed...

Now all we need are the patches, PR's, to **implement** this ;=)) to bring `libTidy` up-to-date... thanks...

See [CONTRIBUTING.md](https://github.com/htacg/tidy-html5/blob/next/README/CONTRIBUTING.md) for details of `forking`, keeping that `fork` up-to-date, creating, and presenting a [PR](https://github.com/htacg/tidy-html5/pulls), in a branch, etc... Ask here, if further help needed... thanks...

**Comment by drichardson** [comment]
>  Ask here, if further help needed... thanks...

@geoffmcl I've had the PR #949 opened for about a month now... is there anything else I need to do to get it reviewed?

**Comment by balthisar** [comment]
@drichardson, @geoffmcl is on sick leave; I'll get to it as soon as I can. It won't be closed, and I'm sorry I can't rush it, either, with a one month old son in the house!

**Comment by balthisar** [comment]
Closing as fixed via merge #949.

**Comment by Seirdy** [comment]
@balthisar This issue doesn't seem fixed; several attributes enumerated in the original filing don't appear to be supported, such as `referrerpolicy`
