### ISSUE TITLE
`<a><sub><a>text</a></sub></a>` should be legal

### ISSUE THREAD

**Issue by uu1101** [htacg/tidy-html5#95]
The following document:
~~~{.html}
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>TITLE</title>
  </head>
  <body>
    <a href="#ref">
      text here
      <sup>
        <a href="#fn6">
          footnote here
        </a>
      </sup>
      more text here
    </a>
  </body>
</html>
~~~

Fails with:
~~~
line 9 column 7 - Warning: missing </sup> before <a>
line 13 column 7 - Warning: discarding unexpected </sup>
line 9 column 7 - Warning: trimming empty <sup>
~~~

Tidy is rendering the `<sub>` tag meaningless.

The same happens with the similar:
~~~{.html}
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>TITLE</title>
  </head>
  <body>
    <a href="#ref">
      text here
      <cite>
        <a href="#abc">
          footnote here
        </a>
      </cite>
      more text here
    </a>
  </body>
</html>
~~~

One could imagine that Tidy does not understand nested `<a>` tags, but that is not the case, as the following document passes without problems:

~~~{.html}
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>TITLE</title>
  </head>
  <body>
    <a href="#ref">
      text here
        <a href="#abc">
          footnote here
        </a>
      more text here
    </a>
  </body>
</html>
~~~

This issue shows up with the way some transpilers generate footnotes, when the element already is wrapped in an `<a>` by virtue of being a header, for example.

In my opinion the documents presented above should all be legal legal. I would be nice for Tidy to support them.

**Comment by geoffmcl** [comment]
Thanks for your post.

As you may know the latest development branch is develop-500
$ git checkout develop-500
and all issues can only be tested against this.

Now, concerning nested a elements... maybe it 'should' be legal,
and a quick browser test seems to indicate they have no problem, BUT -

It was stated very clearly in W3C for HTML4:
12.2.2 Nested links are illegal
Links and anchors defined by the A element must not be nested; an A element must not contain any other A elements.

And for HTML5 it is a little different, but basically similar...
http://www.w3.org/html/wg/drafts/html/master/single-page.html#the-a-element
http://www.w3.org/TR/html5/text-level-semantics.html#the-a-element

To quote (my emphasis): "The a element may be wrapped around entire paragraphs, lists, tables, and so forth, even 
entire sections, so long as there is NO interactive content within (e.g. buttons or other links)."

All three of your samples FAIL in the W3C validators, with -
Error: An a start tag seen but an element of the same type was already open.

So to me the real problem here is that the current Tidy 4.9.++ passes 
your third example, and clearly it should NOT! If you do not beat me to it 
I will get around to posting a NEW issue, something like -
Nested a elements pass without error!
using your 3rd sample...

And while Tidy does get into a MESS on your samples 1 and 2, erroneously citing 
the sub and cite elements, that would be fixed when fixing the above no nested 
interactive content problem...

And just to prove, sub, sup and cite are no problem to dev5 Tidy, try my input\in_95-4.html sample, containing -
````
<!DOCTYPE html>
<html>
<head>
<meta charset=utf-8>
<title>should be legal #95</title>
</head>
<body>
<p>This text contains <sub>subscript</sub> text.</p>
<p>This text contains <sup>superscript</sup> text.</p>
<p>This text contains <cite>cite</cite> text.</p>
</body>
</html>
````

which also passes the W3C validators...

So in summery, I think this should be closed after you try the above test and a new issue about nested a opened...

**Comment by balthisar** [comment]
Develop-500 is giving me the following out for case 3 with default options:
~~~
<body>
<a href="#ref">text here</a> <a href="#abc">footnote here</a> more
text here
</body>
~~~

I'm guessing you fixed it and I missed it in the change logs. I think this is proper behavior, especially with the warnings generated. 

I'll close this.
