### ISSUE TITLE
omit-optional-tags makes <a> elements output in a single line separated by space

### ISSUE THREAD

**Issue by Czarnodziej** [htacg/tidy-html5#97]
omit-optional-tags: no

 ```
<a>something</a>
<a>something</a>
<a>something</a>
 ```
omit-optional-tags: yes
 ```
<a>something</a> <a>something</a> <a>something</a>
 ```

**Comment by geoffmcl** [comment]
As you may know the latest development branch is develop-500
$ git checkout develop-500
and issues can only be tested against this branch.

In testing with this branch I find whether --omit-optional-tags no,
the default, or with --omit-optional-tags yes, the a elements are output
in a single line separated by a space.

And even testing with the last 2009 release of tidy, of course not using 
omit-optional-tags since it did not have that option, they are also 
output in a single line...

Input:
````
<!DOCTYPE html>
<html>
<head>
<title>omit-optional-tags makes a elements output in a single line separated by space #97</title>
<meta charset="utf-8">
</head>
<body>
<a>something</a>
<a>something</a>
<a>something</a>
</body>
</html>
````

Output, adding --tidy-mark no, and --show-info no, the default
--omit-optional-tags no
````
<!DOCTYPE html>
<html>
<head>
<title>omit-optional-tags makes a elements output in a single line
separated by space #97</title>
<meta charset="utf-8">
</head>
<body>
<a>something</a> <a>something</a> <a>something</a>
</body>
</html>
````

Output with --omit-optional-tags yes
````
<!DOCTYPE html>
<title>omit-optional-tags makes a elements output in a single line
separated by space #97</title>
<meta charset="utf-8">
<a>something</a> <a>something</a> <a>something</a>
````

Please check again using the develop-500 branch, and if no change 
when adding omit-optional-tags please close...

Thanks for your post.
